/*******************************************************************************
 *  Copyright (C) 2024 Intel Corporation
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions
 *  and limitations under the License.
 *
 *
 *  SPDX-License-Identifier: Apache-2.0
 ******************************************************************************/

// generated by split_classes.pl
#ifndef __REGISTER_INCLUDES_GPIO_PAIR_REGS_MDIO_CTRL_MUTABLE_H__
#define __REGISTER_INCLUDES_GPIO_PAIR_REGS_MDIO_CTRL_MUTABLE_H__


#include <cstdint>
#include <cassert>
#include <array>
#include <vector>
#include <string>
#include <boost/lexical_cast.hpp>
#include <boost/format.hpp>
#include <model_core/register_block.h>
#include <shared/bitvector.h>












namespace tofinoB0 {
  namespace register_classes {

class GpioPairRegsMdioCtrlMutable : public model_core::RegisterBlock<RegisterCallback> {
public:
  enum TofinoEnum {
    kEthgpiobr,
    kEthgpiotl
  };
public:
  GpioPairRegsMdioCtrlMutable(
      int chipNumber, TofinoEnum selector_tofino, int index_gpio_pair_regs, RegisterCallback& write_callback = 0, RegisterCallback& read_callback = 0
  )
    : RegisterBlock(chipNumber, StartOffset(selector_tofino, index_gpio_pair_regs), 4, true, write_callback, read_callback, std::string("GpioPairRegsMdioCtrlMutable")+":"+boost::lexical_cast<std::string>(selector_tofino) + "," + boost::lexical_cast<std::string>(index_gpio_pair_regs))
    {
    }
  GpioPairRegsMdioCtrlMutable(
      
  )
    : RegisterBlock(0, 0, 0, true, 0, 0, "GpioPairRegsMdioCtrlMutable")
    {
    }
public:






  uint8_t mdio_portaddr() { return mdio_portaddr_; }
  void mdio_portaddr(const uint8_t &v) { mdio_portaddr_=v; }






  uint8_t mdio_devaddr() { return mdio_devaddr_; }
  void mdio_devaddr(const uint8_t &v) { mdio_devaddr_=v; }










  uint8_t mdio_code() { return mdio_code_; }
  void mdio_code(const uint8_t &v) { mdio_code_=v; }








  uint8_t mdio_type() { return mdio_type_; }
  void mdio_type(const uint8_t &v) { mdio_type_=v; }






  uint8_t mdio_exec() { return mdio_exec_; }
  void mdio_exec(const uint8_t &v) { mdio_exec_=v; }

  bool read(
      uint32_t offset, uint32_t* data
      ) const {
    if (read_callback_) read_callback_();
    *data = (mdio_portaddr_ & 0x1f);
    *data |= ((mdio_devaddr_ & 0x1f) << 5);
    *data |= ((mdio_code_ & 0x3) << 10);
    *data |= ((mdio_type_ & 0x1) << 12);
    *data |= ((mdio_exec_ & 0x1) << 15);
    return true;
  }


  bool write(
      uint32_t offset, uint32_t data
      ) {
    mdio_portaddr_ = (data & 0x1f);
    mdio_devaddr_ = ((data >> 5) & 0x1f);
    mdio_code_ = ((data >> 10) & 0x3);
    mdio_type_ = ((data >> 12) & 0x1);
    mdio_exec_ = ((data >> 15) & 0x1);
    if (write_callback_) write_callback_();
    return true;
  }

  void reset(
      
      ) {
    mdio_portaddr_ = 0x0;
    mdio_devaddr_ = 0x0;
    mdio_code_ = 0x0;
    mdio_type_ = 0x0;
    mdio_exec_ = 0x0;
    if (write_callback_) write_callback_();
  }

  std::string to_string(
      uint32_t offset, bool print_zeros = false, std::string indent_string = ""
      ) const {
    std::string r("");
    bool all_zeros=true;
    r += indent_string + std::string("GpioPairRegsMdioCtrlMutable") + ":\n";
    r += indent_string + "  " + std::string("mdio_portaddr") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(mdio_portaddr_) ) + "\n";
    all_zeros &= (0 == mdio_portaddr_);
    r += indent_string + "  " + std::string("mdio_devaddr") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(mdio_devaddr_) ) + "\n";
    all_zeros &= (0 == mdio_devaddr_);
    r += indent_string + "  " + std::string("mdio_code") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(mdio_code_) ) + "\n";
    all_zeros &= (0 == mdio_code_);
    r += indent_string + "  " + std::string("mdio_type") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(mdio_type_) ) + "\n";
    all_zeros &= (0 == mdio_type_);
    r += indent_string + "  " + std::string("mdio_exec") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(mdio_exec_) ) + "\n";
    all_zeros &= (0 == mdio_exec_);
    if (all_zeros && !print_zeros) {
      return("");
    }
    else {
      return r;
    }
  }

  std::string to_string(
      bool print_zeros = false, std::string indent_string = ""
      ) const {
    std::string r("");
    bool all_zeros=true;
    r += indent_string + std::string("GpioPairRegsMdioCtrlMutable") + ":\n";
    r += indent_string + "  " + std::string("mdio_portaddr") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(mdio_portaddr_) ) + "\n";
    all_zeros &= (0 == mdio_portaddr_);
    r += indent_string + "  " + std::string("mdio_devaddr") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(mdio_devaddr_) ) + "\n";
    all_zeros &= (0 == mdio_devaddr_);
    r += indent_string + "  " + std::string("mdio_code") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(mdio_code_) ) + "\n";
    all_zeros &= (0 == mdio_code_);
    r += indent_string + "  " + std::string("mdio_type") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(mdio_type_) ) + "\n";
    all_zeros &= (0 == mdio_type_);
    r += indent_string + "  " + std::string("mdio_exec") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(mdio_exec_) ) + "\n";
    all_zeros &= (0 == mdio_exec_);
    if (all_zeros && !print_zeros) {
      return("");
    }
    else {
      return r;
    }
  }

private:
  uint8_t mdio_portaddr_;
  uint8_t mdio_devaddr_;
  uint8_t mdio_code_;
  uint8_t mdio_type_;
  uint8_t mdio_exec_;
private:
  static int StartOffset(
      TofinoEnum selector_tofino, int index_gpio_pair_regs
      ) {
    int offset=0;
    switch (selector_tofino) {
      case kEthgpiobr:
        offset += 0x1820000; // to get to ethgpiobr
        assert(index_gpio_pair_regs < 6);
        offset += index_gpio_pair_regs * 0x2c; // gpio_pair_regs[]
        offset += 0x20; // to get to mdio_ctrl
        break;
      case kEthgpiotl:
        offset += 0x1840000; // to get to ethgpiotl
        assert(index_gpio_pair_regs < 6);
        offset += index_gpio_pair_regs * 0x2c; // gpio_pair_regs[]
        offset += 0x20; // to get to mdio_ctrl
        break;
      default:
        assert(0);
        break;
    }
    return offset;
  }

};









  }; // namespace register_classes
}; // namespace tofinoB0

#endif // __REGISTER_INCLUDES_GPIO_PAIR_REGS_MDIO_CTRL_MUTABLE_H__
