/*******************************************************************************
 *  Copyright (C) 2024 Intel Corporation
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions
 *  and limitations under the License.
 *
 *
 *  SPDX-License-Identifier: Apache-2.0
 ******************************************************************************/

// generated by split_classes.pl
#ifndef __REGISTER_INCLUDES_LFLTR_LQT_STATE_MUTABLE_H__
#define __REGISTER_INCLUDES_LFLTR_LQT_STATE_MUTABLE_H__


#include <cstdint>
#include <cassert>
#include <array>
#include <vector>
#include <string>
#include <boost/lexical_cast.hpp>
#include <boost/format.hpp>
#include <model_core/register_block.h>
#include <shared/bitvector.h>












namespace tofinoB0 {
  namespace register_classes {

class LfltrLqtStateMutable : public model_core::RegisterBlock<RegisterCallback> {
public:
  enum DvslAddrmapEnum {
    kLfltr0,
    kLfltr1,
    kLfltr2,
    kLfltr3
  };
public:
  LfltrLqtStateMutable(
      int chipNumber, DvslAddrmapEnum selector_dvsl_addrmap, RegisterCallback& write_callback = 0, RegisterCallback& read_callback = 0
  )
    : RegisterBlock(chipNumber, StartOffset(selector_dvsl_addrmap), 4, true, write_callback, read_callback, std::string("LfltrLqtStateMutable")+":"+boost::lexical_cast<std::string>(selector_dvsl_addrmap))
    {
    }
  LfltrLqtStateMutable(
      
  )
    : RegisterBlock(0, 0, 0, true, 0, 0, "LfltrLqtStateMutable")
    {
    }
public:










  uint8_t state0() { return state0_; }
  void state0(const uint8_t &v) { state0_=v; }










  uint8_t state1() { return state1_; }
  void state1(const uint8_t &v) { state1_=v; }





  uint8_t empty0() { return empty0_; }
  void empty0(const uint8_t &v) { empty0_=v; }





  uint8_t empty1() { return empty1_; }
  void empty1(const uint8_t &v) { empty1_=v; }





  uint8_t full0() { return full0_; }
  void full0(const uint8_t &v) { full0_=v; }





  uint8_t full1() { return full1_; }
  void full1(const uint8_t &v) { full1_=v; }

  bool read(
      uint32_t offset, uint32_t* data
      ) const {
    if (read_callback_) read_callback_();
    *data = (state0_ & 0x7);
    *data |= ((state1_ & 0x7) << 4);
    *data |= ((empty0_ & 0x1) << 8);
    *data |= ((empty1_ & 0x1) << 9);
    *data |= ((full0_ & 0x1) << 10);
    *data |= ((full1_ & 0x1) << 11);
    return true;
  }


  bool write(
      uint32_t offset, uint32_t data
      ) {
    state0_ = (data & 0x7);
    state1_ = ((data >> 4) & 0x7);
    empty0_ = ((data >> 8) & 0x1);
    empty1_ = ((data >> 9) & 0x1);
    full0_ = ((data >> 10) & 0x1);
    full1_ = ((data >> 11) & 0x1);
    if (write_callback_) write_callback_();
    return true;
  }

  void reset(
      
      ) {
    state0_ = 0x0;
    state1_ = 0x0;
    empty0_ = 0x0;
    empty1_ = 0x0;
    full0_ = 0x0;
    full1_ = 0x0;
    if (write_callback_) write_callback_();
  }

  std::string to_string(
      uint32_t offset, bool print_zeros = false, std::string indent_string = ""
      ) const {
    std::string r("");
    bool all_zeros=true;
    r += indent_string + std::string("LfltrLqtStateMutable") + ":\n";
    r += indent_string + "  " + std::string("state0") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(state0_) ) + "\n";
    all_zeros &= (0 == state0_);
    r += indent_string + "  " + std::string("state1") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(state1_) ) + "\n";
    all_zeros &= (0 == state1_);
    r += indent_string + "  " + std::string("empty0") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(empty0_) ) + "\n";
    all_zeros &= (0 == empty0_);
    r += indent_string + "  " + std::string("empty1") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(empty1_) ) + "\n";
    all_zeros &= (0 == empty1_);
    r += indent_string + "  " + std::string("full0") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(full0_) ) + "\n";
    all_zeros &= (0 == full0_);
    r += indent_string + "  " + std::string("full1") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(full1_) ) + "\n";
    all_zeros &= (0 == full1_);
    if (all_zeros && !print_zeros) {
      return("");
    }
    else {
      return r;
    }
  }

  std::string to_string(
      bool print_zeros = false, std::string indent_string = ""
      ) const {
    std::string r("");
    bool all_zeros=true;
    r += indent_string + std::string("LfltrLqtStateMutable") + ":\n";
    r += indent_string + "  " + std::string("state0") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(state0_) ) + "\n";
    all_zeros &= (0 == state0_);
    r += indent_string + "  " + std::string("state1") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(state1_) ) + "\n";
    all_zeros &= (0 == state1_);
    r += indent_string + "  " + std::string("empty0") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(empty0_) ) + "\n";
    all_zeros &= (0 == empty0_);
    r += indent_string + "  " + std::string("empty1") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(empty1_) ) + "\n";
    all_zeros &= (0 == empty1_);
    r += indent_string + "  " + std::string("full0") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(full0_) ) + "\n";
    all_zeros &= (0 == full0_);
    r += indent_string + "  " + std::string("full1") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(full1_) ) + "\n";
    all_zeros &= (0 == full1_);
    if (all_zeros && !print_zeros) {
      return("");
    }
    else {
      return r;
    }
  }

private:
  uint8_t state0_;
  uint8_t state1_;
  uint8_t empty0_;
  uint8_t empty1_;
  uint8_t full0_;
  uint8_t full1_;
private:
  static int StartOffset(
      DvslAddrmapEnum selector_dvsl_addrmap
      ) {
    int offset=0;
    switch (selector_dvsl_addrmap) {
      case kLfltr0:
        offset += 0x200000; // to get to lfltr0
        offset += 0x20000; // to get to ctrl
        offset += 0x78; // to get to lqt_state
        break;
      case kLfltr1:
        offset += 0x240000; // to get to lfltr1
        offset += 0x20000; // to get to ctrl
        offset += 0x78; // to get to lqt_state
        break;
      case kLfltr2:
        offset += 0x280000; // to get to lfltr2
        offset += 0x20000; // to get to ctrl
        offset += 0x78; // to get to lqt_state
        break;
      case kLfltr3:
        offset += 0x2c0000; // to get to lfltr3
        offset += 0x20000; // to get to ctrl
        offset += 0x78; // to get to lqt_state
        break;
      default:
        assert(0);
        break;
    }
    return offset;
  }

};









  }; // namespace register_classes
}; // namespace tofinoB0

#endif // __REGISTER_INCLUDES_LFLTR_LQT_STATE_MUTABLE_H__
