/*******************************************************************************
 *  Copyright (C) 2024 Intel Corporation
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions
 *  and limitations under the License.
 *
 *
 *  SPDX-License-Identifier: Apache-2.0
 ******************************************************************************/

// generated by split_classes.pl
#ifndef __REGISTER_INCLUDES_LFLTR_COMMON_CTRL_H__
#define __REGISTER_INCLUDES_LFLTR_COMMON_CTRL_H__


#include <cstdint>
#include <cassert>
#include <array>
#include <vector>
#include <string>
#include <boost/lexical_cast.hpp>
#include <boost/format.hpp>
#include <model_core/register_block.h>
#include <shared/bitvector.h>












namespace tofinoB0 {
  namespace register_classes {

class LfltrCommonCtrl : public model_core::RegisterBlock<RegisterCallback> {
public:
  enum DvslAddrmapEnum {
    kLfltr0,
    kLfltr1,
    kLfltr2,
    kLfltr3
  };
public:
  LfltrCommonCtrl(
      int chipNumber, DvslAddrmapEnum selector_dvsl_addrmap, RegisterCallback& write_callback = 0, RegisterCallback& read_callback = 0
  )
    : RegisterBlock(chipNumber, StartOffset(selector_dvsl_addrmap), 4, false, write_callback, read_callback, std::string("LfltrCommonCtrl")+":"+boost::lexical_cast<std::string>(selector_dvsl_addrmap))
    {
    }
  LfltrCommonCtrl(
      
  )
    : RegisterBlock(0, 0, 0, false, 0, 0, "LfltrCommonCtrl")
    {
    }
public:






  uint8_t &learn_dis() { return learn_dis_; }






  uint8_t &ecc_dec_dis() { return ecc_dec_dis_; }





  uint8_t &parity_dec_dis() { return parity_dec_dis_; }

  bool read(
      uint32_t offset, uint32_t* data
      ) const {
    if (read_callback_) read_callback_();
    *data = (learn_dis_ & 0x1);
    *data |= ((ecc_dec_dis_ & 0x1) << 1);
    *data |= ((parity_dec_dis_ & 0x1) << 2);
    return true;
  }


  bool write(
      uint32_t offset, uint32_t data
      ) {
    learn_dis_ = (data & 0x1);
    ecc_dec_dis_ = ((data >> 1) & 0x1);
    parity_dec_dis_ = ((data >> 2) & 0x1);
    if (write_callback_) write_callback_();
    return true;
  }

  void reset(
      
      ) {
    learn_dis_ = 0x0;
    ecc_dec_dis_ = 0x0;
    parity_dec_dis_ = 0x0;
    if (write_callback_) write_callback_();
  }

  std::string to_string(
      uint32_t offset, bool print_zeros = false, std::string indent_string = ""
      ) const {
    std::string r("");
    bool all_zeros=true;
    r += indent_string + std::string("LfltrCommonCtrl") + ":\n";
    r += indent_string + "  " + std::string("learn_dis") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(learn_dis_) ) + "\n";
    all_zeros &= (0 == learn_dis_);
    r += indent_string + "  " + std::string("ecc_dec_dis") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(ecc_dec_dis_) ) + "\n";
    all_zeros &= (0 == ecc_dec_dis_);
    r += indent_string + "  " + std::string("parity_dec_dis") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(parity_dec_dis_) ) + "\n";
    all_zeros &= (0 == parity_dec_dis_);
    if (all_zeros && !print_zeros) {
      return("");
    }
    else {
      return r;
    }
  }

  std::string to_string(
      bool print_zeros = false, std::string indent_string = ""
      ) const {
    std::string r("");
    bool all_zeros=true;
    r += indent_string + std::string("LfltrCommonCtrl") + ":\n";
    r += indent_string + "  " + std::string("learn_dis") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(learn_dis_) ) + "\n";
    all_zeros &= (0 == learn_dis_);
    r += indent_string + "  " + std::string("ecc_dec_dis") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(ecc_dec_dis_) ) + "\n";
    all_zeros &= (0 == ecc_dec_dis_);
    r += indent_string + "  " + std::string("parity_dec_dis") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(parity_dec_dis_) ) + "\n";
    all_zeros &= (0 == parity_dec_dis_);
    if (all_zeros && !print_zeros) {
      return("");
    }
    else {
      return r;
    }
  }

private:
  uint8_t learn_dis_;
  uint8_t ecc_dec_dis_;
  uint8_t parity_dec_dis_;
private:
  static int StartOffset(
      DvslAddrmapEnum selector_dvsl_addrmap
      ) {
    int offset=0;
    switch (selector_dvsl_addrmap) {
      case kLfltr0:
        offset += 0x200000; // to get to lfltr0
        offset += 0x20000; // to get to ctrl
        offset += 0x14; // to get to common_ctrl
        break;
      case kLfltr1:
        offset += 0x240000; // to get to lfltr1
        offset += 0x20000; // to get to ctrl
        offset += 0x14; // to get to common_ctrl
        break;
      case kLfltr2:
        offset += 0x280000; // to get to lfltr2
        offset += 0x20000; // to get to ctrl
        offset += 0x14; // to get to common_ctrl
        break;
      case kLfltr3:
        offset += 0x2c0000; // to get to lfltr3
        offset += 0x20000; // to get to ctrl
        offset += 0x14; // to get to common_ctrl
        break;
      default:
        assert(0);
        break;
    }
    return offset;
  }

};









  }; // namespace register_classes
}; // namespace tofinoB0

#endif // __REGISTER_INCLUDES_LFLTR_COMMON_CTRL_H__
