/*******************************************************************************
 *  Copyright (C) 2024 Intel Corporation
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions
 *  and limitations under the License.
 *
 *
 *  SPDX-License-Identifier: Apache-2.0
 ******************************************************************************/

// generated by split_classes.pl
#ifndef __REGISTER_INCLUDES_MOVEREG_AD_DIRECT_MUTABLE_H__
#define __REGISTER_INCLUDES_MOVEREG_AD_DIRECT_MUTABLE_H__


#include <cstdint>
#include <cassert>
#include <array>
#include <vector>
#include <string>
#include <boost/lexical_cast.hpp>
#include <boost/format.hpp>
#include <model_core/register_block.h>
#include <shared/bitvector.h>












namespace tofinoB0 {
  namespace register_classes {

class MoveregAdDirectMutable : public model_core::RegisterBlock<RegisterCallback> {
public:
  MoveregAdDirectMutable(
      int chipNumber, int index_pipe_addrmap, int index_mau_addrmap, int index_movereg_ad_direct, RegisterCallback& write_callback = 0, RegisterCallback& read_callback = 0
  )
    : RegisterBlock(chipNumber, StartOffset(index_pipe_addrmap, index_mau_addrmap, index_movereg_ad_direct), 4, true, write_callback, read_callback, std::string("MoveregAdDirectMutable")+":"+boost::lexical_cast<std::string>(index_pipe_addrmap) + "," + boost::lexical_cast<std::string>(index_mau_addrmap) + "," + boost::lexical_cast<std::string>(index_movereg_ad_direct))
    {
    }
  MoveregAdDirectMutable(
      
  )
    : RegisterBlock(0, 0, 0, true, 0, 0, "MoveregAdDirectMutable")
    {
    }
public:
  uint16_t movereg_ad_direct() { return movereg_ad_direct_; }
  void movereg_ad_direct(const uint16_t &v) { movereg_ad_direct_=v; }

  bool read(
      uint32_t offset, uint32_t* data
      ) const {
    if (read_callback_) read_callback_();
    *data = movereg_ad_direct_;
    return true;
  }


  bool write(
      uint32_t offset, uint32_t data
      ) {
    movereg_ad_direct_ = data;
    if (write_callback_) write_callback_();
    return true;
  }

  void reset(
      
      ) {
    movereg_ad_direct_ = 0x0;
    if (write_callback_) write_callback_();
  }

  std::string to_string(
      uint32_t offset, bool print_zeros = false, std::string indent_string = ""
      ) const {
    std::string r("");
    bool all_zeros=true;
    r += indent_string + std::string("MoveregAdDirectMutable") + ":\n";
    r += indent_string + "  " + std::string("movereg_ad_direct") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(movereg_ad_direct_) ) + "\n";
    all_zeros &= (0 == movereg_ad_direct_);
    if (all_zeros && !print_zeros) {
      return("");
    }
    else {
      return r;
    }
  }

  std::string to_string(
      bool print_zeros = false, std::string indent_string = ""
      ) const {
    std::string r("");
    bool all_zeros=true;
    r += indent_string + std::string("MoveregAdDirectMutable") + ":\n";
    r += indent_string + "  " + std::string("movereg_ad_direct") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(movereg_ad_direct_) ) + "\n";
    all_zeros &= (0 == movereg_ad_direct_);
    if (all_zeros && !print_zeros) {
      return("");
    }
    else {
      return r;
    }
  }

private:
  uint16_t movereg_ad_direct_;
private:
  static int StartOffset(
      int index_pipe_addrmap, int index_mau_addrmap, int index_movereg_ad_direct
      ) {
    int offset=0;
    offset += 0x2000000; // to get to pipes
    assert(index_pipe_addrmap < 4);
    offset += index_pipe_addrmap * 0x800000; // pipe_addrmap[]
    assert(index_mau_addrmap < 12);
    offset += index_mau_addrmap * 0x80000; // mau_addrmap[]
    offset += 0x18000; // to get to match
    offset += 0x140; // to get to movereg_ad_direct
    assert(index_movereg_ad_direct < 3);
    offset += index_movereg_ad_direct * 0x4; // movereg_ad_direct[]
    return offset;
  }

};











  }; // namespace register_classes
}; // namespace tofinoB0

#endif // __REGISTER_INCLUDES_MOVEREG_AD_DIRECT_MUTABLE_H__
