/*******************************************************************************
 *  Copyright (C) 2024 Intel Corporation
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions
 *  and limitations under the License.
 *
 *
 *  SPDX-License-Identifier: Apache-2.0
 ******************************************************************************/

// generated by split_classes.pl
#ifndef __REGISTER_INCLUDES_PRC_PIPE_CONTROL_MUTABLE_H__
#define __REGISTER_INCLUDES_PRC_PIPE_CONTROL_MUTABLE_H__


#include <cstdint>
#include <cassert>
#include <array>
#include <vector>
#include <string>
#include <boost/lexical_cast.hpp>
#include <boost/format.hpp>
#include <model_core/register_block.h>
#include <shared/bitvector.h>












namespace tofinoB0 {
  namespace register_classes {

class PrcPipeControlMutable : public model_core::RegisterBlock<RegisterCallback> {
public:
  PrcPipeControlMutable(
      int chipNumber, int index_tm_prc_pipe_rspec, RegisterCallback& write_callback = 0, RegisterCallback& read_callback = 0
  )
    : RegisterBlock(chipNumber, StartOffset(index_tm_prc_pipe_rspec), 4, true, write_callback, read_callback, std::string("PrcPipeControlMutable")+":"+boost::lexical_cast<std::string>(index_tm_prc_pipe_rspec))
    {
    }
  PrcPipeControlMutable(
      
  )
    : RegisterBlock(0, 0, 0, true, 0, 0, "PrcPipeControlMutable")
    {
    }
public:





  uint8_t qac_cnt_en() { return qac_cnt_en_; }
  void qac_cnt_en(const uint8_t &v) { qac_cnt_en_=v; }





  uint8_t qac_zero_cnt_en() { return qac_zero_cnt_en_; }
  void qac_zero_cnt_en(const uint8_t &v) { qac_zero_cnt_en_=v; }





  uint8_t pex_cnt_en() { return pex_cnt_en_; }
  void pex_cnt_en(const uint8_t &v) { pex_cnt_en_=v; }





  uint8_t pex_zero_cnt_en() { return pex_zero_cnt_en_; }
  void pex_zero_cnt_en(const uint8_t &v) { pex_zero_cnt_en_=v; }





  uint8_t freeze_on_error() { return freeze_on_error_; }
  void freeze_on_error(const uint8_t &v) { freeze_on_error_=v; }

  bool read(
      uint32_t offset, uint32_t* data
      ) const {
    if (read_callback_) read_callback_();
    *data = (qac_cnt_en_ & 0x1);
    *data |= ((qac_zero_cnt_en_ & 0x1) << 1);
    *data |= ((pex_cnt_en_ & 0x1) << 2);
    *data |= ((pex_zero_cnt_en_ & 0x1) << 3);
    *data |= ((freeze_on_error_ & 0x1) << 30);
    return true;
  }


  bool write(
      uint32_t offset, uint32_t data
      ) {
    qac_cnt_en_ = (data & 0x1);
    qac_zero_cnt_en_ = ((data >> 1) & 0x1);
    pex_cnt_en_ = ((data >> 2) & 0x1);
    pex_zero_cnt_en_ = ((data >> 3) & 0x1);
    freeze_on_error_ = ((data >> 30) & 0x1);
    if (write_callback_) write_callback_();
    return true;
  }

  void reset(
      
      ) {
    qac_cnt_en_ = 0x0;
    qac_zero_cnt_en_ = 0x0;
    pex_cnt_en_ = 0x0;
    pex_zero_cnt_en_ = 0x0;
    freeze_on_error_ = 0x0;
    if (write_callback_) write_callback_();
  }

  std::string to_string(
      uint32_t offset, bool print_zeros = false, std::string indent_string = ""
      ) const {
    std::string r("");
    bool all_zeros=true;
    r += indent_string + std::string("PrcPipeControlMutable") + ":\n";
    r += indent_string + "  " + std::string("qac_cnt_en") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(qac_cnt_en_) ) + "\n";
    all_zeros &= (0 == qac_cnt_en_);
    r += indent_string + "  " + std::string("qac_zero_cnt_en") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(qac_zero_cnt_en_) ) + "\n";
    all_zeros &= (0 == qac_zero_cnt_en_);
    r += indent_string + "  " + std::string("pex_cnt_en") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(pex_cnt_en_) ) + "\n";
    all_zeros &= (0 == pex_cnt_en_);
    r += indent_string + "  " + std::string("pex_zero_cnt_en") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(pex_zero_cnt_en_) ) + "\n";
    all_zeros &= (0 == pex_zero_cnt_en_);
    r += indent_string + "  " + std::string("freeze_on_error") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(freeze_on_error_) ) + "\n";
    all_zeros &= (0 == freeze_on_error_);
    if (all_zeros && !print_zeros) {
      return("");
    }
    else {
      return r;
    }
  }

  std::string to_string(
      bool print_zeros = false, std::string indent_string = ""
      ) const {
    std::string r("");
    bool all_zeros=true;
    r += indent_string + std::string("PrcPipeControlMutable") + ":\n";
    r += indent_string + "  " + std::string("qac_cnt_en") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(qac_cnt_en_) ) + "\n";
    all_zeros &= (0 == qac_cnt_en_);
    r += indent_string + "  " + std::string("qac_zero_cnt_en") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(qac_zero_cnt_en_) ) + "\n";
    all_zeros &= (0 == qac_zero_cnt_en_);
    r += indent_string + "  " + std::string("pex_cnt_en") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(pex_cnt_en_) ) + "\n";
    all_zeros &= (0 == pex_cnt_en_);
    r += indent_string + "  " + std::string("pex_zero_cnt_en") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(pex_zero_cnt_en_) ) + "\n";
    all_zeros &= (0 == pex_zero_cnt_en_);
    r += indent_string + "  " + std::string("freeze_on_error") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(freeze_on_error_) ) + "\n";
    all_zeros &= (0 == freeze_on_error_);
    if (all_zeros && !print_zeros) {
      return("");
    }
    else {
      return r;
    }
  }

private:
  uint8_t qac_cnt_en_;
  uint8_t qac_zero_cnt_en_;
  uint8_t pex_cnt_en_;
  uint8_t pex_zero_cnt_en_;
  uint8_t freeze_on_error_;
private:
  static int StartOffset(
      int index_tm_prc_pipe_rspec
      ) {
    int offset=0;
    offset += 0x400000; // to get to tm_top
    offset += 0x1c0000; // to get to tm_prc_top
    assert(index_tm_prc_pipe_rspec < 4);
    offset += index_tm_prc_pipe_rspec * 0x8000; // tm_prc_pipe_rspec[]
    return offset;
  }

};









  }; // namespace register_classes
}; // namespace tofinoB0

#endif // __REGISTER_INCLUDES_PRC_PIPE_CONTROL_MUTABLE_H__
