/*******************************************************************************
 *  Copyright (C) 2024 Intel Corporation
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions
 *  and limitations under the License.
 *
 *
 *  SPDX-License-Identifier: Apache-2.0
 ******************************************************************************/

// generated by split_classes.pl
#ifndef __REGISTER_INCLUDES_QCLC_PT_SPD_H__
#define __REGISTER_INCLUDES_QCLC_PT_SPD_H__


#include <cstdint>
#include <cassert>
#include <array>
#include <vector>
#include <string>
#include <boost/lexical_cast.hpp>
#include <boost/format.hpp>
#include <model_core/register_block.h>
#include <shared/bitvector.h>












namespace tofinoB0 {
  namespace register_classes {

class QclcPtSpd : public model_core::RegisterBlock<RegisterCallback> {
public:
  QclcPtSpd(
      int chipNumber, int index_qclc_pt_spd, RegisterCallback& write_callback = 0, RegisterCallback& read_callback = 0
  )
    : RegisterBlock(chipNumber, StartOffset(index_qclc_pt_spd), 4, false, write_callback, read_callback, std::string("QclcPtSpd")+":"+boost::lexical_cast<std::string>(index_qclc_pt_spd))
    {
    }
  QclcPtSpd(
      
  )
    : RegisterBlock(0, 0, 0, false, 0, 0, "QclcPtSpd")
    {
    }
public:







  uint8_t &pt_spd_0() { return pt_spd_0_; }





  uint8_t &pt_spd_1() { return pt_spd_1_; }





  uint8_t &pt_spd_2() { return pt_spd_2_; }





  uint8_t &pt_spd_3() { return pt_spd_3_; }





  uint8_t &pt_spd_4() { return pt_spd_4_; }





  uint8_t &pt_spd_5() { return pt_spd_5_; }





  uint8_t &pt_spd_6() { return pt_spd_6_; }





  uint8_t &pt_spd_7() { return pt_spd_7_; }

  bool read(
      uint32_t offset, uint32_t* data
      ) const {
    if (read_callback_) read_callback_();
    *data = (pt_spd_0_ & 0xf);
    *data |= ((pt_spd_1_ & 0xf) << 4);
    *data |= ((pt_spd_2_ & 0xf) << 8);
    *data |= ((pt_spd_3_ & 0xf) << 12);
    *data |= ((pt_spd_4_ & 0xf) << 16);
    *data |= ((pt_spd_5_ & 0xf) << 20);
    *data |= ((pt_spd_6_ & 0xf) << 24);
    *data |= ((pt_spd_7_ & 0xf) << 28);
    return true;
  }


  bool write(
      uint32_t offset, uint32_t data
      ) {
    pt_spd_0_ = (data & 0xf);
    pt_spd_1_ = ((data >> 4) & 0xf);
    pt_spd_2_ = ((data >> 8) & 0xf);
    pt_spd_3_ = ((data >> 12) & 0xf);
    pt_spd_4_ = ((data >> 16) & 0xf);
    pt_spd_5_ = ((data >> 20) & 0xf);
    pt_spd_6_ = ((data >> 24) & 0xf);
    pt_spd_7_ = ((data >> 28) & 0xf);
    if (write_callback_) write_callback_();
    return true;
  }

  void reset(
      
      ) {
    pt_spd_0_ = 0x0;
    pt_spd_1_ = 0x0;
    pt_spd_2_ = 0x0;
    pt_spd_3_ = 0x0;
    pt_spd_4_ = 0x0;
    pt_spd_5_ = 0x0;
    pt_spd_6_ = 0x0;
    pt_spd_7_ = 0x0;
    if (write_callback_) write_callback_();
  }

  std::string to_string(
      uint32_t offset, bool print_zeros = false, std::string indent_string = ""
      ) const {
    std::string r("");
    bool all_zeros=true;
    r += indent_string + std::string("QclcPtSpd") + ":\n";
    r += indent_string + "  " + std::string("pt_spd_0") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(pt_spd_0_) ) + "\n";
    all_zeros &= (0 == pt_spd_0_);
    r += indent_string + "  " + std::string("pt_spd_1") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(pt_spd_1_) ) + "\n";
    all_zeros &= (0 == pt_spd_1_);
    r += indent_string + "  " + std::string("pt_spd_2") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(pt_spd_2_) ) + "\n";
    all_zeros &= (0 == pt_spd_2_);
    r += indent_string + "  " + std::string("pt_spd_3") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(pt_spd_3_) ) + "\n";
    all_zeros &= (0 == pt_spd_3_);
    r += indent_string + "  " + std::string("pt_spd_4") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(pt_spd_4_) ) + "\n";
    all_zeros &= (0 == pt_spd_4_);
    r += indent_string + "  " + std::string("pt_spd_5") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(pt_spd_5_) ) + "\n";
    all_zeros &= (0 == pt_spd_5_);
    r += indent_string + "  " + std::string("pt_spd_6") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(pt_spd_6_) ) + "\n";
    all_zeros &= (0 == pt_spd_6_);
    r += indent_string + "  " + std::string("pt_spd_7") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(pt_spd_7_) ) + "\n";
    all_zeros &= (0 == pt_spd_7_);
    if (all_zeros && !print_zeros) {
      return("");
    }
    else {
      return r;
    }
  }

  std::string to_string(
      bool print_zeros = false, std::string indent_string = ""
      ) const {
    std::string r("");
    bool all_zeros=true;
    r += indent_string + std::string("QclcPtSpd") + ":\n";
    r += indent_string + "  " + std::string("pt_spd_0") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(pt_spd_0_) ) + "\n";
    all_zeros &= (0 == pt_spd_0_);
    r += indent_string + "  " + std::string("pt_spd_1") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(pt_spd_1_) ) + "\n";
    all_zeros &= (0 == pt_spd_1_);
    r += indent_string + "  " + std::string("pt_spd_2") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(pt_spd_2_) ) + "\n";
    all_zeros &= (0 == pt_spd_2_);
    r += indent_string + "  " + std::string("pt_spd_3") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(pt_spd_3_) ) + "\n";
    all_zeros &= (0 == pt_spd_3_);
    r += indent_string + "  " + std::string("pt_spd_4") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(pt_spd_4_) ) + "\n";
    all_zeros &= (0 == pt_spd_4_);
    r += indent_string + "  " + std::string("pt_spd_5") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(pt_spd_5_) ) + "\n";
    all_zeros &= (0 == pt_spd_5_);
    r += indent_string + "  " + std::string("pt_spd_6") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(pt_spd_6_) ) + "\n";
    all_zeros &= (0 == pt_spd_6_);
    r += indent_string + "  " + std::string("pt_spd_7") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(pt_spd_7_) ) + "\n";
    all_zeros &= (0 == pt_spd_7_);
    if (all_zeros && !print_zeros) {
      return("");
    }
    else {
      return r;
    }
  }

private:
  uint8_t pt_spd_0_;
  uint8_t pt_spd_1_;
  uint8_t pt_spd_2_;
  uint8_t pt_spd_3_;
  uint8_t pt_spd_4_;
  uint8_t pt_spd_5_;
  uint8_t pt_spd_6_;
  uint8_t pt_spd_7_;
private:
  static int StartOffset(
      int index_qclc_pt_spd
      ) {
    int offset=0;
    offset += 0x400000; // to get to tm_top
    offset += 0x100000; // to get to tm_clc_top
    offset += 0x20000; // to get to clc_common
    offset += 0x100; // to get to pt_speed
    assert(index_qclc_pt_spd < 36);
    offset += index_qclc_pt_spd * 0x4; // qclc_pt_spd[]
    return offset;
  }

};









  }; // namespace register_classes
}; // namespace tofinoB0

#endif // __REGISTER_INCLUDES_QCLC_PT_SPD_H__
