/*******************************************************************************
 *  Copyright (C) 2024 Intel Corporation
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions
 *  and limitations under the License.
 *
 *
 *  SPDX-License-Identifier: Apache-2.0
 ******************************************************************************/

// generated by split_classes.pl
#ifndef __REGISTER_INCLUDES_STATEFUL_METER_ALU_DATA_CTL_MUTABLE_H__
#define __REGISTER_INCLUDES_STATEFUL_METER_ALU_DATA_CTL_MUTABLE_H__


#include <cstdint>
#include <cassert>
#include <array>
#include <vector>
#include <string>
#include <boost/lexical_cast.hpp>
#include <boost/format.hpp>
#include <model_core/register_block.h>
#include <shared/bitvector.h>












namespace tofinoB0 {
  namespace register_classes {

class StatefulMeterAluDataCtlMutable : public model_core::RegisterBlock<RegisterCallback> {
public:
  StatefulMeterAluDataCtlMutable(
      int chipNumber, int index_pipe_addrmap, int index_mau_addrmap, int index_mau_unit_ram_row_addrmap, int index_mau_exactmatch_row_vh_xbar_addrmap, RegisterCallback& write_callback = 0, RegisterCallback& read_callback = 0
  )
    : RegisterBlock(chipNumber, StartOffset(index_pipe_addrmap, index_mau_addrmap, index_mau_unit_ram_row_addrmap, index_mau_exactmatch_row_vh_xbar_addrmap), 4, true, write_callback, read_callback, std::string("StatefulMeterAluDataCtlMutable")+":"+boost::lexical_cast<std::string>(index_pipe_addrmap) + "," + boost::lexical_cast<std::string>(index_mau_addrmap) + "," + boost::lexical_cast<std::string>(index_mau_unit_ram_row_addrmap) + "," + boost::lexical_cast<std::string>(index_mau_exactmatch_row_vh_xbar_addrmap))
    {
    }
  StatefulMeterAluDataCtlMutable(
      
  )
    : RegisterBlock(0, 0, 0, true, 0, 0, "StatefulMeterAluDataCtlMutable")
    {
    }
public:






  uint8_t stateful_meter_alu_data_bytemask() { return stateful_meter_alu_data_bytemask_; }
  void stateful_meter_alu_data_bytemask(const uint8_t &v) { stateful_meter_alu_data_bytemask_=v; }








  uint8_t stateful_meter_alu_data_xbar_ctl() { return stateful_meter_alu_data_xbar_ctl_; }
  void stateful_meter_alu_data_xbar_ctl(const uint8_t &v) { stateful_meter_alu_data_xbar_ctl_=v; }

  bool read(
      uint32_t offset, uint32_t* data
      ) const {
    if (read_callback_) read_callback_();
    *data = stateful_meter_alu_data_bytemask_;
    *data |= ((stateful_meter_alu_data_xbar_ctl_ & 0xf) << 8);
    return true;
  }


  bool write(
      uint32_t offset, uint32_t data
      ) {
    stateful_meter_alu_data_bytemask_ = data;
    stateful_meter_alu_data_xbar_ctl_ = ((data >> 8) & 0xf);
    if (write_callback_) write_callback_();
    return true;
  }

  void reset(
      
      ) {
    stateful_meter_alu_data_bytemask_ = 0x0;
    stateful_meter_alu_data_xbar_ctl_ = 0x0;
    if (write_callback_) write_callback_();
  }

  std::string to_string(
      uint32_t offset, bool print_zeros = false, std::string indent_string = ""
      ) const {
    std::string r("");
    bool all_zeros=true;
    r += indent_string + std::string("StatefulMeterAluDataCtlMutable") + ":\n";
    r += indent_string + "  " + std::string("stateful_meter_alu_data_bytemask") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(stateful_meter_alu_data_bytemask_) ) + "\n";
    all_zeros &= (0 == stateful_meter_alu_data_bytemask_);
    r += indent_string + "  " + std::string("stateful_meter_alu_data_xbar_ctl") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(stateful_meter_alu_data_xbar_ctl_) ) + "\n";
    all_zeros &= (0 == stateful_meter_alu_data_xbar_ctl_);
    if (all_zeros && !print_zeros) {
      return("");
    }
    else {
      return r;
    }
  }

  std::string to_string(
      bool print_zeros = false, std::string indent_string = ""
      ) const {
    std::string r("");
    bool all_zeros=true;
    r += indent_string + std::string("StatefulMeterAluDataCtlMutable") + ":\n";
    r += indent_string + "  " + std::string("stateful_meter_alu_data_bytemask") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(stateful_meter_alu_data_bytemask_) ) + "\n";
    all_zeros &= (0 == stateful_meter_alu_data_bytemask_);
    r += indent_string + "  " + std::string("stateful_meter_alu_data_xbar_ctl") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(stateful_meter_alu_data_xbar_ctl_) ) + "\n";
    all_zeros &= (0 == stateful_meter_alu_data_xbar_ctl_);
    if (all_zeros && !print_zeros) {
      return("");
    }
    else {
      return r;
    }
  }

private:
  uint8_t stateful_meter_alu_data_bytemask_;
  uint8_t stateful_meter_alu_data_xbar_ctl_;
private:
  static int StartOffset(
      int index_pipe_addrmap, int index_mau_addrmap, int index_mau_unit_ram_row_addrmap, int index_mau_exactmatch_row_vh_xbar_addrmap
      ) {
    int offset=0;
    offset += 0x2000000; // to get to pipes
    assert(index_pipe_addrmap < 4);
    offset += index_pipe_addrmap * 0x800000; // pipe_addrmap[]
    assert(index_mau_addrmap < 12);
    offset += index_mau_addrmap * 0x80000; // mau_addrmap[]
    offset += 0x8000; // to get to row
    assert(index_mau_unit_ram_row_addrmap < 8);
    offset += index_mau_unit_ram_row_addrmap * 0x1000; // mau_unit_ram_row_addrmap[]
    offset += 0xf00; // to get to vh_xbar
    assert(index_mau_exactmatch_row_vh_xbar_addrmap < 2);
    offset += index_mau_exactmatch_row_vh_xbar_addrmap * 0x8; // mau_exactmatch_row_vh_xbar_addrmap[]
    offset += 0x4; // to get to stateful_meter_alu_data_ctl
    return offset;
  }

};












  }; // namespace register_classes
}; // namespace tofinoB0

#endif // __REGISTER_INCLUDES_STATEFUL_METER_ALU_DATA_CTL_MUTABLE_H__
