/*******************************************************************************
 *  Copyright (C) 2024 Intel Corporation
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions
 *  and limitations under the License.
 *
 *
 *  SPDX-License-Identifier: Apache-2.0
 ******************************************************************************/

// generated by split_classes.pl
#ifndef __REGISTER_INCLUDES_WAC_DROP_CNT_PRE_FIFO_MUTABLE_H__
#define __REGISTER_INCLUDES_WAC_DROP_CNT_PRE_FIFO_MUTABLE_H__


#include <cstdint>
#include <cassert>
#include <array>
#include <vector>
#include <string>
#include <boost/lexical_cast.hpp>
#include <boost/format.hpp>
#include <model_core/register_block.h>
#include <shared/bitvector.h>












namespace tofinoB0 {
  namespace register_classes {

class WacDropCntPreFifoMutable : public model_core::RegisterBlock<RegisterCallback> {
public:
  enum WacCommonBlockEnum {
    kWacCommonWacDropCntPre0Fifo,
    kWacCommonWacDropCntPre1Fifo,
    kWacCommonWacDropCntPre2Fifo,
    kWacCommonWacDropCntPre3Fifo
  };
public:
  WacDropCntPreFifoMutable(
      int chipNumber, WacCommonBlockEnum selector_wac_common_block, int index_wac_drop_cnt_pre_fifo, RegisterCallback& write_callback = 0, RegisterCallback& read_callback = 0
  )
    : RegisterBlock(chipNumber, StartOffset(selector_wac_common_block, index_wac_drop_cnt_pre_fifo), 8, true, write_callback, read_callback, std::string("WacDropCntPreFifoMutable")+":"+boost::lexical_cast<std::string>(selector_wac_common_block) + "," + boost::lexical_cast<std::string>(index_wac_drop_cnt_pre_fifo))
    {
    }
  WacDropCntPreFifoMutable(
      
  )
    : RegisterBlock(0, 0, 0, true, 0, 0, "WacDropCntPreFifoMutable")
    {
    }
public:





  uint64_t cnt() { return cnt_; }
  void cnt(const uint64_t &v) { cnt_=v; }

  bool read(
      uint32_t offset, uint32_t* data
      ) const {
    if (offset < 0x4) {
      if (read_callback_) read_callback_();
      *data = (cnt_ & 0xffffffff);
    }
    else if (offset >= 0x4 && offset < 0x8) {
      if (read_callback_) read_callback_();
      *data = ((cnt_ & UINT64_C(0xff00000000)) >> 32);
    }
    else {
      assert(0);
    }
    return true;
  }


  bool write(
      uint32_t offset, uint32_t data
      ) {
    if (offset < 0x4) {
      cnt_ = ((static_cast<uint64_t>(data) & 0xffffffff) | (cnt_ & UINT64_C(0xff00000000)));
      if (write_callback_) write_callback_();
    }
    else if (offset >= 0x4 && offset < 0x8) {
      cnt_ = (((static_cast<uint64_t>(data) << 32) & UINT64_C(0xff00000000)) | (cnt_ & 0xffffffff));
      if (write_callback_) write_callback_();
    }
    else {
      assert(0);
    }
    return true;
  }

  void reset(
      
      ) {
    cnt_ = UINT64_C(0x0);
    if (write_callback_) write_callback_();
  }

  std::string to_string(
      uint32_t offset, bool print_zeros = false, std::string indent_string = ""
      ) const {
    std::string r("");
    bool all_zeros=true;
    r += indent_string + std::string("WacDropCntPreFifoMutable") + ":\n";
    r += indent_string + "  " + std::string("cnt") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(cnt_) ) + "\n";
    all_zeros &= (0 == cnt_);
    if (all_zeros && !print_zeros) {
      return("");
    }
    else {
      return r;
    }
  }

  std::string to_string(
      bool print_zeros = false, std::string indent_string = ""
      ) const {
    std::string r("");
    bool all_zeros=true;
    r += indent_string + std::string("WacDropCntPreFifoMutable") + ":\n";
    r += indent_string + "  " + std::string("cnt") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(cnt_) ) + "\n";
    all_zeros &= (0 == cnt_);
    if (all_zeros && !print_zeros) {
      return("");
    }
    else {
      return r;
    }
  }

private:
  uint64_t cnt_;
private:
  static int StartOffset(
      WacCommonBlockEnum selector_wac_common_block, int index_wac_drop_cnt_pre_fifo
      ) {
    int offset=0;
    offset += 0x400000; // to get to tm_top
    offset += 0x20000; // to get to wac_common
    switch (selector_wac_common_block) {
      case kWacCommonWacDropCntPre0Fifo:
        offset += 0x140; // to get to wac_common_wac_drop_cnt_pre0_fifo
        assert(index_wac_drop_cnt_pre_fifo < 4);
        offset += index_wac_drop_cnt_pre_fifo * 0x8; // wac_drop_cnt_pre_fifo[]
        break;
      case kWacCommonWacDropCntPre1Fifo:
        offset += 0x160; // to get to wac_common_wac_drop_cnt_pre1_fifo
        assert(index_wac_drop_cnt_pre_fifo < 4);
        offset += index_wac_drop_cnt_pre_fifo * 0x8; // wac_drop_cnt_pre_fifo[]
        break;
      case kWacCommonWacDropCntPre2Fifo:
        offset += 0x180; // to get to wac_common_wac_drop_cnt_pre2_fifo
        assert(index_wac_drop_cnt_pre_fifo < 4);
        offset += index_wac_drop_cnt_pre_fifo * 0x8; // wac_drop_cnt_pre_fifo[]
        break;
      case kWacCommonWacDropCntPre3Fifo:
        offset += 0x1a0; // to get to wac_common_wac_drop_cnt_pre3_fifo
        assert(index_wac_drop_cnt_pre_fifo < 4);
        offset += index_wac_drop_cnt_pre_fifo * 0x8; // wac_drop_cnt_pre_fifo[]
        break;
      default:
        assert(0);
        break;
    }
    return offset;
  }

};









  }; // namespace register_classes
}; // namespace tofinoB0

#endif // __REGISTER_INCLUDES_WAC_DROP_CNT_PRE_FIFO_MUTABLE_H__
