/*******************************************************************************
 *  Copyright (C) 2024 Intel Corporation
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions
 *  and limitations under the License.
 *
 *
 *  SPDX-License-Identifier: Apache-2.0
 ******************************************************************************/

// generated by split_classes.pl
#ifndef __REGISTER_INCLUDES_DPRSR_OUT_EGR_INTR_0_H__
#define __REGISTER_INCLUDES_DPRSR_OUT_EGR_INTR_0_H__


#include <cstdint>
#include <cassert>
#include <array>
#include <vector>
#include <string>
#include <boost/lexical_cast.hpp>
#include <boost/format.hpp>
#include <model_core/register_block.h>
#include <shared/bitvector.h>









#include "dprsr_out_egr_intr_0_en0.h"
#include "dprsr_out_egr_intr_0_en1.h"
#include "dprsr_out_egr_intr_0_freeze_enable.h"
#include "dprsr_out_egr_intr_0_inj.h"
#include "dprsr_out_egr_intr_0_stat.h"

namespace jbayB0 {
  namespace register_classes {

class DprsrOutEgrIntr_0 : public model_core::RegisterBlock<RegisterCallback> {
public:
  DprsrOutEgrIntr_0(
      int chipNumber, int index_pipe_addrmap, int index_dprsr_ho_e, RegisterCallback& write_callback = 0, RegisterCallback& read_callback = 0
  )
    : RegisterBlock(chipNumber, StartOffset(index_pipe_addrmap, index_dprsr_ho_e), 20, false, write_callback, read_callback, std::string("DprsrOutEgrIntr_0")+":"+boost::lexical_cast<std::string>(index_pipe_addrmap) + "," + boost::lexical_cast<std::string>(index_dprsr_ho_e))
    {
    }
  DprsrOutEgrIntr_0(
      
  )
    : RegisterBlock(0, 0, 0, false, 0, 0, "DprsrOutEgrIntr_0")
    {
    }
public:






  DprsrOutEgrIntr_0Stat &intr_0_stat() { return intr_0_stat_; }







  DprsrOutEgrIntr_0En0 &intr_0_en0() { return intr_0_en0_; }







  DprsrOutEgrIntr_0En1 &intr_0_en1() { return intr_0_en1_; }








  DprsrOutEgrIntr_0Inj &intr_0_inj() { return intr_0_inj_; }





  DprsrOutEgrIntr_0FreezeEnable &intr_0_freeze_enable() { return intr_0_freeze_enable_; }

  bool read(
      uint32_t offset, uint32_t* data
      ) const {
    if (offset >= 0x3a0 && offset < 0x3a4) {
      offset -= 0x3a0;
      if (read_callback_) read_callback_();
      intr_0_stat_.read( offset, data );
    }
    else if (offset >= 0x3a4 && offset < 0x3a8) {
      offset -= 0x3a4;
      if (read_callback_) read_callback_();
      intr_0_en0_.read( offset, data );
    }
    else if (offset >= 0x3a8 && offset < 0x3ac) {
      offset -= 0x3a8;
      if (read_callback_) read_callback_();
      intr_0_en1_.read( offset, data );
    }
    else if (offset >= 0x3ac && offset < 0x3b0) {
      offset -= 0x3ac;
      if (read_callback_) read_callback_();
      intr_0_inj_.read( offset, data );
    }
    else if (offset >= 0x3b0 && offset < 0x3b4) {
      offset -= 0x3b0;
      if (read_callback_) read_callback_();
      intr_0_freeze_enable_.read( offset, data );
    }
    return true;
  }


  bool write(
      uint32_t offset, uint32_t data
      ) {
    if (offset >= 0x3a0 && offset < 0x3a4) {
      offset -= 0x3a0;
      intr_0_stat_.write( offset, data );
      if (write_callback_) write_callback_();
    }
    else if (offset >= 0x3a4 && offset < 0x3a8) {
      offset -= 0x3a4;
      intr_0_en0_.write( offset, data );
      if (write_callback_) write_callback_();
    }
    else if (offset >= 0x3a8 && offset < 0x3ac) {
      offset -= 0x3a8;
      intr_0_en1_.write( offset, data );
      if (write_callback_) write_callback_();
    }
    else if (offset >= 0x3ac && offset < 0x3b0) {
      offset -= 0x3ac;
      intr_0_inj_.write( offset, data );
      if (write_callback_) write_callback_();
    }
    else if (offset >= 0x3b0 && offset < 0x3b4) {
      offset -= 0x3b0;
      intr_0_freeze_enable_.write( offset, data );
      if (write_callback_) write_callback_();
    }
    return true;
  }

  void reset(
      
      ) {
    intr_0_stat_.reset();
    intr_0_en0_.reset();
    intr_0_en1_.reset();
    intr_0_inj_.reset();
    intr_0_freeze_enable_.reset();
    if (write_callback_) write_callback_();
  }

  std::string to_string(
      uint32_t offset, bool print_zeros = false, std::string indent_string = ""
      ) const {
    std::string r("");
    bool all_zeros=true;
    all_zeros=false;
    if (offset >= 0x3a0 && offset < 0x3a4) {
      offset -= 0x3a0;
      r += intr_0_stat_.to_string(offset,print_zeros,indent_string) ;
    }
    else if (offset >= 0x3a4 && offset < 0x3a8) {
      offset -= 0x3a4;
      r += intr_0_en0_.to_string(offset,print_zeros,indent_string) ;
    }
    else if (offset >= 0x3a8 && offset < 0x3ac) {
      offset -= 0x3a8;
      r += intr_0_en1_.to_string(offset,print_zeros,indent_string) ;
    }
    else if (offset >= 0x3ac && offset < 0x3b0) {
      offset -= 0x3ac;
      r += intr_0_inj_.to_string(offset,print_zeros,indent_string) ;
    }
    else if (offset >= 0x3b0 && offset < 0x3b4) {
      offset -= 0x3b0;
      r += intr_0_freeze_enable_.to_string(offset,print_zeros,indent_string) ;
    }
    if (all_zeros && !print_zeros) {
      return("");
    }
    else {
      return r;
    }
  }

  std::string to_string(
      bool print_zeros = false, std::string indent_string = ""
      ) const {
    std::string r("");
    bool all_zeros=true;
    all_zeros=false;
    r += intr_0_stat_.to_string(print_zeros,indent_string) ;
    r += intr_0_en0_.to_string(print_zeros,indent_string) ;
    r += intr_0_en1_.to_string(print_zeros,indent_string) ;
    r += intr_0_inj_.to_string(print_zeros,indent_string) ;
    r += intr_0_freeze_enable_.to_string(print_zeros,indent_string) ;
    if (all_zeros && !print_zeros) {
      return("");
    }
    else {
      return r;
    }
  }

private:
  DprsrOutEgrIntr_0Stat intr_0_stat_;
  DprsrOutEgrIntr_0En0 intr_0_en0_;
  DprsrOutEgrIntr_0En1 intr_0_en1_;
  DprsrOutEgrIntr_0Inj intr_0_inj_;
  DprsrOutEgrIntr_0FreezeEnable intr_0_freeze_enable_;
private:
  static int StartOffset(
      int index_pipe_addrmap, int index_dprsr_ho_e
      ) {
    int offset=0;
    offset += 0x4000000; // to get to pipes
    assert(index_pipe_addrmap < 4);
    offset += index_pipe_addrmap * 0x1000000; // pipe_addrmap[]
    offset += 0xc00000; // to get to pardereg
    offset += 0x100000; // to get to dprsrreg
    offset += 0x38000; // to get to ho_e
    assert(index_dprsr_ho_e < 4);
    offset += index_dprsr_ho_e * 0x2000; // dprsr_ho_e[]
    offset += 0x1000; // to get to out_egr
    return offset;
  }

};





  }; // namespace register_classes
}; // namespace jbayB0

#endif // __REGISTER_INCLUDES_DPRSR_OUT_EGR_INTR_0_H__
