/*******************************************************************************
 *  Copyright (C) 2024 Intel Corporation
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions
 *  and limitations under the License.
 *
 *
 *  SPDX-License-Identifier: Apache-2.0
 ******************************************************************************/

// generated by split_classes.pl
#ifndef __REGISTER_INCLUDES_DPRSR_HO_I_H__
#define __REGISTER_INCLUDES_DPRSR_HO_I_H__


#include <cstdint>
#include <cassert>
#include <array>
#include <vector>
#include <string>
#include <boost/lexical_cast.hpp>
#include <boost/format.hpp>
#include <model_core/register_block.h>
#include <shared/bitvector.h>









#include "dprsr_hi_mem.h"
#include "dprsr_hi_regs.h"
#include "dprsr_out_ingr.h"

namespace jbayB0 {
  namespace register_classes {

class DprsrHoI : public model_core::RegisterBlock<RegisterCallback> {
public:
  DprsrHoI(
      int chipNumber, int index_pipe_addrmap, int index_dprsr_ho_i, RegisterCallback& write_callback = 0, RegisterCallback& read_callback = 0
  )
    : RegisterBlock(chipNumber, StartOffset(index_pipe_addrmap, index_dprsr_ho_i), 8192, false, write_callback, read_callback, std::string("DprsrHoI")+":"+boost::lexical_cast<std::string>(index_pipe_addrmap) + "," + boost::lexical_cast<std::string>(index_dprsr_ho_i))
    {
    }
  DprsrHoI(
      
  )
    : RegisterBlock(0, 0, 0, false, 0, 0, "DprsrHoI")
    {
    }
public:
  DprsrHiMem &him() { return him_; }





  DprsrHiRegs &hir() { return hir_; }





  DprsrOutIngr &out_ingr() { return out_ingr_; }

  bool read(
      uint32_t offset, uint32_t* data
      ) const {
    if (offset < 0xc00) {
      offset -= 0x0;
      if (read_callback_) read_callback_();
      him_.read( offset, data );
    }
    else if (offset >= 0xc00 && offset < 0x1000) {
      offset -= 0xc00;
      if (read_callback_) read_callback_();
      hir_.read( offset, data );
    }
    else if (offset >= 0x1000 && offset < 0x2000) {
      offset -= 0x1000;
      if (read_callback_) read_callback_();
      out_ingr_.read( offset, data );
    }
    return true;
  }


  bool write(
      uint32_t offset, uint32_t data
      ) {
    if (offset < 0xc00) {
      offset -= 0x0;
      him_.write( offset, data );
      if (write_callback_) write_callback_();
    }
    else if (offset >= 0xc00 && offset < 0x1000) {
      offset -= 0xc00;
      hir_.write( offset, data );
      if (write_callback_) write_callback_();
    }
    else if (offset >= 0x1000 && offset < 0x2000) {
      offset -= 0x1000;
      out_ingr_.write( offset, data );
      if (write_callback_) write_callback_();
    }
    return true;
  }

  void reset(
      
      ) {
    him_.reset();
    hir_.reset();
    out_ingr_.reset();
    if (write_callback_) write_callback_();
  }

  std::string to_string(
      uint32_t offset, bool print_zeros = false, std::string indent_string = ""
      ) const {
    std::string r("");
    bool all_zeros=true;
    all_zeros=false;
    if (offset < 0xc00) {
      offset -= 0x0;
      r += him_.to_string(offset,print_zeros,indent_string) ;
    }
    else if (offset >= 0xc00 && offset < 0x1000) {
      offset -= 0xc00;
      r += hir_.to_string(offset,print_zeros,indent_string) ;
    }
    else if (offset >= 0x1000 && offset < 0x2000) {
      offset -= 0x1000;
      r += out_ingr_.to_string(offset,print_zeros,indent_string) ;
    }
    if (all_zeros && !print_zeros) {
      return("");
    }
    else {
      return r;
    }
  }

  std::string to_string(
      bool print_zeros = false, std::string indent_string = ""
      ) const {
    std::string r("");
    bool all_zeros=true;
    all_zeros=false;
    r += him_.to_string(print_zeros,indent_string) ;
    r += hir_.to_string(print_zeros,indent_string) ;
    r += out_ingr_.to_string(print_zeros,indent_string) ;
    if (all_zeros && !print_zeros) {
      return("");
    }
    else {
      return r;
    }
  }

private:
  DprsrHiMem him_;
  DprsrHiRegs hir_;
  DprsrOutIngr out_ingr_;
private:
  static int StartOffset(
      int index_pipe_addrmap, int index_dprsr_ho_i
      ) {
    int offset=0;
    offset += 0x4000000; // to get to pipes
    assert(index_pipe_addrmap < 4);
    offset += index_pipe_addrmap * 0x1000000; // pipe_addrmap[]
    offset += 0xc00000; // to get to pardereg
    offset += 0x100000; // to get to dprsrreg
    offset += 0x30000; // to get to ho_i
    assert(index_dprsr_ho_i < 4);
    offset += index_dprsr_ho_i * 0x2000; // dprsr_ho_i[]
    return offset;
  }

};









  }; // namespace register_classes
}; // namespace jbayB0

#endif // __REGISTER_INCLUDES_DPRSR_HO_I_H__
