/*******************************************************************************
 *  Copyright (C) 2024 Intel Corporation
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions
 *  and limitations under the License.
 *
 *
 *  SPDX-License-Identifier: Apache-2.0
 ******************************************************************************/

// generated by split_classes.pl
#ifndef __REGISTER_INCLUDES_EPB_RSPEC_CHAN7_GROUP_H__
#define __REGISTER_INCLUDES_EPB_RSPEC_CHAN7_GROUP_H__


#include <cstdint>
#include <cassert>
#include <array>
#include <vector>
#include <string>
#include <boost/lexical_cast.hpp>
#include <boost/format.hpp>
#include <model_core/register_block.h>
#include <shared/bitvector.h>









#include "epb_chnl_ctrl.h"
#include "epb_chnl_deparser_send_pkt.h"
#include "epb_chnl_fifo_cfg.h"
#include "epb_chnl_fifo_ctrl.h"
#include "epb_chnl_p2s_received_pkt.h"
#include "epb_chnl_parser_send_pkt.h"
#include "epb_chnl_pktnum0.h"
#include "epb_chnl_pktnum1.h"
#include "epb_chnl_pktnum2.h"
#include "epb_chnl_pktnum3.h"
#include "epb_chnl_stat.h"
#include "epb_chnl_warp_send_pkt.h"

namespace jbayB0 {
  namespace register_classes {

class EpbRspecChan7Group : public model_core::RegisterBlock<RegisterCallback> {
public:
  EpbRspecChan7Group(
      int chipNumber, int index_pipe_addrmap, int index_epb_prsr4_reg, RegisterCallback& write_callback = 0, RegisterCallback& read_callback = 0
  )
    : RegisterBlock(chipNumber, StartOffset(index_pipe_addrmap, index_epb_prsr4_reg), 108, false, write_callback, read_callback, std::string("EpbRspecChan7Group")+":"+boost::lexical_cast<std::string>(index_pipe_addrmap) + "," + boost::lexical_cast<std::string>(index_epb_prsr4_reg))
    {
    }
  EpbRspecChan7Group(
      
  )
    : RegisterBlock(0, 0, 0, false, 0, 0, "EpbRspecChan7Group")
    {
    }
public:





  EpbChnlCtrl &chan7_group_chnl_ctrl() { return chan7_group_chnl_ctrl_; }





  EpbChnlFifoCtrl &chan7_group_chnl_fifo_ctrl() { return chan7_group_chnl_fifo_ctrl_; }







  EpbChnlFifoCfg &chan7_group_chnl_fifo_cfg() { return chan7_group_chnl_fifo_cfg_; }






  EpbChnlStat &chan7_group_chnl_stat() { return chan7_group_chnl_stat_; }







  EpbChnlPktnum0 &chan7_group_chnl_pktnum0() { return chan7_group_chnl_pktnum0_; }






  EpbChnlPktnum1 &chan7_group_chnl_pktnum1() { return chan7_group_chnl_pktnum1_; }






  EpbChnlPktnum2 &chan7_group_chnl_pktnum2() { return chan7_group_chnl_pktnum2_; }






  EpbChnlPktnum3 &chan7_group_chnl_pktnum3() { return chan7_group_chnl_pktnum3_; }





  EpbChnlParserSendPkt &chan7_group_chnl_parser_send_pkt() { return chan7_group_chnl_parser_send_pkt_; }





  EpbChnlDeparserSendPkt &chan7_group_chnl_deparser_send_pkt() { return chan7_group_chnl_deparser_send_pkt_; }





  EpbChnlWarpSendPkt &chan7_group_chnl_warp_send_pkt() { return chan7_group_chnl_warp_send_pkt_; }





  EpbChnlP2sReceivedPkt &chan7_group_chnl_p2s_received_pkt() { return chan7_group_chnl_p2s_received_pkt_; }

  bool read(
      uint32_t offset, uint32_t* data
      ) const {
    if (offset >= 0xf00 && offset < 0xf08) {
      offset -= 0xf00;
      if (read_callback_) read_callback_();
      chan7_group_chnl_ctrl_.read( offset, data );
    }
    else if (offset >= 0xf08 && offset < 0xf10) {
      offset -= 0xf08;
      if (read_callback_) read_callback_();
      chan7_group_chnl_fifo_ctrl_.read( offset, data );
    }
    else if (offset >= 0xf10 && offset < 0xf14) {
      offset -= 0xf10;
      if (read_callback_) read_callback_();
      chan7_group_chnl_fifo_cfg_.read( offset, data );
    }
    else if (offset >= 0xf14 && offset < 0xf18) {
      offset -= 0xf14;
      if (read_callback_) read_callback_();
      chan7_group_chnl_stat_.read( offset, data );
    }
    else if (offset >= 0xf18 && offset < 0xf1c) {
      offset -= 0xf18;
      if (read_callback_) read_callback_();
      chan7_group_chnl_pktnum0_.read( offset, data );
    }
    else if (offset >= 0xf1c && offset < 0xf20) {
      offset -= 0xf1c;
      if (read_callback_) read_callback_();
      chan7_group_chnl_pktnum1_.read( offset, data );
    }
    else if (offset >= 0xf20 && offset < 0xf24) {
      offset -= 0xf20;
      if (read_callback_) read_callback_();
      chan7_group_chnl_pktnum2_.read( offset, data );
    }
    else if (offset >= 0xf28 && offset < 0xf30) {
      offset -= 0xf28;
      if (read_callback_) read_callback_();
      chan7_group_chnl_pktnum3_.read( offset, data );
    }
    else if (offset >= 0xf30 && offset < 0xf3c) {
      offset -= 0xf30;
      if (read_callback_) read_callback_();
      chan7_group_chnl_parser_send_pkt_.read( offset, data );
    }
    else if (offset >= 0xf40 && offset < 0xf4c) {
      offset -= 0xf40;
      if (read_callback_) read_callback_();
      chan7_group_chnl_deparser_send_pkt_.read( offset, data );
    }
    else if (offset >= 0xf50 && offset < 0xf5c) {
      offset -= 0xf50;
      if (read_callback_) read_callback_();
      chan7_group_chnl_warp_send_pkt_.read( offset, data );
    }
    else if (offset >= 0xf60 && offset < 0xf6c) {
      offset -= 0xf60;
      if (read_callback_) read_callback_();
      chan7_group_chnl_p2s_received_pkt_.read( offset, data );
    }
    return true;
  }


  bool write(
      uint32_t offset, uint32_t data
      ) {
    if (offset >= 0xf00 && offset < 0xf08) {
      offset -= 0xf00;
      chan7_group_chnl_ctrl_.write( offset, data );
      if (write_callback_) write_callback_();
    }
    else if (offset >= 0xf08 && offset < 0xf10) {
      offset -= 0xf08;
      chan7_group_chnl_fifo_ctrl_.write( offset, data );
      if (write_callback_) write_callback_();
    }
    else if (offset >= 0xf10 && offset < 0xf14) {
      offset -= 0xf10;
      chan7_group_chnl_fifo_cfg_.write( offset, data );
      if (write_callback_) write_callback_();
    }
    else if (offset >= 0xf14 && offset < 0xf18) {
      offset -= 0xf14;
      chan7_group_chnl_stat_.write( offset, data );
      if (write_callback_) write_callback_();
    }
    else if (offset >= 0xf18 && offset < 0xf1c) {
      offset -= 0xf18;
      chan7_group_chnl_pktnum0_.write( offset, data );
      if (write_callback_) write_callback_();
    }
    else if (offset >= 0xf1c && offset < 0xf20) {
      offset -= 0xf1c;
      chan7_group_chnl_pktnum1_.write( offset, data );
      if (write_callback_) write_callback_();
    }
    else if (offset >= 0xf20 && offset < 0xf24) {
      offset -= 0xf20;
      chan7_group_chnl_pktnum2_.write( offset, data );
      if (write_callback_) write_callback_();
    }
    else if (offset >= 0xf28 && offset < 0xf30) {
      offset -= 0xf28;
      chan7_group_chnl_pktnum3_.write( offset, data );
      if (write_callback_) write_callback_();
    }
    else if (offset >= 0xf30 && offset < 0xf3c) {
      offset -= 0xf30;
      chan7_group_chnl_parser_send_pkt_.write( offset, data );
      if (write_callback_) write_callback_();
    }
    else if (offset >= 0xf40 && offset < 0xf4c) {
      offset -= 0xf40;
      chan7_group_chnl_deparser_send_pkt_.write( offset, data );
      if (write_callback_) write_callback_();
    }
    else if (offset >= 0xf50 && offset < 0xf5c) {
      offset -= 0xf50;
      chan7_group_chnl_warp_send_pkt_.write( offset, data );
      if (write_callback_) write_callback_();
    }
    else if (offset >= 0xf60 && offset < 0xf6c) {
      offset -= 0xf60;
      chan7_group_chnl_p2s_received_pkt_.write( offset, data );
      if (write_callback_) write_callback_();
    }
    return true;
  }

  void reset(
      
      ) {
    chan7_group_chnl_ctrl_.reset();
    chan7_group_chnl_fifo_ctrl_.reset();
    chan7_group_chnl_fifo_cfg_.reset();
    chan7_group_chnl_stat_.reset();
    chan7_group_chnl_pktnum0_.reset();
    chan7_group_chnl_pktnum1_.reset();
    chan7_group_chnl_pktnum2_.reset();
    chan7_group_chnl_pktnum3_.reset();
    chan7_group_chnl_parser_send_pkt_.reset();
    chan7_group_chnl_deparser_send_pkt_.reset();
    chan7_group_chnl_warp_send_pkt_.reset();
    chan7_group_chnl_p2s_received_pkt_.reset();
    if (write_callback_) write_callback_();
  }

  std::string to_string(
      uint32_t offset, bool print_zeros = false, std::string indent_string = ""
      ) const {
    std::string r("");
    bool all_zeros=true;
    all_zeros=false;
    if (offset >= 0xf00 && offset < 0xf08) {
      offset -= 0xf00;
      r += chan7_group_chnl_ctrl_.to_string(offset,print_zeros,indent_string) ;
    }
    else if (offset >= 0xf08 && offset < 0xf10) {
      offset -= 0xf08;
      r += chan7_group_chnl_fifo_ctrl_.to_string(offset,print_zeros,indent_string) ;
    }
    else if (offset >= 0xf10 && offset < 0xf14) {
      offset -= 0xf10;
      r += chan7_group_chnl_fifo_cfg_.to_string(offset,print_zeros,indent_string) ;
    }
    else if (offset >= 0xf14 && offset < 0xf18) {
      offset -= 0xf14;
      r += chan7_group_chnl_stat_.to_string(offset,print_zeros,indent_string) ;
    }
    else if (offset >= 0xf18 && offset < 0xf1c) {
      offset -= 0xf18;
      r += chan7_group_chnl_pktnum0_.to_string(offset,print_zeros,indent_string) ;
    }
    else if (offset >= 0xf1c && offset < 0xf20) {
      offset -= 0xf1c;
      r += chan7_group_chnl_pktnum1_.to_string(offset,print_zeros,indent_string) ;
    }
    else if (offset >= 0xf20 && offset < 0xf24) {
      offset -= 0xf20;
      r += chan7_group_chnl_pktnum2_.to_string(offset,print_zeros,indent_string) ;
    }
    else if (offset >= 0xf28 && offset < 0xf30) {
      offset -= 0xf28;
      r += chan7_group_chnl_pktnum3_.to_string(offset,print_zeros,indent_string) ;
    }
    else if (offset >= 0xf30 && offset < 0xf3c) {
      offset -= 0xf30;
      r += chan7_group_chnl_parser_send_pkt_.to_string(offset,print_zeros,indent_string) ;
    }
    else if (offset >= 0xf40 && offset < 0xf4c) {
      offset -= 0xf40;
      r += chan7_group_chnl_deparser_send_pkt_.to_string(offset,print_zeros,indent_string) ;
    }
    else if (offset >= 0xf50 && offset < 0xf5c) {
      offset -= 0xf50;
      r += chan7_group_chnl_warp_send_pkt_.to_string(offset,print_zeros,indent_string) ;
    }
    else if (offset >= 0xf60 && offset < 0xf6c) {
      offset -= 0xf60;
      r += chan7_group_chnl_p2s_received_pkt_.to_string(offset,print_zeros,indent_string) ;
    }
    if (all_zeros && !print_zeros) {
      return("");
    }
    else {
      return r;
    }
  }

  std::string to_string(
      bool print_zeros = false, std::string indent_string = ""
      ) const {
    std::string r("");
    bool all_zeros=true;
    all_zeros=false;
    r += chan7_group_chnl_ctrl_.to_string(print_zeros,indent_string) ;
    r += chan7_group_chnl_fifo_ctrl_.to_string(print_zeros,indent_string) ;
    r += chan7_group_chnl_fifo_cfg_.to_string(print_zeros,indent_string) ;
    r += chan7_group_chnl_stat_.to_string(print_zeros,indent_string) ;
    r += chan7_group_chnl_pktnum0_.to_string(print_zeros,indent_string) ;
    r += chan7_group_chnl_pktnum1_.to_string(print_zeros,indent_string) ;
    r += chan7_group_chnl_pktnum2_.to_string(print_zeros,indent_string) ;
    r += chan7_group_chnl_pktnum3_.to_string(print_zeros,indent_string) ;
    r += chan7_group_chnl_parser_send_pkt_.to_string(print_zeros,indent_string) ;
    r += chan7_group_chnl_deparser_send_pkt_.to_string(print_zeros,indent_string) ;
    r += chan7_group_chnl_warp_send_pkt_.to_string(print_zeros,indent_string) ;
    r += chan7_group_chnl_p2s_received_pkt_.to_string(print_zeros,indent_string) ;
    if (all_zeros && !print_zeros) {
      return("");
    }
    else {
      return r;
    }
  }

private:
  EpbChnlCtrl chan7_group_chnl_ctrl_;
  EpbChnlFifoCtrl chan7_group_chnl_fifo_ctrl_;
  EpbChnlFifoCfg chan7_group_chnl_fifo_cfg_;
  EpbChnlStat chan7_group_chnl_stat_;
  EpbChnlPktnum0 chan7_group_chnl_pktnum0_;
  EpbChnlPktnum1 chan7_group_chnl_pktnum1_;
  EpbChnlPktnum2 chan7_group_chnl_pktnum2_;
  EpbChnlPktnum3 chan7_group_chnl_pktnum3_;
  EpbChnlParserSendPkt chan7_group_chnl_parser_send_pkt_;
  EpbChnlDeparserSendPkt chan7_group_chnl_deparser_send_pkt_;
  EpbChnlWarpSendPkt chan7_group_chnl_warp_send_pkt_;
  EpbChnlP2sReceivedPkt chan7_group_chnl_p2s_received_pkt_;
private:
  static int StartOffset(
      int index_pipe_addrmap, int index_epb_prsr4_reg
      ) {
    int offset=0;
    offset += 0x4000000; // to get to pipes
    assert(index_pipe_addrmap < 4);
    offset += index_pipe_addrmap * 0x1000000; // pipe_addrmap[]
    offset += 0xc00000; // to get to pardereg
    offset += 0x20000; // to get to epbprsr4reg
    assert(index_epb_prsr4_reg < 9);
    offset += index_epb_prsr4_reg * 0x2000; // epb_prsr4_reg[]
    return offset;
  }

};









  }; // namespace register_classes
}; // namespace jbayB0

#endif // __REGISTER_INCLUDES_EPB_RSPEC_CHAN7_GROUP_H__
