/*******************************************************************************
 *  Copyright (C) 2024 Intel Corporation
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions
 *  and limitations under the License.
 *
 *
 *  SPDX-License-Identifier: Apache-2.0
 ******************************************************************************/

// generated by split_classes.pl
#ifndef __REGISTER_INCLUDES_IMEM_SUBWORD16_H__
#define __REGISTER_INCLUDES_IMEM_SUBWORD16_H__


#include <cstdint>
#include <cassert>
#include <array>
#include <vector>
#include <string>
#include <boost/lexical_cast.hpp>
#include <boost/format.hpp>
#include <model_core/register_block.h>
#include <shared/bitvector.h>










namespace jbayB0 {
  namespace register_classes {

class ImemSubword16 : public model_core::RegisterBlock<RegisterCallback> {
public:
  ImemSubword16(
      int chipNumber, int index_pipe_addrmap, int index_mau_addrmap, int index_imem_subword16_0, int index_imem_subword16_1, int index_imem_subword16_2, int index_imem_subword16_3, RegisterCallback& write_callback = 0, RegisterCallback& read_callback = 0
  )
    : RegisterBlock(chipNumber, StartOffset(index_pipe_addrmap, index_mau_addrmap, index_imem_subword16_0, index_imem_subword16_1, index_imem_subword16_2, index_imem_subword16_3), 4, false, write_callback, read_callback, std::string("ImemSubword16")+":"+boost::lexical_cast<std::string>(index_pipe_addrmap) + "," + boost::lexical_cast<std::string>(index_mau_addrmap) + "," + boost::lexical_cast<std::string>(index_imem_subword16_0) + "," + boost::lexical_cast<std::string>(index_imem_subword16_1) + "," + boost::lexical_cast<std::string>(index_imem_subword16_2) + "," + boost::lexical_cast<std::string>(index_imem_subword16_3))
    {
    }
  ImemSubword16(
      
  )
    : RegisterBlock(0, 0, 0, false, 0, 0, "ImemSubword16")
    {
    }
public:


  uint32_t &imem_subword16_instr() { return imem_subword16_instr_; }


  uint8_t &imem_subword16_color() { return imem_subword16_color_; }



  uint8_t &imem_subword16_parity() { return imem_subword16_parity_; }

  bool read(
      uint32_t offset, uint32_t* data
      ) const {
    if (read_callback_) read_callback_();
    *data = (imem_subword16_instr_ & 0xffffff);
    *data |= ((imem_subword16_color_ & 0x1) << 24);
    *data |= ((imem_subword16_parity_ & 0x1) << 25);
    return true;
  }


  bool write(
      uint32_t offset, uint32_t data
      ) {
    imem_subword16_instr_ = (data & 0xffffff);
    imem_subword16_color_ = ((data >> 24) & 0x1);
    imem_subword16_parity_ = ((data >> 25) & 0x1);
    if (write_callback_) write_callback_();
    return true;
  }

  void reset(
      
      ) {
    imem_subword16_instr_ = 0x0;
    imem_subword16_color_ = 0x0;
    imem_subword16_parity_ = 0x0;
    if (write_callback_) write_callback_();
  }

  std::string to_string(
      uint32_t offset, bool print_zeros = false, std::string indent_string = ""
      ) const {
    std::string r("");
    bool all_zeros=true;
    r += indent_string + std::string("ImemSubword16") + ":\n";
    r += indent_string + "  " + std::string("imem_subword16_instr") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(imem_subword16_instr_) ) + "\n";
    all_zeros &= (0 == imem_subword16_instr_);
    r += indent_string + "  " + std::string("imem_subword16_color") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(imem_subword16_color_) ) + "\n";
    all_zeros &= (0 == imem_subword16_color_);
    r += indent_string + "  " + std::string("imem_subword16_parity") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(imem_subword16_parity_) ) + "\n";
    all_zeros &= (0 == imem_subword16_parity_);
    if (all_zeros && !print_zeros) {
      return("");
    }
    else {
      return r;
    }
  }

  std::string to_string(
      bool print_zeros = false, std::string indent_string = ""
      ) const {
    std::string r("");
    bool all_zeros=true;
    r += indent_string + std::string("ImemSubword16") + ":\n";
    r += indent_string + "  " + std::string("imem_subword16_instr") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(imem_subword16_instr_) ) + "\n";
    all_zeros &= (0 == imem_subword16_instr_);
    r += indent_string + "  " + std::string("imem_subword16_color") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(imem_subword16_color_) ) + "\n";
    all_zeros &= (0 == imem_subword16_color_);
    r += indent_string + "  " + std::string("imem_subword16_parity") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(imem_subword16_parity_) ) + "\n";
    all_zeros &= (0 == imem_subword16_parity_);
    if (all_zeros && !print_zeros) {
      return("");
    }
    else {
      return r;
    }
  }

private:
  uint32_t imem_subword16_instr_;
  uint8_t imem_subword16_color_;
  uint8_t imem_subword16_parity_;
private:
  static int StartOffset(
      int index_pipe_addrmap, int index_mau_addrmap, int index_imem_subword16_0, int index_imem_subword16_1, int index_imem_subword16_2, int index_imem_subword16_3
      ) {
    int offset=0;
    offset += 0x4000000; // to get to pipes
    assert(index_pipe_addrmap < 4);
    offset += index_pipe_addrmap * 0x1000000; // pipe_addrmap[]
    assert(index_mau_addrmap < 20);
    offset += index_mau_addrmap * 0x80000; // mau_addrmap[]
    offset += 0x8000; // to get to imem_subword16
    assert(index_imem_subword16_0 < 2);
    offset += index_imem_subword16_0 * 0x2000; // imem_subword16[]
    assert(index_imem_subword16_1 < 3);
    offset += index_imem_subword16_1 * 0x800; // imem_subword16[][]
    assert(index_imem_subword16_2 < 12);
    offset += index_imem_subword16_2 * 0x80; // imem_subword16[][][]
    assert(index_imem_subword16_3 < 32);
    offset += index_imem_subword16_3 * 0x4; // imem_subword16[][][][]
    return offset;
  }

};













  }; // namespace register_classes
}; // namespace jbayB0

#endif // __REGISTER_INCLUDES_IMEM_SUBWORD16_H__
