/*******************************************************************************
 *  Copyright (C) 2024 Intel Corporation
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions
 *  and limitations under the License.
 *
 *
 *  SPDX-License-Identifier: Apache-2.0
 ******************************************************************************/

// generated by split_classes.pl
#ifndef __REGISTER_INCLUDES_PRE_ARB_CTRL_MUTABLE_H__
#define __REGISTER_INCLUDES_PRE_ARB_CTRL_MUTABLE_H__


#include <cstdint>
#include <cassert>
#include <array>
#include <vector>
#include <string>
#include <boost/lexical_cast.hpp>
#include <boost/format.hpp>
#include <model_core/register_block.h>
#include <shared/bitvector.h>










namespace jbayB0 {
  namespace register_classes {

class PreArbCtrlMutable : public model_core::RegisterBlock<RegisterCallback> {
public:
  PreArbCtrlMutable(
      int chipNumber, int index_tm_pre_pipe_rspec, RegisterCallback& write_callback = 0, RegisterCallback& read_callback = 0
  )
    : RegisterBlock(chipNumber, StartOffset(index_tm_pre_pipe_rspec), 4, true, write_callback, read_callback, std::string("PreArbCtrlMutable")+":"+boost::lexical_cast<std::string>(index_tm_pre_pipe_rspec))
    {
    }
  PreArbCtrlMutable(
      
  )
    : RegisterBlock(0, 0, 0, true, 0, 0, "PreArbCtrlMutable")
    {
    }
public:






  uint8_t arbitration_mode() { return arbitration_mode_; }
  void arbitration_mode(const uint8_t &v) { arbitration_mode_=v; }

  bool read(
      uint32_t offset, uint32_t* data
      ) const {
    if (read_callback_) read_callback_();
    *data = (arbitration_mode_ & 0xf);
    return true;
  }


  bool write(
      uint32_t offset, uint32_t data
      ) {
    arbitration_mode_ = (data & 0xf);
    if (write_callback_) write_callback_();
    return true;
  }

  void reset(
      
      ) {
    arbitration_mode_ = 0x0;
    if (write_callback_) write_callback_();
  }

  std::string to_string(
      uint32_t offset, bool print_zeros = false, std::string indent_string = ""
      ) const {
    std::string r("");
    bool all_zeros=true;
    r += indent_string + std::string("PreArbCtrlMutable") + ":\n";
    r += indent_string + "  " + std::string("arbitration_mode") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(arbitration_mode_) ) + "\n";
    all_zeros &= (0 == arbitration_mode_);
    if (all_zeros && !print_zeros) {
      return("");
    }
    else {
      return r;
    }
  }

  std::string to_string(
      bool print_zeros = false, std::string indent_string = ""
      ) const {
    std::string r("");
    bool all_zeros=true;
    r += indent_string + std::string("PreArbCtrlMutable") + ":\n";
    r += indent_string + "  " + std::string("arbitration_mode") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(arbitration_mode_) ) + "\n";
    all_zeros &= (0 == arbitration_mode_);
    if (all_zeros && !print_zeros) {
      return("");
    }
    else {
      return r;
    }
  }

private:
  uint8_t arbitration_mode_;
private:
  static int StartOffset(
      int index_tm_pre_pipe_rspec
      ) {
    int offset=0;
    offset += 0x800000; // to get to tm_top
    offset += 0x480000; // to get to tm_pre_top
    assert(index_tm_pre_pipe_rspec < 4);
    offset += index_tm_pre_pipe_rspec * 0x8000; // tm_pre_pipe_rspec[]
    offset += 0x8; // to get to arb_ctrl
    return offset;
  }

};









  }; // namespace register_classes
}; // namespace jbayB0

#endif // __REGISTER_INCLUDES_PRE_ARB_CTRL_MUTABLE_H__
