/*******************************************************************************
 *  Copyright (C) 2024 Intel Corporation
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions
 *  and limitations under the License.
 *
 *
 *  SPDX-License-Identifier: Apache-2.0
 ******************************************************************************/

// generated by split_classes.pl
#ifndef __REGISTER_INCLUDES_PRED_MAP_GLOB_MUTABLE_H__
#define __REGISTER_INCLUDES_PRED_MAP_GLOB_MUTABLE_H__


#include <cstdint>
#include <cassert>
#include <array>
#include <vector>
#include <string>
#include <boost/lexical_cast.hpp>
#include <boost/format.hpp>
#include <model_core/register_block.h>
#include <shared/bitvector.h>










namespace jbayB0 {
  namespace register_classes {

class PredMapGlobMutable : public model_core::RegisterBlock<RegisterCallback> {
public:
  PredMapGlobMutable(
      int chipNumber, int index_pipe_addrmap, int index_mau_addrmap, int index_pred_map_glob_0, int index_pred_map_glob_1, RegisterCallback& write_callback = 0, RegisterCallback& read_callback = 0
  )
    : RegisterBlock(chipNumber, StartOffset(index_pipe_addrmap, index_mau_addrmap, index_pred_map_glob_0, index_pred_map_glob_1), 4, true, write_callback, read_callback, std::string("PredMapGlobMutable")+":"+boost::lexical_cast<std::string>(index_pipe_addrmap) + "," + boost::lexical_cast<std::string>(index_mau_addrmap) + "," + boost::lexical_cast<std::string>(index_pred_map_glob_0) + "," + boost::lexical_cast<std::string>(index_pred_map_glob_1))
    {
    }
  PredMapGlobMutable(
      
  )
    : RegisterBlock(0, 0, 0, true, 0, 0, "PredMapGlobMutable")
    {
    }
public:
  uint8_t pred_map_long_brch() { return pred_map_long_brch_; }
  void pred_map_long_brch(const uint8_t &v) { pred_map_long_brch_=v; }
  uint16_t pred_map_glob_exec() { return pred_map_glob_exec_; }
  void pred_map_glob_exec(const uint16_t &v) { pred_map_glob_exec_=v; }

  bool read(
      uint32_t offset, uint32_t* data
      ) const {
    if (read_callback_) read_callback_();
    *data = pred_map_long_brch_;
    *data |= (pred_map_glob_exec_ << 8);
    return true;
  }


  bool write(
      uint32_t offset, uint32_t data
      ) {
    pred_map_long_brch_ = data;
    pred_map_glob_exec_ = (data >> 8);
    if (write_callback_) write_callback_();
    return true;
  }

  void reset(
      
      ) {
    pred_map_long_brch_ = 0x0;
    pred_map_glob_exec_ = 0x0;
    if (write_callback_) write_callback_();
  }

  std::string to_string(
      uint32_t offset, bool print_zeros = false, std::string indent_string = ""
      ) const {
    std::string r("");
    bool all_zeros=true;
    r += indent_string + std::string("PredMapGlobMutable") + ":\n";
    r += indent_string + "  " + std::string("pred_map_long_brch") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(pred_map_long_brch_) ) + "\n";
    all_zeros &= (0 == pred_map_long_brch_);
    r += indent_string + "  " + std::string("pred_map_glob_exec") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(pred_map_glob_exec_) ) + "\n";
    all_zeros &= (0 == pred_map_glob_exec_);
    if (all_zeros && !print_zeros) {
      return("");
    }
    else {
      return r;
    }
  }

  std::string to_string(
      bool print_zeros = false, std::string indent_string = ""
      ) const {
    std::string r("");
    bool all_zeros=true;
    r += indent_string + std::string("PredMapGlobMutable") + ":\n";
    r += indent_string + "  " + std::string("pred_map_long_brch") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(pred_map_long_brch_) ) + "\n";
    all_zeros &= (0 == pred_map_long_brch_);
    r += indent_string + "  " + std::string("pred_map_glob_exec") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(pred_map_glob_exec_) ) + "\n";
    all_zeros &= (0 == pred_map_glob_exec_);
    if (all_zeros && !print_zeros) {
      return("");
    }
    else {
      return r;
    }
  }

private:
  uint8_t pred_map_long_brch_;
  uint16_t pred_map_glob_exec_;
private:
  static int StartOffset(
      int index_pipe_addrmap, int index_mau_addrmap, int index_pred_map_glob_0, int index_pred_map_glob_1
      ) {
    int offset=0;
    offset += 0x4000000; // to get to pipes
    assert(index_pipe_addrmap < 4);
    offset += index_pipe_addrmap * 0x1000000; // pipe_addrmap[]
    assert(index_mau_addrmap < 20);
    offset += index_mau_addrmap * 0x80000; // mau_addrmap[]
    offset += 0x60000; // to get to rams
    offset += 0x18000; // to get to match
    offset += 0x4000; // to get to merge
    offset += 0x1800; // to get to pred_map_glob
    assert(index_pred_map_glob_0 < 16);
    offset += index_pred_map_glob_0 * 0x20; // pred_map_glob[]
    assert(index_pred_map_glob_1 < 8);
    offset += index_pred_map_glob_1 * 0x4; // pred_map_glob[][]
    return offset;
  }

};














  }; // namespace register_classes
}; // namespace jbayB0

#endif // __REGISTER_INCLUDES_PRED_MAP_GLOB_MUTABLE_H__
