include Makefile

bf_drivers_binding_deps.dc:
	touch $@

bf_utils_binding_deps.dc:
	touch $@

bf_syslibs_binding_deps.dc:
	touch $@

include bf_drivers_binding_deps.dc
include bf_utils_binding_deps.dc
include bf_syslibs_binding_deps.dc
