/*******************************************************************************
 *  Copyright (C) 2024 Intel Corporation
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions
 *  and limitations under the License.
 *
 *
 *  SPDX-License-Identifier: Apache-2.0
 ******************************************************************************/

// generated by split_classes.pl
#ifndef __REGISTER_INCLUDES_EPB_PRSR_STAT_MUTABLE_H__
#define __REGISTER_INCLUDES_EPB_PRSR_STAT_MUTABLE_H__


#include <cstdint>
#include <cassert>
#include <array>
#include <vector>
#include <string>
#include <boost/lexical_cast.hpp>
#include <boost/format.hpp>
#include <model_core/register_block.h>
#include <shared/bitvector.h>










namespace jbay {
  namespace register_classes {

class EpbPrsrStatMutable : public model_core::RegisterBlock<RegisterCallback> {
public:
  EpbPrsrStatMutable(
      int chipNumber, int index_pipe_addrmap, int index_epb_prsr4_reg, RegisterCallback& write_callback = 0, RegisterCallback& read_callback = 0
  )
    : RegisterBlock(chipNumber, StartOffset(index_pipe_addrmap, index_epb_prsr4_reg), 8, true, write_callback, read_callback, std::string("EpbPrsrStatMutable")+":"+boost::lexical_cast<std::string>(index_pipe_addrmap) + "," + boost::lexical_cast<std::string>(index_epb_prsr4_reg))
    {
    }
  EpbPrsrStatMutable(
      
  )
    : RegisterBlock(0, 0, 0, true, 0, 0, "EpbPrsrStatMutable")
    {
    }
public:









  uint32_t st() { return st_; }
  void st(const uint32_t &v) { st_=v; }









  uint32_t st_nxt() { return st_nxt_; }
  void st_nxt(const uint32_t &v) { st_nxt_=v; }

  bool read(
      uint32_t offset, uint32_t* data
      ) const {
    if (offset < 0x4) {
      if (read_callback_) read_callback_();
      *data = (st_ & 0xffffff);
      *data |= ((st_nxt_ & 0xff) << 24);
    }
    else if (offset >= 0x4 && offset < 0x8) {
      if (read_callback_) read_callback_();
      *data = ((st_nxt_ & 0xffff00) >> 8);
    }
    else {
      assert(0);
    }
    return true;
  }


  bool write(
      uint32_t offset, uint32_t data
      ) {
    if (offset < 0x4) {
      st_ = (data & 0xffffff);
      st_nxt_ = (((data >> 24) & 0xff) | (st_nxt_ & 0xffff00));
      if (write_callback_) write_callback_();
    }
    else if (offset >= 0x4 && offset < 0x8) {
      st_nxt_ = (((data << 8) & 0xffff00) | (st_nxt_ & 0xff));
      if (write_callback_) write_callback_();
    }
    else {
      assert(0);
    }
    return true;
  }

  void reset(
      
      ) {
    st_ = 0x0;
    st_nxt_ = 0x0;
    if (write_callback_) write_callback_();
  }

  std::string to_string(
      uint32_t offset, bool print_zeros = false, std::string indent_string = ""
      ) const {
    std::string r("");
    bool all_zeros=true;
    r += indent_string + std::string("EpbPrsrStatMutable") + ":\n";
    r += indent_string + "  " + std::string("st") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(st_) ) + "\n";
    all_zeros &= (0 == st_);
    r += indent_string + "  " + std::string("st_nxt") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(st_nxt_) ) + "\n";
    all_zeros &= (0 == st_nxt_);
    if (all_zeros && !print_zeros) {
      return("");
    }
    else {
      return r;
    }
  }

  std::string to_string(
      bool print_zeros = false, std::string indent_string = ""
      ) const {
    std::string r("");
    bool all_zeros=true;
    r += indent_string + std::string("EpbPrsrStatMutable") + ":\n";
    r += indent_string + "  " + std::string("st") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(st_) ) + "\n";
    all_zeros &= (0 == st_);
    r += indent_string + "  " + std::string("st_nxt") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(st_nxt_) ) + "\n";
    all_zeros &= (0 == st_nxt_);
    if (all_zeros && !print_zeros) {
      return("");
    }
    else {
      return r;
    }
  }

private:
  uint32_t st_;
  uint32_t st_nxt_;
private:
  static int StartOffset(
      int index_pipe_addrmap, int index_epb_prsr4_reg
      ) {
    int offset=0;
    offset += 0x4000000; // to get to pipes
    assert(index_pipe_addrmap < 4);
    offset += index_pipe_addrmap * 0x1000000; // pipe_addrmap[]
    offset += 0xc00000; // to get to pardereg
    offset += 0x20000; // to get to epbprsr4reg
    assert(index_epb_prsr4_reg < 9);
    offset += index_epb_prsr4_reg * 0x2000; // epb_prsr4_reg[]
    offset += 0x20; // to get to glb_group_glb_prsr_stat
    return offset;
  }

};










  }; // namespace register_classes
}; // namespace jbay

#endif // __REGISTER_INCLUDES_EPB_PRSR_STAT_MUTABLE_H__
