/*******************************************************************************
 *  Copyright (C) 2024 Intel Corporation
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions
 *  and limitations under the License.
 *
 *
 *  SPDX-License-Identifier: Apache-2.0
 ******************************************************************************/

// generated by split_classes.pl
#ifndef __REGISTER_INCLUDES_IPB_RSPEC_CHAN7_GROUP_H__
#define __REGISTER_INCLUDES_IPB_RSPEC_CHAN7_GROUP_H__


#include <cstdint>
#include <cassert>
#include <array>
#include <vector>
#include <string>
#include <boost/lexical_cast.hpp>
#include <boost/format.hpp>
#include <model_core/register_block.h>
#include <shared/bitvector.h>









#include "chnl_acc_ctrl.h"
#include "chnl_acc_stat.h"
#include "chnl_ctrl.h"
#include "chnl_deparser_drop_pkt.h"
#include "chnl_deparser_send_pkt.h"
#include "chnl_drop_trunc_pkt.h"
#include "chnl_fifo_ctrl.h"
#include "chnl_macs_received_pkt.h"
#include "chnl_meta.h"
#include "chnl_metanum.h"
#include "chnl_metanum_cfg.h"
#include "chnl_parser_discard_pkt.h"
#include "chnl_parser_send_pkt.h"
#include "chnl_pktnum0.h"
#include "chnl_pktnum0_cfg.h"
#include "chnl_pktnum1.h"
#include "chnl_pktnum1_cfg.h"
#include "chnl_resubmit_discard_pkt.h"
#include "chnl_resubmit_received_pkt.h"
#include "chnl_stat.h"
#include "chnl_wsch_discard_pkt.h"
#include "chnl_wsch_trunc_pkt.h"
#include "meta_fifo_ctrl.h"

namespace jbay {
  namespace register_classes {

class IpbRspecChan7Group : public model_core::RegisterBlock<RegisterCallback> {
public:
  IpbRspecChan7Group(
      int chipNumber, int index_pipe_addrmap, int index_ipb_prsr4_reg, RegisterCallback& write_callback = 0, RegisterCallback& read_callback = 0
  )
    : RegisterBlock(chipNumber, StartOffset(index_pipe_addrmap, index_ipb_prsr4_reg), 216, false, write_callback, read_callback, std::string("IpbRspecChan7Group")+":"+boost::lexical_cast<std::string>(index_pipe_addrmap) + "," + boost::lexical_cast<std::string>(index_ipb_prsr4_reg))
    {
    }
  IpbRspecChan7Group(
      
  )
    : RegisterBlock(0, 0, 0, false, 0, 0, "IpbRspecChan7Group")
    {
    }
public:





  ChnlCtrl &chan7_group_chnl_ctrl() { return chan7_group_chnl_ctrl_; }






  ChnlMeta &chan7_group_chnl_meta() { return chan7_group_chnl_meta_; }





  MetaFifoCtrl &chan7_group_meta_fifo_ctrl() { return chan7_group_meta_fifo_ctrl_; }





  ChnlFifoCtrl &chan7_group_chnl_fifo_ctrl() { return chan7_group_chnl_fifo_ctrl_; }





  ChnlAccCtrl &chan7_group_chnl_acc_ctrl() { return chan7_group_chnl_acc_ctrl_; }





  ChnlAccStat &chan7_group_chnl_acc_stat() { return chan7_group_chnl_acc_stat_; }







  ChnlPktnum0Cfg &chan7_group_chnl_pktnum0_cfg() { return chan7_group_chnl_pktnum0_cfg_; }







  ChnlPktnum1Cfg &chan7_group_chnl_pktnum1_cfg() { return chan7_group_chnl_pktnum1_cfg_; }







  ChnlMetanumCfg &chan7_group_chnl_metanum_cfg() { return chan7_group_chnl_metanum_cfg_; }






  ChnlStat &chan7_group_chnl_stat() { return chan7_group_chnl_stat_; }








  ChnlPktnum0 &chan7_group_chnl_pktnum0() { return chan7_group_chnl_pktnum0_; }






  ChnlPktnum1 &chan7_group_chnl_pktnum1() { return chan7_group_chnl_pktnum1_; }







  ChnlMetanum &chan7_group_chnl_metanum() { return chan7_group_chnl_metanum_; }





  ChnlDeparserDropPkt &chan7_group_chnl_deparser_drop_pkt() { return chan7_group_chnl_deparser_drop_pkt_; }









  ChnlWschDiscardPkt &chan7_group_chnl_wsch_discard_pkt() { return chan7_group_chnl_wsch_discard_pkt_; }





  ChnlWschTruncPkt &chan7_group_chnl_wsch_trunc_pkt() { return chan7_group_chnl_wsch_trunc_pkt_; }





  ChnlDropTruncPkt &chan7_group_chnl_drop_trunc_pkt() { return chan7_group_chnl_drop_trunc_pkt_; }





  ChnlResubmitDiscardPkt &chan7_group_chnl_resubmit_discard_pkt() { return chan7_group_chnl_resubmit_discard_pkt_; }





  ChnlParserDiscardPkt &chan7_group_chnl_parser_discard_pkt() { return chan7_group_chnl_parser_discard_pkt_; }








  ChnlParserSendPkt &chan7_group_chnl_parser_send_pkt() { return chan7_group_chnl_parser_send_pkt_; }








  ChnlDeparserSendPkt &chan7_group_chnl_deparser_send_pkt() { return chan7_group_chnl_deparser_send_pkt_; }





  ChnlMacsReceivedPkt &chan7_group_chnl_macs_received_pkt() { return chan7_group_chnl_macs_received_pkt_; }





  ChnlResubmitReceivedPkt &chan7_group_chnl_resubmit_received_pkt() { return chan7_group_chnl_resubmit_received_pkt_; }

  bool read(
      uint32_t offset, uint32_t* data
      ) const {
    if (offset < 0x8) {
      offset -= 0x0;
      if (read_callback_) read_callback_();
      chan7_group_chnl_ctrl_.read( offset, data );
    }
    else if (offset >= 0x10 && offset < 0x20) {
      offset -= 0x10;
      if (read_callback_) read_callback_();
      chan7_group_chnl_meta_.read( offset, data );
    }
    else if (offset >= 0x20 && offset < 0x24) {
      offset -= 0x20;
      if (read_callback_) read_callback_();
      chan7_group_meta_fifo_ctrl_.read( offset, data );
    }
    else if (offset >= 0x30 && offset < 0x3c) {
      offset -= 0x30;
      if (read_callback_) read_callback_();
      chan7_group_chnl_fifo_ctrl_.read( offset, data );
    }
    else if (offset >= 0x40 && offset < 0x4c) {
      offset -= 0x40;
      if (read_callback_) read_callback_();
      chan7_group_chnl_acc_ctrl_.read( offset, data );
    }
    else if (offset >= 0x4c && offset < 0x50) {
      offset -= 0x4c;
      if (read_callback_) read_callback_();
      chan7_group_chnl_acc_stat_.read( offset, data );
    }
    else if (offset >= 0x50 && offset < 0x54) {
      offset -= 0x50;
      if (read_callback_) read_callback_();
      chan7_group_chnl_pktnum0_cfg_.read( offset, data );
    }
    else if (offset >= 0x54 && offset < 0x58) {
      offset -= 0x54;
      if (read_callback_) read_callback_();
      chan7_group_chnl_pktnum1_cfg_.read( offset, data );
    }
    else if (offset >= 0x58 && offset < 0x5c) {
      offset -= 0x58;
      if (read_callback_) read_callback_();
      chan7_group_chnl_metanum_cfg_.read( offset, data );
    }
    else if (offset >= 0x5c && offset < 0x60) {
      offset -= 0x5c;
      if (read_callback_) read_callback_();
      chan7_group_chnl_stat_.read( offset, data );
    }
    else if (offset >= 0x60 && offset < 0x64) {
      offset -= 0x60;
      if (read_callback_) read_callback_();
      chan7_group_chnl_pktnum0_.read( offset, data );
    }
    else if (offset >= 0x64 && offset < 0x68) {
      offset -= 0x64;
      if (read_callback_) read_callback_();
      chan7_group_chnl_pktnum1_.read( offset, data );
    }
    else if (offset >= 0x68 && offset < 0x6c) {
      offset -= 0x68;
      if (read_callback_) read_callback_();
      chan7_group_chnl_metanum_.read( offset, data );
    }
    else if (offset >= 0x70 && offset < 0x78) {
      offset -= 0x70;
      if (read_callback_) read_callback_();
      chan7_group_chnl_deparser_drop_pkt_.read( offset, data );
    }
    else if (offset >= 0x78 && offset < 0x80) {
      offset -= 0x78;
      if (read_callback_) read_callback_();
      chan7_group_chnl_wsch_discard_pkt_.read( offset, data );
    }
    else if (offset >= 0x80 && offset < 0x88) {
      offset -= 0x80;
      if (read_callback_) read_callback_();
      chan7_group_chnl_wsch_trunc_pkt_.read( offset, data );
    }
    else if (offset >= 0x88 && offset < 0x90) {
      offset -= 0x88;
      if (read_callback_) read_callback_();
      chan7_group_chnl_drop_trunc_pkt_.read( offset, data );
    }
    else if (offset >= 0x90 && offset < 0x98) {
      offset -= 0x90;
      if (read_callback_) read_callback_();
      chan7_group_chnl_resubmit_discard_pkt_.read( offset, data );
    }
    else if (offset >= 0x98 && offset < 0xa0) {
      offset -= 0x98;
      if (read_callback_) read_callback_();
      chan7_group_chnl_parser_discard_pkt_.read( offset, data );
    }
    else if (offset >= 0xa0 && offset < 0xac) {
      offset -= 0xa0;
      if (read_callback_) read_callback_();
      chan7_group_chnl_parser_send_pkt_.read( offset, data );
    }
    else if (offset >= 0xb0 && offset < 0xbc) {
      offset -= 0xb0;
      if (read_callback_) read_callback_();
      chan7_group_chnl_deparser_send_pkt_.read( offset, data );
    }
    else if (offset >= 0xc0 && offset < 0xcc) {
      offset -= 0xc0;
      if (read_callback_) read_callback_();
      chan7_group_chnl_macs_received_pkt_.read( offset, data );
    }
    else if (offset >= 0xd0 && offset < 0xd8) {
      offset -= 0xd0;
      if (read_callback_) read_callback_();
      chan7_group_chnl_resubmit_received_pkt_.read( offset, data );
    }
    return true;
  }


  bool write(
      uint32_t offset, uint32_t data
      ) {
    if (offset < 0x8) {
      offset -= 0x0;
      chan7_group_chnl_ctrl_.write( offset, data );
      if (write_callback_) write_callback_();
    }
    else if (offset >= 0x10 && offset < 0x20) {
      offset -= 0x10;
      chan7_group_chnl_meta_.write( offset, data );
      if (write_callback_) write_callback_();
    }
    else if (offset >= 0x20 && offset < 0x24) {
      offset -= 0x20;
      chan7_group_meta_fifo_ctrl_.write( offset, data );
      if (write_callback_) write_callback_();
    }
    else if (offset >= 0x30 && offset < 0x3c) {
      offset -= 0x30;
      chan7_group_chnl_fifo_ctrl_.write( offset, data );
      if (write_callback_) write_callback_();
    }
    else if (offset >= 0x40 && offset < 0x4c) {
      offset -= 0x40;
      chan7_group_chnl_acc_ctrl_.write( offset, data );
      if (write_callback_) write_callback_();
    }
    else if (offset >= 0x4c && offset < 0x50) {
      offset -= 0x4c;
      chan7_group_chnl_acc_stat_.write( offset, data );
      if (write_callback_) write_callback_();
    }
    else if (offset >= 0x50 && offset < 0x54) {
      offset -= 0x50;
      chan7_group_chnl_pktnum0_cfg_.write( offset, data );
      if (write_callback_) write_callback_();
    }
    else if (offset >= 0x54 && offset < 0x58) {
      offset -= 0x54;
      chan7_group_chnl_pktnum1_cfg_.write( offset, data );
      if (write_callback_) write_callback_();
    }
    else if (offset >= 0x58 && offset < 0x5c) {
      offset -= 0x58;
      chan7_group_chnl_metanum_cfg_.write( offset, data );
      if (write_callback_) write_callback_();
    }
    else if (offset >= 0x5c && offset < 0x60) {
      offset -= 0x5c;
      chan7_group_chnl_stat_.write( offset, data );
      if (write_callback_) write_callback_();
    }
    else if (offset >= 0x60 && offset < 0x64) {
      offset -= 0x60;
      chan7_group_chnl_pktnum0_.write( offset, data );
      if (write_callback_) write_callback_();
    }
    else if (offset >= 0x64 && offset < 0x68) {
      offset -= 0x64;
      chan7_group_chnl_pktnum1_.write( offset, data );
      if (write_callback_) write_callback_();
    }
    else if (offset >= 0x68 && offset < 0x6c) {
      offset -= 0x68;
      chan7_group_chnl_metanum_.write( offset, data );
      if (write_callback_) write_callback_();
    }
    else if (offset >= 0x70 && offset < 0x78) {
      offset -= 0x70;
      chan7_group_chnl_deparser_drop_pkt_.write( offset, data );
      if (write_callback_) write_callback_();
    }
    else if (offset >= 0x78 && offset < 0x80) {
      offset -= 0x78;
      chan7_group_chnl_wsch_discard_pkt_.write( offset, data );
      if (write_callback_) write_callback_();
    }
    else if (offset >= 0x80 && offset < 0x88) {
      offset -= 0x80;
      chan7_group_chnl_wsch_trunc_pkt_.write( offset, data );
      if (write_callback_) write_callback_();
    }
    else if (offset >= 0x88 && offset < 0x90) {
      offset -= 0x88;
      chan7_group_chnl_drop_trunc_pkt_.write( offset, data );
      if (write_callback_) write_callback_();
    }
    else if (offset >= 0x90 && offset < 0x98) {
      offset -= 0x90;
      chan7_group_chnl_resubmit_discard_pkt_.write( offset, data );
      if (write_callback_) write_callback_();
    }
    else if (offset >= 0x98 && offset < 0xa0) {
      offset -= 0x98;
      chan7_group_chnl_parser_discard_pkt_.write( offset, data );
      if (write_callback_) write_callback_();
    }
    else if (offset >= 0xa0 && offset < 0xac) {
      offset -= 0xa0;
      chan7_group_chnl_parser_send_pkt_.write( offset, data );
      if (write_callback_) write_callback_();
    }
    else if (offset >= 0xb0 && offset < 0xbc) {
      offset -= 0xb0;
      chan7_group_chnl_deparser_send_pkt_.write( offset, data );
      if (write_callback_) write_callback_();
    }
    else if (offset >= 0xc0 && offset < 0xcc) {
      offset -= 0xc0;
      chan7_group_chnl_macs_received_pkt_.write( offset, data );
      if (write_callback_) write_callback_();
    }
    else if (offset >= 0xd0 && offset < 0xd8) {
      offset -= 0xd0;
      chan7_group_chnl_resubmit_received_pkt_.write( offset, data );
      if (write_callback_) write_callback_();
    }
    return true;
  }

  void reset(
      
      ) {
    chan7_group_chnl_ctrl_.reset();
    chan7_group_chnl_meta_.reset();
    chan7_group_meta_fifo_ctrl_.reset();
    chan7_group_chnl_fifo_ctrl_.reset();
    chan7_group_chnl_acc_ctrl_.reset();
    chan7_group_chnl_acc_stat_.reset();
    chan7_group_chnl_pktnum0_cfg_.reset();
    chan7_group_chnl_pktnum1_cfg_.reset();
    chan7_group_chnl_metanum_cfg_.reset();
    chan7_group_chnl_stat_.reset();
    chan7_group_chnl_pktnum0_.reset();
    chan7_group_chnl_pktnum1_.reset();
    chan7_group_chnl_metanum_.reset();
    chan7_group_chnl_deparser_drop_pkt_.reset();
    chan7_group_chnl_wsch_discard_pkt_.reset();
    chan7_group_chnl_wsch_trunc_pkt_.reset();
    chan7_group_chnl_drop_trunc_pkt_.reset();
    chan7_group_chnl_resubmit_discard_pkt_.reset();
    chan7_group_chnl_parser_discard_pkt_.reset();
    chan7_group_chnl_parser_send_pkt_.reset();
    chan7_group_chnl_deparser_send_pkt_.reset();
    chan7_group_chnl_macs_received_pkt_.reset();
    chan7_group_chnl_resubmit_received_pkt_.reset();
    if (write_callback_) write_callback_();
  }

  std::string to_string(
      uint32_t offset, bool print_zeros = false, std::string indent_string = ""
      ) const {
    std::string r("");
    bool all_zeros=true;
    all_zeros=false;
    if (offset < 0x8) {
      offset -= 0x0;
      r += chan7_group_chnl_ctrl_.to_string(offset,print_zeros,indent_string) ;
    }
    else if (offset >= 0x10 && offset < 0x20) {
      offset -= 0x10;
      r += chan7_group_chnl_meta_.to_string(offset,print_zeros,indent_string) ;
    }
    else if (offset >= 0x20 && offset < 0x24) {
      offset -= 0x20;
      r += chan7_group_meta_fifo_ctrl_.to_string(offset,print_zeros,indent_string) ;
    }
    else if (offset >= 0x30 && offset < 0x3c) {
      offset -= 0x30;
      r += chan7_group_chnl_fifo_ctrl_.to_string(offset,print_zeros,indent_string) ;
    }
    else if (offset >= 0x40 && offset < 0x4c) {
      offset -= 0x40;
      r += chan7_group_chnl_acc_ctrl_.to_string(offset,print_zeros,indent_string) ;
    }
    else if (offset >= 0x4c && offset < 0x50) {
      offset -= 0x4c;
      r += chan7_group_chnl_acc_stat_.to_string(offset,print_zeros,indent_string) ;
    }
    else if (offset >= 0x50 && offset < 0x54) {
      offset -= 0x50;
      r += chan7_group_chnl_pktnum0_cfg_.to_string(offset,print_zeros,indent_string) ;
    }
    else if (offset >= 0x54 && offset < 0x58) {
      offset -= 0x54;
      r += chan7_group_chnl_pktnum1_cfg_.to_string(offset,print_zeros,indent_string) ;
    }
    else if (offset >= 0x58 && offset < 0x5c) {
      offset -= 0x58;
      r += chan7_group_chnl_metanum_cfg_.to_string(offset,print_zeros,indent_string) ;
    }
    else if (offset >= 0x5c && offset < 0x60) {
      offset -= 0x5c;
      r += chan7_group_chnl_stat_.to_string(offset,print_zeros,indent_string) ;
    }
    else if (offset >= 0x60 && offset < 0x64) {
      offset -= 0x60;
      r += chan7_group_chnl_pktnum0_.to_string(offset,print_zeros,indent_string) ;
    }
    else if (offset >= 0x64 && offset < 0x68) {
      offset -= 0x64;
      r += chan7_group_chnl_pktnum1_.to_string(offset,print_zeros,indent_string) ;
    }
    else if (offset >= 0x68 && offset < 0x6c) {
      offset -= 0x68;
      r += chan7_group_chnl_metanum_.to_string(offset,print_zeros,indent_string) ;
    }
    else if (offset >= 0x70 && offset < 0x78) {
      offset -= 0x70;
      r += chan7_group_chnl_deparser_drop_pkt_.to_string(offset,print_zeros,indent_string) ;
    }
    else if (offset >= 0x78 && offset < 0x80) {
      offset -= 0x78;
      r += chan7_group_chnl_wsch_discard_pkt_.to_string(offset,print_zeros,indent_string) ;
    }
    else if (offset >= 0x80 && offset < 0x88) {
      offset -= 0x80;
      r += chan7_group_chnl_wsch_trunc_pkt_.to_string(offset,print_zeros,indent_string) ;
    }
    else if (offset >= 0x88 && offset < 0x90) {
      offset -= 0x88;
      r += chan7_group_chnl_drop_trunc_pkt_.to_string(offset,print_zeros,indent_string) ;
    }
    else if (offset >= 0x90 && offset < 0x98) {
      offset -= 0x90;
      r += chan7_group_chnl_resubmit_discard_pkt_.to_string(offset,print_zeros,indent_string) ;
    }
    else if (offset >= 0x98 && offset < 0xa0) {
      offset -= 0x98;
      r += chan7_group_chnl_parser_discard_pkt_.to_string(offset,print_zeros,indent_string) ;
    }
    else if (offset >= 0xa0 && offset < 0xac) {
      offset -= 0xa0;
      r += chan7_group_chnl_parser_send_pkt_.to_string(offset,print_zeros,indent_string) ;
    }
    else if (offset >= 0xb0 && offset < 0xbc) {
      offset -= 0xb0;
      r += chan7_group_chnl_deparser_send_pkt_.to_string(offset,print_zeros,indent_string) ;
    }
    else if (offset >= 0xc0 && offset < 0xcc) {
      offset -= 0xc0;
      r += chan7_group_chnl_macs_received_pkt_.to_string(offset,print_zeros,indent_string) ;
    }
    else if (offset >= 0xd0 && offset < 0xd8) {
      offset -= 0xd0;
      r += chan7_group_chnl_resubmit_received_pkt_.to_string(offset,print_zeros,indent_string) ;
    }
    if (all_zeros && !print_zeros) {
      return("");
    }
    else {
      return r;
    }
  }

  std::string to_string(
      bool print_zeros = false, std::string indent_string = ""
      ) const {
    std::string r("");
    bool all_zeros=true;
    all_zeros=false;
    r += chan7_group_chnl_ctrl_.to_string(print_zeros,indent_string) ;
    r += chan7_group_chnl_meta_.to_string(print_zeros,indent_string) ;
    r += chan7_group_meta_fifo_ctrl_.to_string(print_zeros,indent_string) ;
    r += chan7_group_chnl_fifo_ctrl_.to_string(print_zeros,indent_string) ;
    r += chan7_group_chnl_acc_ctrl_.to_string(print_zeros,indent_string) ;
    r += chan7_group_chnl_acc_stat_.to_string(print_zeros,indent_string) ;
    r += chan7_group_chnl_pktnum0_cfg_.to_string(print_zeros,indent_string) ;
    r += chan7_group_chnl_pktnum1_cfg_.to_string(print_zeros,indent_string) ;
    r += chan7_group_chnl_metanum_cfg_.to_string(print_zeros,indent_string) ;
    r += chan7_group_chnl_stat_.to_string(print_zeros,indent_string) ;
    r += chan7_group_chnl_pktnum0_.to_string(print_zeros,indent_string) ;
    r += chan7_group_chnl_pktnum1_.to_string(print_zeros,indent_string) ;
    r += chan7_group_chnl_metanum_.to_string(print_zeros,indent_string) ;
    r += chan7_group_chnl_deparser_drop_pkt_.to_string(print_zeros,indent_string) ;
    r += chan7_group_chnl_wsch_discard_pkt_.to_string(print_zeros,indent_string) ;
    r += chan7_group_chnl_wsch_trunc_pkt_.to_string(print_zeros,indent_string) ;
    r += chan7_group_chnl_drop_trunc_pkt_.to_string(print_zeros,indent_string) ;
    r += chan7_group_chnl_resubmit_discard_pkt_.to_string(print_zeros,indent_string) ;
    r += chan7_group_chnl_parser_discard_pkt_.to_string(print_zeros,indent_string) ;
    r += chan7_group_chnl_parser_send_pkt_.to_string(print_zeros,indent_string) ;
    r += chan7_group_chnl_deparser_send_pkt_.to_string(print_zeros,indent_string) ;
    r += chan7_group_chnl_macs_received_pkt_.to_string(print_zeros,indent_string) ;
    r += chan7_group_chnl_resubmit_received_pkt_.to_string(print_zeros,indent_string) ;
    if (all_zeros && !print_zeros) {
      return("");
    }
    else {
      return r;
    }
  }

private:
  ChnlCtrl chan7_group_chnl_ctrl_;
  ChnlMeta chan7_group_chnl_meta_;
  MetaFifoCtrl chan7_group_meta_fifo_ctrl_;
  ChnlFifoCtrl chan7_group_chnl_fifo_ctrl_;
  ChnlAccCtrl chan7_group_chnl_acc_ctrl_;
  ChnlAccStat chan7_group_chnl_acc_stat_;
  ChnlPktnum0Cfg chan7_group_chnl_pktnum0_cfg_;
  ChnlPktnum1Cfg chan7_group_chnl_pktnum1_cfg_;
  ChnlMetanumCfg chan7_group_chnl_metanum_cfg_;
  ChnlStat chan7_group_chnl_stat_;
  ChnlPktnum0 chan7_group_chnl_pktnum0_;
  ChnlPktnum1 chan7_group_chnl_pktnum1_;
  ChnlMetanum chan7_group_chnl_metanum_;
  ChnlDeparserDropPkt chan7_group_chnl_deparser_drop_pkt_;
  ChnlWschDiscardPkt chan7_group_chnl_wsch_discard_pkt_;
  ChnlWschTruncPkt chan7_group_chnl_wsch_trunc_pkt_;
  ChnlDropTruncPkt chan7_group_chnl_drop_trunc_pkt_;
  ChnlResubmitDiscardPkt chan7_group_chnl_resubmit_discard_pkt_;
  ChnlParserDiscardPkt chan7_group_chnl_parser_discard_pkt_;
  ChnlParserSendPkt chan7_group_chnl_parser_send_pkt_;
  ChnlDeparserSendPkt chan7_group_chnl_deparser_send_pkt_;
  ChnlMacsReceivedPkt chan7_group_chnl_macs_received_pkt_;
  ChnlResubmitReceivedPkt chan7_group_chnl_resubmit_received_pkt_;
private:
  static int StartOffset(
      int index_pipe_addrmap, int index_ipb_prsr4_reg
      ) {
    int offset=0;
    offset += 0x4000000; // to get to pipes
    assert(index_pipe_addrmap < 4);
    offset += index_pipe_addrmap * 0x1000000; // pipe_addrmap[]
    offset += 0xc00000; // to get to pardereg
    assert(index_ipb_prsr4_reg < 9);
    offset += index_ipb_prsr4_reg * 0x2000; // ipb_prsr4_reg[]
    offset += 0xf00; // to get to chan7_group
    return offset;
  }

};









  }; // namespace register_classes
}; // namespace jbay

#endif // __REGISTER_INCLUDES_IPB_RSPEC_CHAN7_GROUP_H__
