/*******************************************************************************
 *  Copyright (C) 2024 Intel Corporation
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions
 *  and limitations under the License.
 *
 *
 *  SPDX-License-Identifier: Apache-2.0
 ******************************************************************************/

// generated by split_classes.pl
#ifndef __REGISTER_INCLUDES_MISC_REGS_PCIE_PHY_SRAM_INIT_STATUS_MUTABLE_H__
#define __REGISTER_INCLUDES_MISC_REGS_PCIE_PHY_SRAM_INIT_STATUS_MUTABLE_H__


#include <cstdint>
#include <cassert>
#include <array>
#include <vector>
#include <string>
#include <boost/lexical_cast.hpp>
#include <boost/format.hpp>
#include <model_core/register_block.h>
#include <shared/bitvector.h>










namespace jbay {
  namespace register_classes {

class MiscRegsPciePhySramInitStatusMutable : public model_core::RegisterBlock<RegisterCallback> {
public:
  MiscRegsPciePhySramInitStatusMutable(
      int chipNumber, RegisterCallback& write_callback = 0, RegisterCallback& read_callback = 0
  )
    : RegisterBlock(chipNumber, StartOffset(), 4, true, write_callback, read_callback, std::string("MiscRegsPciePhySramInitStatusMutable"))
    {
    }
  MiscRegsPciePhySramInitStatusMutable(
      
  )
    : RegisterBlock(0, 0, 0, true, 0, 0, "MiscRegsPciePhySramInitStatusMutable")
    {
    }
public:





  uint8_t load_done() { return load_done_; }
  void load_done(const uint8_t &v) { load_done_=v; }





  uint8_t init_done() { return init_done_; }
  void init_done(const uint8_t &v) { init_done_=v; }

  bool read(
      uint32_t offset, uint32_t* data
      ) const {
    if (read_callback_) read_callback_();
    *data = (load_done_ & 0x1);
    *data |= ((init_done_ & 0x1) << 1);
    return true;
  }


  bool write(
      uint32_t offset, uint32_t data
      ) {
    load_done_ = (data & 0x1);
    init_done_ = ((data >> 1) & 0x1);
    if (write_callback_) write_callback_();
    return true;
  }

  void reset(
      
      ) {
    load_done_ = 0x0;
    init_done_ = 0x0;
    if (write_callback_) write_callback_();
  }

  std::string to_string(
      uint32_t offset, bool print_zeros = false, std::string indent_string = ""
      ) const {
    std::string r("");
    bool all_zeros=true;
    r += indent_string + std::string("MiscRegsPciePhySramInitStatusMutable") + ":\n";
    r += indent_string + "  " + std::string("load_done") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(load_done_) ) + "\n";
    all_zeros &= (0 == load_done_);
    r += indent_string + "  " + std::string("init_done") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(init_done_) ) + "\n";
    all_zeros &= (0 == init_done_);
    if (all_zeros && !print_zeros) {
      return("");
    }
    else {
      return r;
    }
  }

  std::string to_string(
      bool print_zeros = false, std::string indent_string = ""
      ) const {
    std::string r("");
    bool all_zeros=true;
    r += indent_string + std::string("MiscRegsPciePhySramInitStatusMutable") + ":\n";
    r += indent_string + "  " + std::string("load_done") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(load_done_) ) + "\n";
    all_zeros &= (0 == load_done_);
    r += indent_string + "  " + std::string("init_done") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(init_done_) ) + "\n";
    all_zeros &= (0 == init_done_);
    if (all_zeros && !print_zeros) {
      return("");
    }
    else {
      return r;
    }
  }

private:
  uint8_t load_done_;
  uint8_t init_done_;
private:
  static int StartOffset(
      
      ) {
    int offset=0;
    offset += 0x80000; // to get to misc_regs
    offset += 0x4c; // to get to pcie_phy_sram_init_status
    return offset;
  }

};










  }; // namespace register_classes
}; // namespace jbay

#endif // __REGISTER_INCLUDES_MISC_REGS_PCIE_PHY_SRAM_INIT_STATUS_MUTABLE_H__
