/*******************************************************************************
 *  Copyright (C) 2024 Intel Corporation
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions
 *  and limitations under the License.
 *
 *
 *  SPDX-License-Identifier: Apache-2.0
 ******************************************************************************/

// generated by split_classes.pl
#ifndef __REGISTER_INCLUDES_PGR_PGEN_RETRIGGER_PORT_DOWN_H__
#define __REGISTER_INCLUDES_PGR_PGEN_RETRIGGER_PORT_DOWN_H__


#include <cstdint>
#include <cassert>
#include <array>
#include <vector>
#include <string>
#include <boost/lexical_cast.hpp>
#include <boost/format.hpp>
#include <model_core/register_block.h>
#include <shared/bitvector.h>










namespace jbay {
  namespace register_classes {

class PgrPgenRetriggerPortDown : public model_core::RegisterBlock<RegisterCallback> {
public:
  PgrPgenRetriggerPortDown(
      int chipNumber, int index_pipe_addrmap, RegisterCallback& write_callback = 0, RegisterCallback& read_callback = 0
  )
    : RegisterBlock(chipNumber, StartOffset(index_pipe_addrmap), 4, false, write_callback, read_callback, std::string("PgrPgenRetriggerPortDown")+":"+boost::lexical_cast<std::string>(index_pipe_addrmap))
    {
    }
  PgrPgenRetriggerPortDown(
      
  )
    : RegisterBlock(0, 0, 0, false, 0, 0, "PgrPgenRetriggerPortDown")
    {
    }
public:









  uint8_t &en() { return en_; }






  uint8_t &all_down_port() { return all_down_port_; }

  bool read(
      uint32_t offset, uint32_t* data
      ) const {
    if (read_callback_) read_callback_();
    *data = (en_ & 0x1);
    *data |= ((all_down_port_ & 0x1) << 1);
    return true;
  }


  bool write(
      uint32_t offset, uint32_t data
      ) {
    en_ = (data & 0x1);
    all_down_port_ = ((data >> 1) & 0x1);
    if (write_callback_) write_callback_();
    return true;
  }

  void reset(
      
      ) {
    en_ = 0x0;
    all_down_port_ = 0x0;
    if (write_callback_) write_callback_();
  }

  std::string to_string(
      uint32_t offset, bool print_zeros = false, std::string indent_string = ""
      ) const {
    std::string r("");
    bool all_zeros=true;
    r += indent_string + std::string("PgrPgenRetriggerPortDown") + ":\n";
    r += indent_string + "  " + std::string("en") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(en_) ) + "\n";
    all_zeros &= (0 == en_);
    r += indent_string + "  " + std::string("all_down_port") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(all_down_port_) ) + "\n";
    all_zeros &= (0 == all_down_port_);
    if (all_zeros && !print_zeros) {
      return("");
    }
    else {
      return r;
    }
  }

  std::string to_string(
      bool print_zeros = false, std::string indent_string = ""
      ) const {
    std::string r("");
    bool all_zeros=true;
    r += indent_string + std::string("PgrPgenRetriggerPortDown") + ":\n";
    r += indent_string + "  " + std::string("en") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(en_) ) + "\n";
    all_zeros &= (0 == en_);
    r += indent_string + "  " + std::string("all_down_port") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(all_down_port_) ) + "\n";
    all_zeros &= (0 == all_down_port_);
    if (all_zeros && !print_zeros) {
      return("");
    }
    else {
      return r;
    }
  }

private:
  uint8_t en_;
  uint8_t all_down_port_;
private:
  static int StartOffset(
      int index_pipe_addrmap
      ) {
    int offset=0;
    offset += 0x4000000; // to get to pipes
    assert(index_pipe_addrmap < 4);
    offset += index_pipe_addrmap * 0x1000000; // pipe_addrmap[]
    offset += 0xc00000; // to get to pardereg
    offset += 0x34000; // to get to pgrreg
    offset += 0x2000; // to get to pgr_common
    offset += 0x8c; // to get to pgen_retrigger_port_down
    return offset;
  }

};









  }; // namespace register_classes
}; // namespace jbay

#endif // __REGISTER_INCLUDES_PGR_PGEN_RETRIGGER_PORT_DOWN_H__
