/*******************************************************************************
 *  Copyright (C) 2024 Intel Corporation
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions
 *  and limitations under the License.
 *
 *
 *  SPDX-License-Identifier: Apache-2.0
 ******************************************************************************/

// generated by split_classes.pl
#ifndef __REGISTER_INCLUDES_PGR_APP_CTR48_BATCH_H__
#define __REGISTER_INCLUDES_PGR_APP_CTR48_BATCH_H__


#include <cstdint>
#include <cassert>
#include <array>
#include <vector>
#include <string>
#include <boost/lexical_cast.hpp>
#include <boost/format.hpp>
#include <model_core/register_block.h>
#include <shared/bitvector.h>










namespace jbay {
  namespace register_classes {

class PgrAppCtr48Batch : public model_core::RegisterBlock<RegisterCallback> {
public:
  PgrAppCtr48Batch(
      int chipNumber, int index_pipe_addrmap, int index_pgr_app_reg_rspec, RegisterCallback& write_callback = 0, RegisterCallback& read_callback = 0
  )
    : RegisterBlock(chipNumber, StartOffset(index_pipe_addrmap, index_pgr_app_reg_rspec), 8, false, write_callback, read_callback, std::string("PgrAppCtr48Batch")+":"+boost::lexical_cast<std::string>(index_pipe_addrmap) + "," + boost::lexical_cast<std::string>(index_pgr_app_reg_rspec))
    {
    }
  PgrAppCtr48Batch(
      
  )
    : RegisterBlock(0, 0, 0, false, 0, 0, "PgrAppCtr48Batch")
    {
    }
public:





  uint64_t &ctr48() { return ctr48_; }

  bool read(
      uint32_t offset, uint32_t* data
      ) const {
    if (offset < 0x4) {
      if (read_callback_) read_callback_();
      *data = (ctr48_ & 0xffffffff);
    }
    else if (offset >= 0x4 && offset < 0x8) {
      if (read_callback_) read_callback_();
      *data = ((ctr48_ & UINT64_C(0xffff00000000)) >> 32);
    }
    else {
      assert(0);
    }
    return true;
  }


  bool write(
      uint32_t offset, uint32_t data
      ) {
    if (offset < 0x4) {
      ctr48_ = ((static_cast<uint64_t>(data) & 0xffffffff) | (ctr48_ & UINT64_C(0xffff00000000)));
      if (write_callback_) write_callback_();
    }
    else if (offset >= 0x4 && offset < 0x8) {
      ctr48_ = (((static_cast<uint64_t>(data) << 32) & UINT64_C(0xffff00000000)) | (ctr48_ & 0xffffffff));
      if (write_callback_) write_callback_();
    }
    else {
      assert(0);
    }
    return true;
  }

  void reset(
      
      ) {
    ctr48_ = UINT64_C(0x0);
    if (write_callback_) write_callback_();
  }

  std::string to_string(
      uint32_t offset, bool print_zeros = false, std::string indent_string = ""
      ) const {
    std::string r("");
    bool all_zeros=true;
    r += indent_string + std::string("PgrAppCtr48Batch") + ":\n";
    r += indent_string + "  " + std::string("ctr48") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(ctr48_) ) + "\n";
    all_zeros &= (0 == ctr48_);
    if (all_zeros && !print_zeros) {
      return("");
    }
    else {
      return r;
    }
  }

  std::string to_string(
      bool print_zeros = false, std::string indent_string = ""
      ) const {
    std::string r("");
    bool all_zeros=true;
    r += indent_string + std::string("PgrAppCtr48Batch") + ":\n";
    r += indent_string + "  " + std::string("ctr48") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(ctr48_) ) + "\n";
    all_zeros &= (0 == ctr48_);
    if (all_zeros && !print_zeros) {
      return("");
    }
    else {
      return r;
    }
  }

private:
  uint64_t ctr48_;
private:
  static int StartOffset(
      int index_pipe_addrmap, int index_pgr_app_reg_rspec
      ) {
    int offset=0;
    offset += 0x4000000; // to get to pipes
    assert(index_pipe_addrmap < 4);
    offset += index_pipe_addrmap * 0x1000000; // pipe_addrmap[]
    offset += 0xc00000; // to get to pardereg
    offset += 0x34000; // to get to pgrreg
    assert(index_pgr_app_reg_rspec < 16);
    offset += index_pgr_app_reg_rspec * 0x200; // pgr_app_reg_rspec[]
    offset += 0x58; // to get to ctr48_batch
    return offset;
  }

};









  }; // namespace register_classes
}; // namespace jbay

#endif // __REGISTER_INCLUDES_PGR_APP_CTR48_BATCH_H__
