/*******************************************************************************
 *  Copyright (C) 2024 Intel Corporation
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions
 *  and limitations under the License.
 *
 *
 *  SPDX-License-Identifier: Apache-2.0
 ******************************************************************************/

// generated by split_classes.pl
#ifndef __REGISTER_INCLUDES_PRED_GLOB_EXEC_THREAD_MUTABLE_H__
#define __REGISTER_INCLUDES_PRED_GLOB_EXEC_THREAD_MUTABLE_H__


#include <cstdint>
#include <cassert>
#include <array>
#include <vector>
#include <string>
#include <boost/lexical_cast.hpp>
#include <boost/format.hpp>
#include <model_core/register_block.h>
#include <shared/bitvector.h>










namespace jbay {
  namespace register_classes {

class PredGlobExecThreadMutable : public model_core::RegisterBlock<RegisterCallback> {
public:
  PredGlobExecThreadMutable(
      int chipNumber, int index_pipe_addrmap, int index_mau_addrmap, int index_pred_glob_exec_thread, RegisterCallback& write_callback = 0, RegisterCallback& read_callback = 0
  )
    : RegisterBlock(chipNumber, StartOffset(index_pipe_addrmap, index_mau_addrmap, index_pred_glob_exec_thread), 4, true, write_callback, read_callback, std::string("PredGlobExecThreadMutable")+":"+boost::lexical_cast<std::string>(index_pipe_addrmap) + "," + boost::lexical_cast<std::string>(index_mau_addrmap) + "," + boost::lexical_cast<std::string>(index_pred_glob_exec_thread))
    {
    }
  PredGlobExecThreadMutable(
      
  )
    : RegisterBlock(0, 0, 0, true, 0, 0, "PredGlobExecThreadMutable")
    {
    }
public:
  uint16_t pred_glob_exec_thread() { return pred_glob_exec_thread_; }
  void pred_glob_exec_thread(const uint16_t &v) { pred_glob_exec_thread_=v; }

  bool read(
      uint32_t offset, uint32_t* data
      ) const {
    if (read_callback_) read_callback_();
    *data = pred_glob_exec_thread_;
    return true;
  }


  bool write(
      uint32_t offset, uint32_t data
      ) {
    pred_glob_exec_thread_ = data;
    if (write_callback_) write_callback_();
    return true;
  }

  void reset(
      
      ) {
    pred_glob_exec_thread_ = 0x0;
    if (write_callback_) write_callback_();
  }

  std::string to_string(
      uint32_t offset, bool print_zeros = false, std::string indent_string = ""
      ) const {
    std::string r("");
    bool all_zeros=true;
    r += indent_string + std::string("PredGlobExecThreadMutable") + ":\n";
    r += indent_string + "  " + std::string("pred_glob_exec_thread") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(pred_glob_exec_thread_) ) + "\n";
    all_zeros &= (0 == pred_glob_exec_thread_);
    if (all_zeros && !print_zeros) {
      return("");
    }
    else {
      return r;
    }
  }

  std::string to_string(
      bool print_zeros = false, std::string indent_string = ""
      ) const {
    std::string r("");
    bool all_zeros=true;
    r += indent_string + std::string("PredGlobExecThreadMutable") + ":\n";
    r += indent_string + "  " + std::string("pred_glob_exec_thread") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(pred_glob_exec_thread_) ) + "\n";
    all_zeros &= (0 == pred_glob_exec_thread_);
    if (all_zeros && !print_zeros) {
      return("");
    }
    else {
      return r;
    }
  }

private:
  uint16_t pred_glob_exec_thread_;
private:
  static int StartOffset(
      int index_pipe_addrmap, int index_mau_addrmap, int index_pred_glob_exec_thread
      ) {
    int offset=0;
    offset += 0x4000000; // to get to pipes
    assert(index_pipe_addrmap < 4);
    offset += index_pipe_addrmap * 0x1000000; // pipe_addrmap[]
    assert(index_mau_addrmap < 20);
    offset += index_mau_addrmap * 0x80000; // mau_addrmap[]
    offset += 0x60000; // to get to rams
    offset += 0x18000; // to get to match
    offset += 0x4000; // to get to merge
    offset += 0x10c0; // to get to pred_glob_exec_thread
    assert(index_pred_glob_exec_thread < 3);
    offset += index_pred_glob_exec_thread * 0x4; // pred_glob_exec_thread[]
    return offset;
  }

};











  }; // namespace register_classes
}; // namespace jbay

#endif // __REGISTER_INCLUDES_PRED_GLOB_EXEC_THREAD_MUTABLE_H__
