/*******************************************************************************
 *  Copyright (C) 2024 Intel Corporation
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions
 *  and limitations under the License.
 *
 *
 *  SPDX-License-Identifier: Apache-2.0
 ******************************************************************************/

// generated by split_classes.pl
#ifndef __REGISTER_INCLUDES_R_ACTION_O_MUX_SELECT_H__
#define __REGISTER_INCLUDES_R_ACTION_O_MUX_SELECT_H__


#include <cstdint>
#include <cassert>
#include <array>
#include <vector>
#include <string>
#include <boost/lexical_cast.hpp>
#include <boost/format.hpp>
#include <model_core/register_block.h>
#include <shared/bitvector.h>










namespace jbay {
  namespace register_classes {

class RActionOMuxSelect : public model_core::RegisterBlock<RegisterCallback> {
public:
  RActionOMuxSelect(
      int chipNumber, int index_pipe_addrmap, int index_mau_addrmap, int index_mau_memory_data_hv_switchbox_row_addrmap, RegisterCallback& write_callback = 0, RegisterCallback& read_callback = 0
  )
    : RegisterBlock(chipNumber, StartOffset(index_pipe_addrmap, index_mau_addrmap, index_mau_memory_data_hv_switchbox_row_addrmap), 4, false, write_callback, read_callback, std::string("RActionOMuxSelect")+":"+boost::lexical_cast<std::string>(index_pipe_addrmap) + "," + boost::lexical_cast<std::string>(index_mau_addrmap) + "," + boost::lexical_cast<std::string>(index_mau_memory_data_hv_switchbox_row_addrmap))
    {
    }
  RActionOMuxSelect(
      
  )
    : RegisterBlock(0, 0, 0, false, 0, 0, "RActionOMuxSelect")
    {
    }
public:



  uint8_t &r_action_o_sel_action_rd_r_i() { return r_action_o_sel_action_rd_r_i_; }



  uint8_t &r_action_o_sel_oflo2up_rd_t_i() { return r_action_o_sel_oflo2up_rd_t_i_; }



  uint8_t &r_action_o_sel_oflo2dn_rd_b_i() { return r_action_o_sel_oflo2dn_rd_b_i_; }



  uint8_t &r_action_o_sel_oflo_rd_b_i() { return r_action_o_sel_oflo_rd_b_i_; }



  uint8_t &r_action_o_sel_oflo2_rd_l_i() { return r_action_o_sel_oflo2_rd_l_i_; }



  uint8_t &r_action_o_sel_oflo_rd_l_i() { return r_action_o_sel_oflo_rd_l_i_; }

  bool read(
      uint32_t offset, uint32_t* data
      ) const {
    if (read_callback_) read_callback_();
    *data = (r_action_o_sel_action_rd_r_i_ & 0x1);
    *data |= ((r_action_o_sel_oflo2up_rd_t_i_ & 0x1) << 1);
    *data |= ((r_action_o_sel_oflo2dn_rd_b_i_ & 0x1) << 2);
    *data |= ((r_action_o_sel_oflo_rd_b_i_ & 0x1) << 3);
    *data |= ((r_action_o_sel_oflo2_rd_l_i_ & 0x1) << 4);
    *data |= ((r_action_o_sel_oflo_rd_l_i_ & 0x1) << 5);
    return true;
  }


  bool write(
      uint32_t offset, uint32_t data
      ) {
    r_action_o_sel_action_rd_r_i_ = (data & 0x1);
    r_action_o_sel_oflo2up_rd_t_i_ = ((data >> 1) & 0x1);
    r_action_o_sel_oflo2dn_rd_b_i_ = ((data >> 2) & 0x1);
    r_action_o_sel_oflo_rd_b_i_ = ((data >> 3) & 0x1);
    r_action_o_sel_oflo2_rd_l_i_ = ((data >> 4) & 0x1);
    r_action_o_sel_oflo_rd_l_i_ = ((data >> 5) & 0x1);
    if (write_callback_) write_callback_();
    return true;
  }

  void reset(
      
      ) {
    r_action_o_sel_action_rd_r_i_ = 0x0;
    r_action_o_sel_oflo2up_rd_t_i_ = 0x0;
    r_action_o_sel_oflo2dn_rd_b_i_ = 0x0;
    r_action_o_sel_oflo_rd_b_i_ = 0x0;
    r_action_o_sel_oflo2_rd_l_i_ = 0x0;
    r_action_o_sel_oflo_rd_l_i_ = 0x0;
    if (write_callback_) write_callback_();
  }

  std::string to_string(
      uint32_t offset, bool print_zeros = false, std::string indent_string = ""
      ) const {
    std::string r("");
    bool all_zeros=true;
    r += indent_string + std::string("RActionOMuxSelect") + ":\n";
    r += indent_string + "  " + std::string("r_action_o_sel_action_rd_r_i") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(r_action_o_sel_action_rd_r_i_) ) + "\n";
    all_zeros &= (0 == r_action_o_sel_action_rd_r_i_);
    r += indent_string + "  " + std::string("r_action_o_sel_oflo2up_rd_t_i") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(r_action_o_sel_oflo2up_rd_t_i_) ) + "\n";
    all_zeros &= (0 == r_action_o_sel_oflo2up_rd_t_i_);
    r += indent_string + "  " + std::string("r_action_o_sel_oflo2dn_rd_b_i") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(r_action_o_sel_oflo2dn_rd_b_i_) ) + "\n";
    all_zeros &= (0 == r_action_o_sel_oflo2dn_rd_b_i_);
    r += indent_string + "  " + std::string("r_action_o_sel_oflo_rd_b_i") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(r_action_o_sel_oflo_rd_b_i_) ) + "\n";
    all_zeros &= (0 == r_action_o_sel_oflo_rd_b_i_);
    r += indent_string + "  " + std::string("r_action_o_sel_oflo2_rd_l_i") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(r_action_o_sel_oflo2_rd_l_i_) ) + "\n";
    all_zeros &= (0 == r_action_o_sel_oflo2_rd_l_i_);
    r += indent_string + "  " + std::string("r_action_o_sel_oflo_rd_l_i") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(r_action_o_sel_oflo_rd_l_i_) ) + "\n";
    all_zeros &= (0 == r_action_o_sel_oflo_rd_l_i_);
    if (all_zeros && !print_zeros) {
      return("");
    }
    else {
      return r;
    }
  }

  std::string to_string(
      bool print_zeros = false, std::string indent_string = ""
      ) const {
    std::string r("");
    bool all_zeros=true;
    r += indent_string + std::string("RActionOMuxSelect") + ":\n";
    r += indent_string + "  " + std::string("r_action_o_sel_action_rd_r_i") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(r_action_o_sel_action_rd_r_i_) ) + "\n";
    all_zeros &= (0 == r_action_o_sel_action_rd_r_i_);
    r += indent_string + "  " + std::string("r_action_o_sel_oflo2up_rd_t_i") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(r_action_o_sel_oflo2up_rd_t_i_) ) + "\n";
    all_zeros &= (0 == r_action_o_sel_oflo2up_rd_t_i_);
    r += indent_string + "  " + std::string("r_action_o_sel_oflo2dn_rd_b_i") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(r_action_o_sel_oflo2dn_rd_b_i_) ) + "\n";
    all_zeros &= (0 == r_action_o_sel_oflo2dn_rd_b_i_);
    r += indent_string + "  " + std::string("r_action_o_sel_oflo_rd_b_i") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(r_action_o_sel_oflo_rd_b_i_) ) + "\n";
    all_zeros &= (0 == r_action_o_sel_oflo_rd_b_i_);
    r += indent_string + "  " + std::string("r_action_o_sel_oflo2_rd_l_i") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(r_action_o_sel_oflo2_rd_l_i_) ) + "\n";
    all_zeros &= (0 == r_action_o_sel_oflo2_rd_l_i_);
    r += indent_string + "  " + std::string("r_action_o_sel_oflo_rd_l_i") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(r_action_o_sel_oflo_rd_l_i_) ) + "\n";
    all_zeros &= (0 == r_action_o_sel_oflo_rd_l_i_);
    if (all_zeros && !print_zeros) {
      return("");
    }
    else {
      return r;
    }
  }

private:
  uint8_t r_action_o_sel_action_rd_r_i_;
  uint8_t r_action_o_sel_oflo2up_rd_t_i_;
  uint8_t r_action_o_sel_oflo2dn_rd_b_i_;
  uint8_t r_action_o_sel_oflo_rd_b_i_;
  uint8_t r_action_o_sel_oflo2_rd_l_i_;
  uint8_t r_action_o_sel_oflo_rd_l_i_;
private:
  static int StartOffset(
      int index_pipe_addrmap, int index_mau_addrmap, int index_mau_memory_data_hv_switchbox_row_addrmap
      ) {
    int offset=0;
    offset += 0x4000000; // to get to pipes
    assert(index_pipe_addrmap < 4);
    offset += index_pipe_addrmap * 0x1000000; // pipe_addrmap[]
    assert(index_mau_addrmap < 20);
    offset += index_mau_addrmap * 0x80000; // mau_addrmap[]
    offset += 0x60000; // to get to rams
    assert(index_mau_memory_data_hv_switchbox_row_addrmap < 8);
    offset += index_mau_memory_data_hv_switchbox_row_addrmap * 0x40; // mau_memory_data_hv_switchbox_row_addrmap[]
    offset += 0x14; // to get to r_action_o_mux_select
    return offset;
  }

};










  }; // namespace register_classes
}; // namespace jbay

#endif // __REGISTER_INCLUDES_R_ACTION_O_MUX_SELECT_H__
