/*******************************************************************************
 *  Copyright (C) 2024 Intel Corporation
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions
 *  and limitations under the License.
 *
 *
 *  SPDX-License-Identifier: Apache-2.0
 ******************************************************************************/

// generated by split_classes.pl
#ifndef __REGISTER_INCLUDES_TBUS_FREEZE_EN1_H__
#define __REGISTER_INCLUDES_TBUS_FREEZE_EN1_H__


#include <cstdint>
#include <cassert>
#include <array>
#include <vector>
#include <string>
#include <boost/lexical_cast.hpp>
#include <boost/format.hpp>
#include <model_core/register_block.h>
#include <shared/bitvector.h>










namespace jbay {
  namespace register_classes {

class TbusFreezeEn1 : public model_core::RegisterBlock<RegisterCallback> {
public:
  TbusFreezeEn1(
      int chipNumber, RegisterCallback& write_callback = 0, RegisterCallback& read_callback = 0
  )
    : RegisterBlock(chipNumber, StartOffset(), 4, false, write_callback, read_callback, std::string("TbusFreezeEn1"))
    {
    }
  TbusFreezeEn1(
      
  )
    : RegisterBlock(0, 0, 0, false, 0, 0, "TbusFreezeEn1")
    {
    }
public:





  uint32_t &en() { return en_; }

  bool read(
      uint32_t offset, uint32_t* data
      ) const {
    if (read_callback_) read_callback_();
    *data = en_;
    return true;
  }


  bool write(
      uint32_t offset, uint32_t data
      ) {
    en_ = data;
    if (write_callback_) write_callback_();
    return true;
  }

  void reset(
      
      ) {
    en_ = 0x0;
    if (write_callback_) write_callback_();
  }

  std::string to_string(
      uint32_t offset, bool print_zeros = false, std::string indent_string = ""
      ) const {
    std::string r("");
    bool all_zeros=true;
    r += indent_string + std::string("TbusFreezeEn1") + ":\n";
    r += indent_string + "  " + std::string("en") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(en_) ) + "\n";
    all_zeros &= (0 == en_);
    if (all_zeros && !print_zeros) {
      return("");
    }
    else {
      return r;
    }
  }

  std::string to_string(
      bool print_zeros = false, std::string indent_string = ""
      ) const {
    std::string r("");
    bool all_zeros=true;
    r += indent_string + std::string("TbusFreezeEn1") + ":\n";
    r += indent_string + "  " + std::string("en") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(en_) ) + "\n";
    all_zeros &= (0 == en_);
    if (all_zeros && !print_zeros) {
      return("");
    }
    else {
      return r;
    }
  }

private:
  uint32_t en_;
private:
  static int StartOffset(
      
      ) {
    int offset=0;
    offset += 0x300000; // to get to tbc
    offset += 0x48; // to get to freeze_en1
    return offset;
  }

};









  }; // namespace register_classes
}; // namespace jbay

#endif // __REGISTER_INCLUDES_TBUS_FREEZE_EN1_H__
