/*******************************************************************************
 *  Copyright (C) 2024 Intel Corporation
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions
 *  and limitations under the License.
 *
 *
 *  SPDX-License-Identifier: Apache-2.0
 ******************************************************************************/

/* clang-format off */

void eth400g_pcs_rspec_eth_soft_reset_ethpcs_swrst_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_eth_soft_reset_ethpcs_swrst_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_eth_soft_reset_ethpcs_swrst_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_eth_clkobs_ctrl_sel_clkobs0_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_eth_clkobs_ctrl_sel_clkobs0_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_eth_clkobs_ctrl_sel_clkobs0_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_eth_clkobs_ctrl_sel_clkdiv0_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_eth_clkobs_ctrl_sel_clkdiv0_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_eth_clkobs_ctrl_sel_clkdiv0_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_eth_clkobs_ctrl_sel_clkena0_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_eth_clkobs_ctrl_sel_clkena0_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_eth_clkobs_ctrl_sel_clkena0_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_eth_clkobs_ctrl_sel_clkobs1_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_eth_clkobs_ctrl_sel_clkobs1_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_eth_clkobs_ctrl_sel_clkobs1_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_eth_clkobs_ctrl_sel_clkdiv1_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_eth_clkobs_ctrl_sel_clkdiv1_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_eth_clkobs_ctrl_sel_clkdiv1_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_eth_clkobs_ctrl_sel_clkena1_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_eth_clkobs_ctrl_sel_clkena1_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_eth_clkobs_ctrl_sel_clkena1_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_eth_rxsigok_ctrl_sigok_debounce_count_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_eth_rxsigok_ctrl_sigok_debounce_count_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_eth_rxsigok_ctrl_sigok_debounce_count_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_eth_rxsigok_ctrl_force_rxsigok_high_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_eth_rxsigok_ctrl_force_rxsigok_high_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_eth_rxsigok_ctrl_force_rxsigok_high_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_eth_rxsigok_ctrl_force_rxsigok_low_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_eth_rxsigok_ctrl_force_rxsigok_low_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_eth_rxsigok_ctrl_force_rxsigok_low_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_eth_mdioci_ctrl_mdioci_en_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_eth_mdioci_ctrl_mdioci_en_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_eth_mdioci_ctrl_mdioci_en_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_eth_mdioci_ctrl_mdioci_reset_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_eth_mdioci_ctrl_mdioci_reset_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_eth_mdioci_ctrl_mdioci_reset_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_eth_mdioci_ctrl_mdioci_clkdiv_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_eth_mdioci_ctrl_mdioci_clkdiv_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_eth_mdioci_ctrl_mdioci_clkdiv_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_eth_mdioci_poll_ctrl_poll_addr_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_eth_mdioci_poll_ctrl_poll_addr_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_eth_mdioci_poll_ctrl_poll_addr_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_eth_mdioci_poll_time_poll_time_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_eth_mdioci_poll_time_poll_time_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_eth_mdioci_poll_time_poll_time_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_eth_mdioci_poll_time_poll_ena_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_eth_mdioci_poll_time_poll_ena_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_eth_mdioci_poll_time_poll_ena_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_eth_rxsigok_bitsel_rxsigok_sel0_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_eth_rxsigok_bitsel_rxsigok_sel0_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_eth_rxsigok_bitsel_rxsigok_sel0_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_eth_rxsigok_bitsel_rxsigok_sel1_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_eth_rxsigok_bitsel_rxsigok_sel1_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_eth_rxsigok_bitsel_rxsigok_sel1_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_eth_rxsigok_bitsel_rxsigok_sel2_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_eth_rxsigok_bitsel_rxsigok_sel2_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_eth_rxsigok_bitsel_rxsigok_sel2_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_eth_rxsigok_bitsel_rxsigok_sel3_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_eth_rxsigok_bitsel_rxsigok_sel3_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_eth_rxsigok_bitsel_rxsigok_sel3_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_eth_rxsigok_bitsel_rxsigok_sel4_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_eth_rxsigok_bitsel_rxsigok_sel4_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_eth_rxsigok_bitsel_rxsigok_sel4_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_eth_rxsigok_bitsel_rxsigok_sel5_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_eth_rxsigok_bitsel_rxsigok_sel5_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_eth_rxsigok_bitsel_rxsigok_sel5_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_eth_rxsigok_bitsel_rxsigok_sel6_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_eth_rxsigok_bitsel_rxsigok_sel6_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_eth_rxsigok_bitsel_rxsigok_sel6_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_eth_rxsigok_bitsel_rxsigok_sel7_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_eth_rxsigok_bitsel_rxsigok_sel7_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_eth_rxsigok_bitsel_rxsigok_sel7_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_mdioci_intr_stat_intr_stat_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_mdioci_intr_stat_intr_stat_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_mdioci_intr_stat_intr_stat_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_txsds_mode_mode_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_txsds_mode_mode_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_txsds_mode_mode_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_rxsds_mode_mode_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_rxsds_mode_mode_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_rxsds_mode_mode_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_sds_112g_mode_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_sds_112g_mode_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_sds_112g_mode_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_eth_ppm_sel_sel_rxclk_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_eth_ppm_sel_sel_rxclk_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_eth_ppm_sel_sel_rxclk_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_eth_ppm_sel_sel_txclk_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_eth_ppm_sel_sel_txclk_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_eth_ppm_sel_sel_txclk_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_eth_ppm_ctrl_max_count_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_eth_ppm_ctrl_max_count_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_eth_ppm_ctrl_max_count_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_eth_ppm_ctrl_ppm_ena_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_eth_ppm_ctrl_ppm_ena_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_eth_ppm_ctrl_ppm_ena_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_eth_ppm_stat_ppm_seen_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_eth_ppm_stat_ppm_seen_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_eth_ppm_stat_ppm_seen_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_eth_ppm_stat_ppm_val_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_eth_ppm_stat_ppm_val_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_eth_ppm_stat_ppm_val_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_mem_intr_stat_deskew_sbe_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_mem_intr_stat_deskew_sbe_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_mem_intr_stat_deskew_sbe_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_mem_intr_stat_deskew_mbe_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_mem_intr_stat_deskew_mbe_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_mem_intr_stat_deskew_mbe_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_mem_intr_stat_rsfec_sbe_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_mem_intr_stat_rsfec_sbe_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_mem_intr_stat_rsfec_sbe_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_mem_intr_stat_rsfec_mbe_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_mem_intr_stat_rsfec_mbe_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_mem_intr_stat_rsfec_mbe_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_mem_intr_en0_deskew_sbe_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_mem_intr_en0_deskew_sbe_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_mem_intr_en0_deskew_sbe_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_mem_intr_en0_deskew_mbe_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_mem_intr_en0_deskew_mbe_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_mem_intr_en0_deskew_mbe_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_mem_intr_en0_rsfec_sbe_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_mem_intr_en0_rsfec_sbe_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_mem_intr_en0_rsfec_sbe_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_mem_intr_en0_rsfec_mbe_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_mem_intr_en0_rsfec_mbe_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_mem_intr_en0_rsfec_mbe_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_mem_intr_en1_deskew_sbe_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_mem_intr_en1_deskew_sbe_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_mem_intr_en1_deskew_sbe_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_mem_intr_en1_deskew_mbe_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_mem_intr_en1_deskew_mbe_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_mem_intr_en1_deskew_mbe_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_mem_intr_en1_rsfec_sbe_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_mem_intr_en1_rsfec_sbe_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_mem_intr_en1_rsfec_sbe_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_mem_intr_en1_rsfec_mbe_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_mem_intr_en1_rsfec_mbe_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_mem_intr_en1_rsfec_mbe_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_mem_intr_inj_deskew_sbe_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_mem_intr_inj_deskew_sbe_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_mem_intr_inj_deskew_sbe_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_mem_intr_inj_deskew_mbe_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_mem_intr_inj_deskew_mbe_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_mem_intr_inj_deskew_mbe_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_mem_intr_inj_rsfec_sbe_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_mem_intr_inj_rsfec_sbe_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_mem_intr_inj_rsfec_sbe_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_mem_intr_inj_rsfec_mbe_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_mem_intr_inj_rsfec_mbe_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_mem_intr_inj_rsfec_mbe_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_deskew_ecc_mem0_disable_check_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_deskew_ecc_mem0_disable_check_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_deskew_ecc_mem0_disable_check_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_deskew_ecc_mem0_inject_sbe_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_deskew_ecc_mem0_inject_sbe_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_deskew_ecc_mem0_inject_sbe_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_deskew_ecc_mem0_inject_mbe_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_deskew_ecc_mem0_inject_mbe_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_deskew_ecc_mem0_inject_mbe_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_deskew_ecc_mem1_inject_sbe_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_deskew_ecc_mem1_inject_sbe_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_deskew_ecc_mem1_inject_sbe_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_deskew_ecc_mem1_inject_mbe_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_deskew_ecc_mem1_inject_mbe_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_deskew_ecc_mem1_inject_mbe_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_deskew_ecc_mem2_inject_sbe_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_deskew_ecc_mem2_inject_sbe_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_deskew_ecc_mem2_inject_sbe_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_deskew_ecc_mem2_inject_mbe_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_deskew_ecc_mem2_inject_mbe_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_deskew_ecc_mem2_inject_mbe_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_deskew_ecc_mem3_inject_sbe_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_deskew_ecc_mem3_inject_sbe_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_deskew_ecc_mem3_inject_sbe_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_deskew_ecc_mem3_inject_mbe_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_deskew_ecc_mem3_inject_mbe_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_deskew_ecc_mem3_inject_mbe_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_deskew_ecc_mem4_inject_sbe_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_deskew_ecc_mem4_inject_sbe_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_deskew_ecc_mem4_inject_sbe_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_deskew_ecc_mem4_inject_mbe_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_deskew_ecc_mem4_inject_mbe_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_deskew_ecc_mem4_inject_mbe_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_deskew_ecc_mem5_inject_sbe_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_deskew_ecc_mem5_inject_sbe_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_deskew_ecc_mem5_inject_sbe_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_deskew_ecc_mem5_inject_mbe_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_deskew_ecc_mem5_inject_mbe_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_deskew_ecc_mem5_inject_mbe_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_deskew_ecc_mem6_inject_sbe_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_deskew_ecc_mem6_inject_sbe_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_deskew_ecc_mem6_inject_sbe_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_deskew_ecc_mem6_inject_mbe_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_deskew_ecc_mem6_inject_mbe_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_deskew_ecc_mem6_inject_mbe_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_deskew_ecc_mem7_inject_sbe_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_deskew_ecc_mem7_inject_sbe_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_deskew_ecc_mem7_inject_sbe_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_deskew_ecc_mem7_inject_mbe_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_deskew_ecc_mem7_inject_mbe_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_deskew_ecc_mem7_inject_mbe_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_rsfec23_ecc_mem2_sram0_inject_sbe_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_rsfec23_ecc_mem2_sram0_inject_sbe_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_rsfec23_ecc_mem2_sram0_inject_sbe_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_rsfec23_ecc_mem2_sram0_inject_mbe_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_rsfec23_ecc_mem2_sram0_inject_mbe_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_rsfec23_ecc_mem2_sram0_inject_mbe_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_rsfec23_ecc_mem2_sram1_inject_sbe_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_rsfec23_ecc_mem2_sram1_inject_sbe_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_rsfec23_ecc_mem2_sram1_inject_sbe_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_rsfec23_ecc_mem2_sram1_inject_mbe_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_rsfec23_ecc_mem2_sram1_inject_mbe_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_rsfec23_ecc_mem2_sram1_inject_mbe_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_rsfec23_ecc_mem2_sram2_inject_sbe_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_rsfec23_ecc_mem2_sram2_inject_sbe_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_rsfec23_ecc_mem2_sram2_inject_sbe_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_rsfec23_ecc_mem2_sram2_inject_mbe_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_rsfec23_ecc_mem2_sram2_inject_mbe_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_rsfec23_ecc_mem2_sram2_inject_mbe_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_rsfec23_ecc_mem2_sram3_inject_sbe_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_rsfec23_ecc_mem2_sram3_inject_sbe_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_rsfec23_ecc_mem2_sram3_inject_sbe_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_rsfec23_ecc_mem2_sram3_inject_mbe_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_rsfec23_ecc_mem2_sram3_inject_mbe_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_rsfec23_ecc_mem2_sram3_inject_mbe_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_rsfec23_ecc_mem3_sram0_inject_sbe_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_rsfec23_ecc_mem3_sram0_inject_sbe_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_rsfec23_ecc_mem3_sram0_inject_sbe_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_rsfec23_ecc_mem3_sram0_inject_mbe_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_rsfec23_ecc_mem3_sram0_inject_mbe_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_rsfec23_ecc_mem3_sram0_inject_mbe_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_rsfec23_ecc_mem3_sram1_inject_sbe_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_rsfec23_ecc_mem3_sram1_inject_sbe_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_rsfec23_ecc_mem3_sram1_inject_sbe_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_rsfec23_ecc_mem3_sram1_inject_mbe_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_rsfec23_ecc_mem3_sram1_inject_mbe_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_rsfec23_ecc_mem3_sram1_inject_mbe_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_rsfec23_ecc_mem3_sram2_inject_sbe_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_rsfec23_ecc_mem3_sram2_inject_sbe_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_rsfec23_ecc_mem3_sram2_inject_sbe_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_rsfec23_ecc_mem3_sram2_inject_mbe_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_rsfec23_ecc_mem3_sram2_inject_mbe_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_rsfec23_ecc_mem3_sram2_inject_mbe_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_rsfec23_ecc_mem3_sram3_inject_sbe_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_rsfec23_ecc_mem3_sram3_inject_sbe_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_rsfec23_ecc_mem3_sram3_inject_sbe_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_rsfec23_ecc_mem3_sram3_inject_mbe_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_rsfec23_ecc_mem3_sram3_inject_mbe_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_rsfec23_ecc_mem3_sram3_inject_mbe_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_deskew_mbe_err_log_addr_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_deskew_mbe_err_log_addr_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_deskew_mbe_err_log_addr_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_deskew_mbe_err_log_laneid_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_deskew_mbe_err_log_laneid_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_deskew_mbe_err_log_laneid_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_rsfec_sbe_err_log_addr_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_rsfec_sbe_err_log_addr_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_rsfec_sbe_err_log_addr_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_rsfec_sbe_err_log_instid_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_rsfec_sbe_err_log_instid_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_rsfec_sbe_err_log_instid_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_rsfec_sbe_err_log_memid_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_rsfec_sbe_err_log_memid_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_rsfec_sbe_err_log_memid_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_rsfec_mbe_err_log_addr_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_rsfec_mbe_err_log_addr_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_rsfec_mbe_err_log_addr_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_rsfec_mbe_err_log_instid_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_rsfec_mbe_err_log_instid_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_rsfec_mbe_err_log_instid_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_rsfec_mbe_err_log_memid_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_rsfec_mbe_err_log_memid_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_rsfec_mbe_err_log_memid_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_mdioci_en0_intr_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_mdioci_en0_intr_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_mdioci_en0_intr_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
void eth400g_pcs_rspec_mdioci_en1_intr_set( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val, bool hw);
void eth400g_pcs_rspec_mdioci_en1_intr_get( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t *val, bool hw);
void eth400g_pcs_rspec_mdioci_en1_intr_rmw( bf_dev_id_t dev_id, uint32_t umac, uint32_t *data_p, uint32_t val);
