/*******************************************************************************
 *  Copyright (C) 2024 Intel Corporation
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions
 *  and limitations under the License.
 *
 *
 *  SPDX-License-Identifier: Apache-2.0
 ******************************************************************************/

UMAC4_RMON_CTR(FramesXmitOK)
UMAC4_RMON_CTR(FramesXmitAll)
UMAC4_RMON_CTR(FramesXmitError)
UMAC4_RMON_CTR(OctetsXmitOK)
UMAC4_RMON_CTR(OctetsXmitAll)
UMAC4_RMON_CTR(FramesXmitUnicast)
UMAC4_RMON_CTR(FramesXmitMulticast)
UMAC4_RMON_CTR(FramesXmitBroadcast)
UMAC4_RMON_CTR(FramesXmitPause)
UMAC4_RMON_CTR(FramesXmitPriPause)
UMAC4_RMON_CTR(FramesXmitVLAN)
UMAC4_RMON_CTR(FramesXmitSizeLT64)
UMAC4_RMON_CTR(FramesXmitSizeEQ64)
UMAC4_RMON_CTR(FramesXmitSize65to127)
UMAC4_RMON_CTR(FramesXmitSize128to255)
UMAC4_RMON_CTR(FramesXmitSize256to511)
UMAC4_RMON_CTR(FramesXmitSize512to1023)
UMAC4_RMON_CTR(FramesXmitSize1024to1518)
UMAC4_RMON_CTR(FramesXmitSize1519to2047)
UMAC4_RMON_CTR(FramesXmitSize2048to4095)
UMAC4_RMON_CTR(FramesXmitSize4096to8191)
UMAC4_RMON_CTR(FramesSmitSize8192to9215)
UMAC4_RMON_CTR(FramesXmitSizeGT9216)
UMAC4_RMON_CTR(FramesXmitPri0)
UMAC4_RMON_CTR(FramesXmitPri1)
UMAC4_RMON_CTR(FramesXmitPri2)
UMAC4_RMON_CTR(FramesXmitPri3)
UMAC4_RMON_CTR(FramesXmitPri4)
UMAC4_RMON_CTR(FramesXmitPri5)
UMAC4_RMON_CTR(FramesXmitPri6)
UMAC4_RMON_CTR(FramesXmitPri7)
UMAC4_RMON_CTR(XmitPri0Pause1US)
UMAC4_RMON_CTR(XmitPri1Pause1US)
UMAC4_RMON_CTR(XmitPri2Pause1US)
UMAC4_RMON_CTR(XmitPri3Pause1US)
UMAC4_RMON_CTR(XmitPri4Pause1US)
UMAC4_RMON_CTR(XmitPri5Pause1US)
UMAC4_RMON_CTR(XmitPri6Pause1US)
UMAC4_RMON_CTR(XmitPri7Pause1US)
UMAC4_RMON_CTR(FramesXmitDrained)
UMAC4_RMON_CTR(FramesXmitJabbered)
UMAC4_RMON_CTR(FramesXmitPadded)
UMAC4_RMON_CTR(FramesXmitTruncated)
UMAC4_RMON_CTR(FramesRcvdOK)
UMAC4_RMON_CTR(OctetsRcvdOK)
UMAC4_RMON_CTR(FramesRcvdAll)
UMAC4_RMON_CTR(OctetsRcvdAll)
UMAC4_RMON_CTR(FramesRcvdCRCError)
UMAC4_RMON_CTR(FramesRcvdError)
UMAC4_RMON_CTR(FramesRcvdUnicast)
UMAC4_RMON_CTR(FramesRcvdMulticast)
UMAC4_RMON_CTR(FramesRcvdBroadcast)
UMAC4_RMON_CTR(FramesRcvdPause)
UMAC4_RMON_CTR(FramesRcvdLenError)
UMAC4_RMON_CTR(Reserved)
UMAC4_RMON_CTR(FramesRcvdOversized)
UMAC4_RMON_CTR(FramesRcvdFragments)
UMAC4_RMON_CTR(FramesRcvdJabber)
UMAC4_RMON_CTR(FramesRcvdPriPause)
UMAC4_RMON_CTR(FramesRcvdCrcErrStomp)
UMAC4_RMON_CTR(FramesRcvdMaxFrmSizeVio)
UMAC4_RMON_CTR(FramesRcvdVLAN)
UMAC4_RMON_CTR(FramesDropped)
UMAC4_RMON_CTR(FramesRcvdSizeLT64)
UMAC4_RMON_CTR(FramesRcvdSizeEQ64)
UMAC4_RMON_CTR(FramesRcvdSize65to127)
UMAC4_RMON_CTR(FramesRcvdSize128to255)
UMAC4_RMON_CTR(FramesRcvdSize256to511)
UMAC4_RMON_CTR(FramesRcvdSize512to1023)
UMAC4_RMON_CTR(FramesRcvdSize1024to1518)
UMAC4_RMON_CTR(FramesRcvdSize1519to2047)
UMAC4_RMON_CTR(FramesRcvdSize2048to4095)
UMAC4_RMON_CTR(FramesRcvdSize4096to8191)
UMAC4_RMON_CTR(FramesRcvdSize8192to9215)
UMAC4_RMON_CTR(FramesRcvdSizeGT9216)
UMAC4_RMON_CTR(FramesRcvdPri0)
UMAC4_RMON_CTR(FramesRcvdPri1)
UMAC4_RMON_CTR(FramesRcvdPri2)
UMAC4_RMON_CTR(FramesRcvdPri3)
UMAC4_RMON_CTR(FramesRcvdPri4)
UMAC4_RMON_CTR(FramesRcvdPri5)
UMAC4_RMON_CTR(FramesRcvdPri6)
UMAC4_RMON_CTR(FramesRcvdPri7)
UMAC4_RMON_CTR(RcvdPri0Pause1US)
UMAC4_RMON_CTR(RcvdPri1Pause1US)
UMAC4_RMON_CTR(RcvdPri2Pause1US)
UMAC4_RMON_CTR(RcvdPri3Pause1US)
UMAC4_RMON_CTR(RcvdPri4Pause1US)
UMAC4_RMON_CTR(RcvdPri5Pause1US)
UMAC4_RMON_CTR(RcvdPri6Pause1US)
UMAC4_RMON_CTR(RcvdPri7Pause1US)
UMAC4_RMON_CTR(RcvdStdPause1US)
UMAC4_RMON_CTR(FramesRcvdTrunc)
UMAC4_RMON_CTR(Reserved2)
UMAC4_RMON_CTR(InvalidPreamble)
UMAC4_RMON_CTR(NormalLenInvalidCRC)
