/*******************************************************************************
 *  Copyright (C) 2024 Intel Corporation
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions
 *  and limitations under the License.
 *
 *
 *  SPDX-License-Identifier: Apache-2.0
 ******************************************************************************/

"C370        Number of errored BIPs received",
    "C378        Number of errored BIPs received",
    "C380        Number of errored BIPs received",
    "C388        Number of errored BIPs received",
    "C390        Number of errored BIPs received",
    "C398        Number of errored BIPs received",
    "C3A0        Number of errored BIPs received",
    "C3A8        Number of errored BIPs received",
    "C3B0        Number of errored BIPs received",
    "C3B8        Number of errored BIPs received",
    "C3C0        Number of errored BIPs received",
    "C3C8        Number of errored BIPs received",
    "C3D0        Number of errored BIPs received",
    "C3D8        Number of errored BIPs received",
    "C3E0        Number of errored BIPs received",
    "C3E8        Number of errored BIPs received",
    "C3F0        Number of errored BIPs received",
    "C3F8        Number of errored BIPs received",
    "C770        Number of errored BIPs received",
    "C778        Number of errored BIPs received",
    "C780        Number of errored BIPs received",
    "C788        Number of errored BIPs received",
    "C790        Number of errored BIPs received",
    "C798        Number of errored BIPs received",
    "C7A0        Number of errored BIPs received",
    "C7A8        Number of errored BIPs received",
    "C7B0        Number of errored BIPs received",
    "C7B8        Number of errored BIPs received",
    "C7C0        Number of errored BIPs received",
    "C7C8        Number of errored BIPs received",
    "C7D0        Number of errored BIPs received",
    "C7D8        Number of errored BIPs received",
    "C7E0        Number of errored BIPs received",
    "C7E8        Number of errored BIPs received",
    "C7F0        Number of errored BIPs received",
    "C7F8        Number of errored BIPs received",
    "CB70        Number of errored BIPs received",
    "CB78        Number of errored BIPs received",
    "CB80        Number of errored BIPs received",
    "CB88        Number of errored BIPs received",
    "CB90        Number of errored BIPs received",
    "CB98        Number of errored BIPs received",
    "CBA0        Number of errored BIPs received",
    "CBA8        Number of errored BIPs received",
    "CBB0        Number of errored BIPs received",
    "CBB8        Number of errored BIPs received",
    "CBC0        Number of errored BIPs received",
    "CBC8        Number of errored BIPs received",
    "CBD0        Number of errored BIPs received",
    "CBD8        Number of errored BIPs received",
    "CBE0        Number of errored BIPs received",
    "CBE8        Number of errored BIPs received",
    "CBF0        Number of errored BIPs received",
    "CBF8        Number of errored BIPs received",
    "CF70        Number of errored BIPs received",
    "CF78        Number of errored BIPs received",
    "CF80        Number of errored BIPs received",
    "CF88        Number of errored BIPs received",
    "CF90        Number of errored BIPs received",
    "CF98        Number of errored BIPs received",
    "CFA0        Number of errored BIPs received",
    "CFA8        Number of errored BIPs received",
    "CFB0        Number of errored BIPs received",
    "CFB8        Number of errored BIPs received",
    "CFC0        Number of errored BIPs received",
    "CFC8        Number of errored BIPs received",
    "CFD0        Number of errored BIPs received",
    "CFD8        Number of errored BIPs received",
    "CFE0        Number of errored BIPs received",
    "CFE8        Number of errored BIPs received",
    "CFF0        Number of errored BIPs received",
    "CFF8        Number of errored BIPs received",
    "D370        Number of errored BIPs received",
    "D378        Number of errored BIPs received",
    "D380        Number of errored BIPs received",
    "D388        Number of errored BIPs received",
    "D390        Number of errored BIPs received",
    "D398        Number of errored BIPs received",
    "D3A0        Number of errored BIPs received",
    "D3A8        Number of errored BIPs received",
