/*******************************************************************************
 *  Copyright (C) 2024 Intel Corporation
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions
 *  and limitations under the License.
 *
 *
 *  SPDX-License-Identifier: Apache-2.0
 ******************************************************************************/

/* clang-format off */
uint64_t get_fld_chmode0__chmode__mode( uint64_t *reg_val );
uint64_t set_fld_chmode0__chmode__mode( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_chmode0__chmode__txswrst( uint64_t *reg_val );
uint64_t set_fld_chmode0__chmode__txswrst( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_chmode0__chmode__rxswrst( uint64_t *reg_val );
uint64_t set_fld_chmode0__chmode__rxswrst( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_chmode0__chmode__txen( uint64_t *reg_val );
uint64_t set_fld_chmode0__chmode__txen( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_chmode0__chmode__txdrain( uint64_t *reg_val );
uint64_t set_fld_chmode0__chmode__txdrain( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_chmode0__chmode__rxen( uint64_t *reg_val );
uint64_t set_fld_chmode0__chmode__rxen( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_chmode0__chmode__gmiilpbk( uint64_t *reg_val );
uint64_t set_fld_chmode0__chmode__gmiilpbk( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_chmode0__chmode__txjabber( uint64_t *reg_val );
uint64_t set_fld_chmode0__chmode__txjabber( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_chmode0__chmode__rxjabber( uint64_t *reg_val );
uint64_t set_fld_chmode0__chmode__rxjabber( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_chmode0__chmode__disfcs( uint64_t *reg_val );
uint64_t set_fld_chmode0__chmode__disfcs( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_chmode0__chmode__invfcs( uint64_t *reg_val );
uint64_t set_fld_chmode0__chmode__invfcs( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_chmode0__chmode__ignfcs( uint64_t *reg_val );
uint64_t set_fld_chmode0__chmode__ignfcs( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_chmode0__chmode__stripfcs( uint64_t *reg_val );
uint64_t set_fld_chmode0__chmode__stripfcs( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_chmode0__chmode__ifglen( uint64_t *reg_val );
uint64_t set_fld_chmode0__chmode__ifglen( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_chmode0__chmode__ifgpacing( uint64_t *reg_val );
uint64_t set_fld_chmode0__chmode__ifgpacing( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_maccfg0__maccfg__disfcsonerr( uint64_t *reg_val );
uint64_t set_fld_maccfg0__maccfg__disfcsonerr( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_maccfg0__maccfg__txfcen( uint64_t *reg_val );
uint64_t set_fld_maccfg0__maccfg__txfcen( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_maccfg0__maccfg__rxfcen( uint64_t *reg_val );
uint64_t set_fld_maccfg0__maccfg__rxfcen( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_maccfg0__maccfg__rxpfcen( uint64_t *reg_val );
uint64_t set_fld_maccfg0__maccfg__rxpfcen( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_maccfg0__maccfg__rxfctotx( uint64_t *reg_val );
uint64_t set_fld_maccfg0__maccfg__rxfctotx( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_maccfg0__maccfg__rxfilterfc( uint64_t *reg_val );
uint64_t set_fld_maccfg0__maccfg__rxfilterfc( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_maccfg0__maccfg__rxfilterpfc( uint64_t *reg_val );
uint64_t set_fld_maccfg0__maccfg__rxfilterpfc( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_maccfg0__maccfg__txpadrunt( uint64_t *reg_val );
uint64_t set_fld_maccfg0__maccfg__txpadrunt( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_maccfg0__maccfg__txwrthresh( uint64_t *reg_val );
uint64_t set_fld_maccfg0__maccfg__txwrthresh( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_maccfg0__maccfg__txrdthresh( uint64_t *reg_val );
uint64_t set_fld_maccfg0__maccfg__txrdthresh( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_maccfg0__maccfg__txlfault( uint64_t *reg_val );
uint64_t set_fld_maccfg0__maccfg__txlfault( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_maccfg0__maccfg__txrfault( uint64_t *reg_val );
uint64_t set_fld_maccfg0__maccfg__txrfault( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_maccfg0__maccfg__txidle( uint64_t *reg_val );
uint64_t set_fld_maccfg0__maccfg__txidle( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_maccfg0__maccfg__rxpadrunt( uint64_t *reg_val );
uint64_t set_fld_maccfg0__maccfg__rxpadrunt( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_maccfg0__maccfg__rxlfault( uint64_t *reg_val );
uint64_t set_fld_maccfg0__maccfg__rxlfault( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_maccfg0__maccfg__rxrfault( uint64_t *reg_val );
uint64_t set_fld_maccfg0__maccfg__rxrfault( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_maccfg0__maccfg__rxidle( uint64_t *reg_val );
uint64_t set_fld_maccfg0__maccfg__rxidle( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_maccfg0__maccfg__statsclr( uint64_t *reg_val );
uint64_t set_fld_maccfg0__maccfg__statsclr( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_maccfg0__maccfg__txignorerx( uint64_t *reg_val );
uint64_t set_fld_maccfg0__maccfg__txignorerx( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_maccfg0__maccfg__txpfcen( uint64_t *reg_val );
uint64_t set_fld_maccfg0__maccfg__txpfcen( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_chconfig120__chconfig12__txvlantag( uint64_t *reg_val );
uint64_t set_fld_chconfig120__chconfig12__txvlantag( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_chconfig30__chconfig3__ifgppm( uint64_t *reg_val );
uint64_t set_fld_chconfig30__chconfig3__ifgppm( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_chconfig30__chconfig3__rxmaxfrmsize( uint64_t *reg_val );
uint64_t set_fld_chconfig30__chconfig3__rxmaxfrmsize( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_chconfig30__chconfig3__txpreamble( uint64_t *reg_val );
uint64_t set_fld_chconfig30__chconfig3__txpreamble( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_chconfig30__chconfig3__txdrainonfault( uint64_t *reg_val );
uint64_t set_fld_chconfig30__chconfig3__txdrainonfault( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_chconfig30__chconfig3__rxpreamble( uint64_t *reg_val );
uint64_t set_fld_chconfig30__chconfig3__rxpreamble( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_chconfig30__chconfig3__rxerrmask( uint64_t *reg_val );
uint64_t set_fld_chconfig30__chconfig3__rxerrmask( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_chconfig40__chconfig4__macaddr( uint64_t *reg_val );
uint64_t set_fld_chconfig40__chconfig4__macaddr( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_chconfig40__chconfig4__pauseontime( uint64_t *reg_val );
uint64_t set_fld_chconfig40__chconfig4__pauseontime( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_chconfig50__chconfig5__pausedest( uint64_t *reg_val );
uint64_t set_fld_chconfig50__chconfig5__pausedest( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_chconfig50__chconfig5__pauserefresh( uint64_t *reg_val );
uint64_t set_fld_chconfig50__chconfig5__pauserefresh( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_chconfig310__chconfig31__macoverride( uint64_t *reg_val );
uint64_t set_fld_chconfig310__chconfig31__macoverride( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_chsts0__chsts__txclkpresentall( uint64_t *reg_val );
uint64_t get_fld_chsts0__chsts__rxclkpresentall( uint64_t *reg_val );
uint64_t get_fld_chsts0__chsts__rxsigokall( uint64_t *reg_val );
uint64_t get_fld_chsts0__chsts__blocklockall( uint64_t *reg_val );
uint64_t get_fld_chsts0__chsts__amlockall( uint64_t *reg_val );
uint64_t get_fld_chsts0__chsts__aligned( uint64_t *reg_val );
uint64_t get_fld_chsts0__chsts__nohiber( uint64_t *reg_val );
uint64_t get_fld_chsts0__chsts__nolocalfault( uint64_t *reg_val );
uint64_t get_fld_chsts0__chsts__noremotefault( uint64_t *reg_val );
uint64_t get_fld_chsts0__chsts__linkup( uint64_t *reg_val );
uint64_t get_fld_chsts0__chsts__hiser( uint64_t *reg_val );
uint64_t get_fld_chsts0__chsts__fecdegser( uint64_t *reg_val );
uint64_t get_fld_chsts0__chsts__rxamsf( uint64_t *reg_val );
uint64_t get_fld_chconfig80__chconfig8__vlantag1( uint64_t *reg_val );
uint64_t set_fld_chconfig80__chconfig8__vlantag1( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_chconfig80__chconfig8__vlantag2( uint64_t *reg_val );
uint64_t set_fld_chconfig80__chconfig8__vlantag2( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_chconfig80__chconfig8__vlantag3( uint64_t *reg_val );
uint64_t set_fld_chconfig80__chconfig8__vlantag3( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_chconfig80__chconfig8__maxvlancnt( uint64_t *reg_val );
uint64_t set_fld_chconfig80__chconfig8__maxvlancnt( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_chconfig80__chconfig8__usclkcnt( uint64_t *reg_val );
uint64_t set_fld_chconfig80__chconfig8__usclkcnt( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_appCfg0__appCfg0__afulltxinv( uint64_t *reg_val );
uint64_t set_fld_appCfg0__appCfg0__afulltxinv( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_appCfg0__appCfg0__afullrxinv( uint64_t *reg_val );
uint64_t set_fld_appCfg0__appCfg0__afullrxinv( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_appCfg0__appCfg0__bitend( uint64_t *reg_val );
uint64_t set_fld_appCfg0__appCfg0__bitend( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_appCfg0__appCfg0__bytend( uint64_t *reg_val );
uint64_t set_fld_appCfg0__appCfg0__bytend( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_appCfg0__appCfg0__statscor( uint64_t *reg_val );
uint64_t set_fld_appCfg0__appCfg0__statscor( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_test00__test0__txpltesten( uint64_t *reg_val );
uint64_t set_fld_test00__test0__txpltesten( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_test00__test0__txp0testen( uint64_t *reg_val );
uint64_t set_fld_test00__test0__txp0testen( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_test00__test0__txsitesten( uint64_t *reg_val );
uint64_t set_fld_test00__test0__txsitesten( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_test00__test0__txswtesten( uint64_t *reg_val );
uint64_t set_fld_test00__test0__txswtesten( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_test00__test0__rxpltesten( uint64_t *reg_val );
uint64_t set_fld_test00__test0__rxpltesten( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_test00__test0__rxp0testen( uint64_t *reg_val );
uint64_t set_fld_test00__test0__rxp0testen( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_test00__test0__rxsitesten( uint64_t *reg_val );
uint64_t set_fld_test00__test0__rxsitesten( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_test1__test1__seeda( uint64_t *reg_val );
uint64_t set_fld_test1__test1__seeda( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_test2__test2__seedb( uint64_t *reg_val );
uint64_t set_fld_test2__test2__seedb( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_sdcfg0__sdcfg__serdeslpbk( uint64_t *reg_val );
uint64_t set_fld_sdcfg0__sdcfg__serdeslpbk( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_sdcfg0__sdcfg__txremap( uint64_t *reg_val );
uint64_t set_fld_sdcfg0__sdcfg__txremap( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_sdcfg0__sdcfg__sigokoverride( uint64_t *reg_val );
uint64_t set_fld_sdcfg0__sdcfg__sigokoverride( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_sdcfg0__sdcfg__rxremap( uint64_t *reg_val );
uint64_t set_fld_sdcfg0__sdcfg__rxremap( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_sdcfg0__sdcfg__txinv( uint64_t *reg_val );
uint64_t set_fld_sdcfg0__sdcfg__txinv( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_sdcfg0__sdcfg__rxinv( uint64_t *reg_val );
uint64_t set_fld_sdcfg0__sdcfg__rxinv( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_sdcfg0__sdcfg__paceren( uint64_t *reg_val );
uint64_t set_fld_sdcfg0__sdcfg__paceren( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_sdcfg0__sdcfg__pacerdiv( uint64_t *reg_val );
uint64_t set_fld_sdcfg0__sdcfg__pacerdiv( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_sdcfg0__sdcfg__txprbssel( uint64_t *reg_val );
uint64_t set_fld_sdcfg0__sdcfg__txprbssel( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_sdcfg0__sdcfg__rxprbssel( uint64_t *reg_val );
uint64_t set_fld_sdcfg0__sdcfg__rxprbssel( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_sderrcfg0__sderrcfg__txerrperiod( uint64_t *reg_val );
uint64_t set_fld_sderrcfg0__sderrcfg__txerrperiod( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_sderrcfg0__sderrcfg__txerrburst( uint64_t *reg_val );
uint64_t set_fld_sderrcfg0__sderrcfg__txerrburst( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_sdsts0__sdsts__txclkpresent( uint64_t *reg_val );
uint64_t get_fld_sdsts0__sdsts__txclkrate( uint64_t *reg_val );
uint64_t get_fld_sdsts0__sdsts__rxclkpresent( uint64_t *reg_val );
uint64_t get_fld_sdsts0__sdsts__rxclkrate( uint64_t *reg_val );
uint64_t get_fld_sdsts0__sdsts__sigok( uint64_t *reg_val );
uint64_t get_fld_sdsts0__sdsts__rxprbserrcnt( uint64_t *reg_val );
uint64_t set_fld_sdsts0__sdsts__rxprbserrcnt( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_progam0__progam__am( uint64_t *reg_val );
uint64_t set_fld_progam0__progam__am( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_progam0__progam__bip( uint64_t *reg_val );
uint64_t set_fld_progam0__progam__bip( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_progam1__progam__am( uint64_t *reg_val );
uint64_t set_fld_progam1__progam__am( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_progam1__progam__bip( uint64_t *reg_val );
uint64_t set_fld_progam1__progam__bip( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_progam2__progam__am( uint64_t *reg_val );
uint64_t set_fld_progam2__progam__am( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_progam2__progam__bip( uint64_t *reg_val );
uint64_t set_fld_progam2__progam__bip( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_progam3__progam__am( uint64_t *reg_val );
uint64_t set_fld_progam3__progam__am( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_progam3__progam__bip( uint64_t *reg_val );
uint64_t set_fld_progam3__progam__bip( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_progam4__progam__am( uint64_t *reg_val );
uint64_t set_fld_progam4__progam__am( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_progam4__progam__bip( uint64_t *reg_val );
uint64_t set_fld_progam4__progam__bip( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_progam5__progam__am( uint64_t *reg_val );
uint64_t set_fld_progam5__progam__am( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_progam5__progam__bip( uint64_t *reg_val );
uint64_t set_fld_progam5__progam__bip( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_progam6__progam__am( uint64_t *reg_val );
uint64_t set_fld_progam6__progam__am( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_progam6__progam__bip( uint64_t *reg_val );
uint64_t set_fld_progam6__progam__bip( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_progam7__progam__am( uint64_t *reg_val );
uint64_t set_fld_progam7__progam__am( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_progam7__progam__bip( uint64_t *reg_val );
uint64_t set_fld_progam7__progam__bip( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_progam8__progam__am( uint64_t *reg_val );
uint64_t set_fld_progam8__progam__am( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_progam8__progam__bip( uint64_t *reg_val );
uint64_t set_fld_progam8__progam__bip( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_progam9__progam__am( uint64_t *reg_val );
uint64_t set_fld_progam9__progam__am( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_progam9__progam__bip( uint64_t *reg_val );
uint64_t set_fld_progam9__progam__bip( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_progamA__progam__am( uint64_t *reg_val );
uint64_t set_fld_progamA__progam__am( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_progamA__progam__bip( uint64_t *reg_val );
uint64_t set_fld_progamA__progam__bip( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_progamB__progam__am( uint64_t *reg_val );
uint64_t set_fld_progamB__progam__am( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_progamB__progam__bip( uint64_t *reg_val );
uint64_t set_fld_progamB__progam__bip( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_progamC__progam__am( uint64_t *reg_val );
uint64_t set_fld_progamC__progam__am( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_progamC__progam__bip( uint64_t *reg_val );
uint64_t set_fld_progamC__progam__bip( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_progamD__progam__am( uint64_t *reg_val );
uint64_t set_fld_progamD__progam__am( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_progamD__progam__bip( uint64_t *reg_val );
uint64_t set_fld_progamD__progam__bip( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_progamE__progam__am( uint64_t *reg_val );
uint64_t set_fld_progamE__progam__am( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_progamE__progam__bip( uint64_t *reg_val );
uint64_t set_fld_progamE__progam__bip( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_progamF__progam__am( uint64_t *reg_val );
uint64_t set_fld_progamF__progam__am( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_progamF__progam__bip( uint64_t *reg_val );
uint64_t set_fld_progamF__progam__bip( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_progam10__progam__am( uint64_t *reg_val );
uint64_t set_fld_progam10__progam__am( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_progam10__progam__bip( uint64_t *reg_val );
uint64_t set_fld_progam10__progam__bip( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_progam11__progam__am( uint64_t *reg_val );
uint64_t set_fld_progam11__progam__am( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_progam11__progam__bip( uint64_t *reg_val );
uint64_t set_fld_progam11__progam__bip( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_progam12__progam__am( uint64_t *reg_val );
uint64_t set_fld_progam12__progam__am( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_progam12__progam__bip( uint64_t *reg_val );
uint64_t set_fld_progam12__progam__bip( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_progam13__progam__am( uint64_t *reg_val );
uint64_t set_fld_progam13__progam__am( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_progam13__progam__bip( uint64_t *reg_val );
uint64_t set_fld_progam13__progam__bip( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_progam14__progam__bip( uint64_t *reg_val );
uint64_t set_fld_progam14__progam__bip( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_progam15__progam__bip( uint64_t *reg_val );
uint64_t set_fld_progam15__progam__bip( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_progam16__progam__bip( uint64_t *reg_val );
uint64_t set_fld_progam16__progam__bip( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_progam17__progam__bip( uint64_t *reg_val );
uint64_t set_fld_progam17__progam__bip( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_progam18__progam__bip( uint64_t *reg_val );
uint64_t set_fld_progam18__progam__bip( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_progam19__progam__bip( uint64_t *reg_val );
uint64_t set_fld_progam19__progam__bip( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_progam1A__progam__bip( uint64_t *reg_val );
uint64_t set_fld_progam1A__progam__bip( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_progam1B__progam__bip( uint64_t *reg_val );
uint64_t set_fld_progam1B__progam__bip( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_progam1C__progam__bip( uint64_t *reg_val );
uint64_t set_fld_progam1C__progam__bip( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_progam1D__progam__bip( uint64_t *reg_val );
uint64_t set_fld_progam1D__progam__bip( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_progam1E__progam__bip( uint64_t *reg_val );
uint64_t set_fld_progam1E__progam__bip( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_progam1F__progam__bip( uint64_t *reg_val );
uint64_t set_fld_progam1F__progam__bip( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_chconfig60__chconfig6__corrbyp( uint64_t *reg_val );
uint64_t set_fld_chconfig60__chconfig6__corrbyp( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_chconfig60__chconfig6__indibyp( uint64_t *reg_val );
uint64_t set_fld_chconfig60__chconfig6__indibyp( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_chconfig60__chconfig6__hiserthresh( uint64_t *reg_val );
uint64_t set_fld_chconfig60__chconfig6__hiserthresh( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_chconfig60__chconfig6__degserenable( uint64_t *reg_val );
uint64_t set_fld_chconfig60__chconfig6__degserenable( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_chconfig60__chconfig6__degserinterval( uint64_t *reg_val );
uint64_t set_fld_chconfig60__chconfig6__degserinterval( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_chconfig70__chconfig7__degseractivatethresh( uint64_t *reg_val );
uint64_t set_fld_chconfig70__chconfig7__degseractivatethresh( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_chconfig70__chconfig7__degserdeactivatethresh( uint64_t *reg_val );
uint64_t set_fld_chconfig70__chconfig7__degserdeactivatethresh( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_pcsrxoverride00__pcsrxoverride0__rxoverride0( uint64_t *reg_val );
uint64_t set_fld_pcsrxoverride00__pcsrxoverride0__rxoverride0( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_pcsrxoverride01__pcsrxoverride1__rxoverride1( uint64_t *reg_val );
uint64_t set_fld_pcsrxoverride01__pcsrxoverride1__rxoverride1( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_pcsrxoverride02__pcsrxoverride2__rxoverride2( uint64_t *reg_val );
uint64_t set_fld_pcsrxoverride02__pcsrxoverride2__rxoverride2( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_pcslcfg0__pcslcfg__amlock( uint64_t *reg_val );
uint64_t get_fld_pcslcfg0__pcslcfg__blocklock( uint64_t *reg_val );
uint64_t get_fld_pcslcfg0__pcslcfg__mapping( uint64_t *reg_val );
uint64_t get_fld_pcslcfg0__pcslcfg__amperiod( uint64_t *reg_val );
uint64_t get_fld_chconfig130__chconfig13__txtsoffset( uint64_t *reg_val );
uint64_t set_fld_chconfig130__chconfig13__txtsoffset( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_version__version__version( uint64_t *reg_val );
uint64_t set_fld_version__version__version( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_intcontrol0__intcontrol__intsts( uint64_t *reg_val );
uint64_t set_fld_intcontrol0__intcontrol__intsts( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_intcontrol0__intcontrol__intclr( uint64_t *reg_val );
uint64_t set_fld_intcontrol0__intcontrol__intclr( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_intcontrol0__intcontrol__intena( uint64_t *reg_val );
uint64_t set_fld_intcontrol0__intcontrol__intena( uint64_t *reg_val, uint64_t fld_val );
uint64_t get_fld_intcontrol0__intcontrol__intraw( uint64_t *reg_val );
