#!/bin/bash
#Load bf_kpkt kernel module

if [ $# -eq 0 ];
  then
    echo "Usage: $(basename ""$0"") <install_dir>"
    exit 1
fi

INSTALL_DIR=$1
insmod $INSTALL_DIR/lib/modules/bf_kpkt.ko intr_mode="msi" kpkt_mode=1
