/*******************************************************************************
 *  Copyright (C) 2024 Intel Corporation
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions
 *  and limitations under the License.
 *
 *
 *  SPDX-License-Identifier: Apache-2.0
 ******************************************************************************/

// generated by split_classes.pl
#ifndef __REGISTER_INCLUDES_DPRSR_OUT_MIRROR_WRR_VEC_R_MUTABLE_H__
#define __REGISTER_INCLUDES_DPRSR_OUT_MIRROR_WRR_VEC_R_MUTABLE_H__


#include <cstdint>
#include <cassert>
#include <array>
#include <vector>
#include <string>
#include <boost/lexical_cast.hpp>
#include <boost/format.hpp>
#include <model_core/register_block.h>
#include <shared/bitvector.h>












namespace tofino {
  namespace register_classes {

class DprsrOutMirrorWrrVecRMutable : public model_core::RegisterBlock<RegisterCallback> {
public:
  DprsrOutMirrorWrrVecRMutable(
      int chipNumber, int index_pipe_addrmap, RegisterCallback& write_callback = 0, RegisterCallback& read_callback = 0
  )
    : RegisterBlock(chipNumber, StartOffset(index_pipe_addrmap), 4, true, write_callback, read_callback, std::string("DprsrOutMirrorWrrVecRMutable")+":"+boost::lexical_cast<std::string>(index_pipe_addrmap))
    {
    }
  DprsrOutMirrorWrrVecRMutable(
      
  )
    : RegisterBlock(0, 0, 0, true, 0, 0, "DprsrOutMirrorWrrVecRMutable")
    {
    }
public:
  uint32_t vec() { return vec_; }
  void vec(const uint32_t &v) { vec_=v; }

  bool read(
      uint32_t offset, uint32_t* data
      ) const {
    if (read_callback_) read_callback_();
    *data = vec_;
    return true;
  }


  bool write(
      uint32_t offset, uint32_t data
      ) {
    vec_ = data;
    if (write_callback_) write_callback_();
    return true;
  }

  void reset(
      
      ) {
    vec_ = 0x0;
    if (write_callback_) write_callback_();
  }

  std::string to_string(
      uint32_t offset, bool print_zeros = false, std::string indent_string = ""
      ) const {
    std::string r("");
    bool all_zeros=true;
    r += indent_string + std::string("DprsrOutMirrorWrrVecRMutable") + ":\n";
    r += indent_string + "  " + std::string("vec") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(vec_) ) + "\n";
    all_zeros &= (0 == vec_);
    if (all_zeros && !print_zeros) {
      return("");
    }
    else {
      return r;
    }
  }

  std::string to_string(
      bool print_zeros = false, std::string indent_string = ""
      ) const {
    std::string r("");
    bool all_zeros=true;
    r += indent_string + std::string("DprsrOutMirrorWrrVecRMutable") + ":\n";
    r += indent_string + "  " + std::string("vec") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(vec_) ) + "\n";
    all_zeros &= (0 == vec_);
    if (all_zeros && !print_zeros) {
      return("");
    }
    else {
      return r;
    }
  }

private:
  uint32_t vec_;
private:
  static int StartOffset(
      int index_pipe_addrmap
      ) {
    int offset=0;
    offset += 0x2000000; // to get to pipes
    assert(index_pipe_addrmap < 4);
    offset += index_pipe_addrmap * 0x800000; // pipe_addrmap[]
    offset += 0x780000; // to get to deparser
    offset += 0x10000; // to get to out_ingr
    offset += 0xc; // to get to mirror_wrr
    return offset;
  }

};











  }; // namespace register_classes
}; // namespace tofino

#endif // __REGISTER_INCLUDES_DPRSR_OUT_MIRROR_WRR_VEC_R_MUTABLE_H__
