/*******************************************************************************
 *  Copyright (C) 2024 Intel Corporation
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions
 *  and limitations under the License.
 *
 *
 *  SPDX-License-Identifier: Apache-2.0
 ******************************************************************************/

// generated by split_classes.pl
#ifndef __REGISTER_INCLUDES_GPIO_COMMON_REGS_SHLD_CTRL_H__
#define __REGISTER_INCLUDES_GPIO_COMMON_REGS_SHLD_CTRL_H__


#include <cstdint>
#include <cassert>
#include <array>
#include <vector>
#include <string>
#include <boost/lexical_cast.hpp>
#include <boost/format.hpp>
#include <model_core/register_block.h>
#include <shared/bitvector.h>












namespace tofino {
  namespace register_classes {

class GpioCommonRegsShldCtrl : public model_core::RegisterBlock<RegisterCallback> {
public:
  enum TofinoEnum {
    kEthgpiobr,
    kEthgpiotl
  };
public:
  GpioCommonRegsShldCtrl(
      int chipNumber, TofinoEnum selector_tofino, RegisterCallback& write_callback = 0, RegisterCallback& read_callback = 0
  )
    : RegisterBlock(chipNumber, StartOffset(selector_tofino), 4, false, write_callback, read_callback, std::string("GpioCommonRegsShldCtrl")+":"+boost::lexical_cast<std::string>(selector_tofino))
    {
    }
  GpioCommonRegsShldCtrl(
      
  )
    : RegisterBlock(0, 0, 0, false, 0, 0, "GpioCommonRegsShldCtrl")
    {
    }
public:





  uint8_t &shld_en() { return shld_en_; }





  uint8_t &shld_sel() { return shld_sel_; }

  bool read(
      uint32_t offset, uint32_t* data
      ) const {
    if (read_callback_) read_callback_();
    *data = (shld_en_ & 0x1);
    *data |= ((shld_sel_ & 0x1) << 1);
    return true;
  }


  bool write(
      uint32_t offset, uint32_t data
      ) {
    shld_en_ = (data & 0x1);
    shld_sel_ = ((data >> 1) & 0x1);
    if (write_callback_) write_callback_();
    return true;
  }

  void reset(
      
      ) {
    shld_en_ = 0x0;
    shld_sel_ = 0x0;
    if (write_callback_) write_callback_();
  }

  std::string to_string(
      uint32_t offset, bool print_zeros = false, std::string indent_string = ""
      ) const {
    std::string r("");
    bool all_zeros=true;
    r += indent_string + std::string("GpioCommonRegsShldCtrl") + ":\n";
    r += indent_string + "  " + std::string("shld_en") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(shld_en_) ) + "\n";
    all_zeros &= (0 == shld_en_);
    r += indent_string + "  " + std::string("shld_sel") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(shld_sel_) ) + "\n";
    all_zeros &= (0 == shld_sel_);
    if (all_zeros && !print_zeros) {
      return("");
    }
    else {
      return r;
    }
  }

  std::string to_string(
      bool print_zeros = false, std::string indent_string = ""
      ) const {
    std::string r("");
    bool all_zeros=true;
    r += indent_string + std::string("GpioCommonRegsShldCtrl") + ":\n";
    r += indent_string + "  " + std::string("shld_en") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(shld_en_) ) + "\n";
    all_zeros &= (0 == shld_en_);
    r += indent_string + "  " + std::string("shld_sel") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(shld_sel_) ) + "\n";
    all_zeros &= (0 == shld_sel_);
    if (all_zeros && !print_zeros) {
      return("");
    }
    else {
      return r;
    }
  }

private:
  uint8_t shld_en_;
  uint8_t shld_sel_;
private:
  static int StartOffset(
      TofinoEnum selector_tofino
      ) {
    int offset=0;
    switch (selector_tofino) {
      case kEthgpiobr:
        offset += 0x1820000; // to get to ethgpiobr
        offset += 0x200; // to get to gpio_common_regs
        offset += 0x154; // to get to shld_ctrl
        break;
      case kEthgpiotl:
        offset += 0x1840000; // to get to ethgpiotl
        offset += 0x200; // to get to gpio_common_regs
        offset += 0x154; // to get to shld_ctrl
        break;
      default:
        assert(0);
        break;
    }
    return offset;
  }

};









  }; // namespace register_classes
}; // namespace tofino

#endif // __REGISTER_INCLUDES_GPIO_COMMON_REGS_SHLD_CTRL_H__
