/*******************************************************************************
 *  Copyright (C) 2024 Intel Corporation
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions
 *  and limitations under the License.
 *
 *
 *  SPDX-License-Identifier: Apache-2.0
 ******************************************************************************/

// generated by split_classes.pl
#ifndef __REGISTER_INCLUDES_MAU_SELECTOR_ALU_ADDRMAP_H__
#define __REGISTER_INCLUDES_MAU_SELECTOR_ALU_ADDRMAP_H__


#include <cstdint>
#include <cassert>
#include <array>
#include <vector>
#include <string>
#include <boost/lexical_cast.hpp>
#include <boost/format.hpp>
#include <model_core/register_block.h>
#include <shared/bitvector.h>











#include "intr_enable0_mau_selector_alu.h"
#include "intr_enable1_mau_selector_alu.h"
#include "intr_inject_mau_selector_alu.h"
#include "intr_status_mau_selector_alu.h"
#include "mau_selector_alu_errlog.h"
#include "selector_alu_ctl.h"

namespace tofino {
  namespace register_classes {

class MauSelectorAluAddrmap : public model_core::RegisterBlock<RegisterCallback> {
public:
  MauSelectorAluAddrmap(
      int chipNumber, int index_pipe_addrmap, int index_mau_addrmap, int index_mau_meter_alu_group_addrmap, RegisterCallback& write_callback = 0, RegisterCallback& read_callback = 0
  )
    : RegisterBlock(chipNumber, StartOffset(index_pipe_addrmap, index_mau_addrmap, index_mau_meter_alu_group_addrmap), 32, false, write_callback, read_callback, std::string("MauSelectorAluAddrmap")+":"+boost::lexical_cast<std::string>(index_pipe_addrmap) + "," + boost::lexical_cast<std::string>(index_mau_addrmap) + "," + boost::lexical_cast<std::string>(index_mau_meter_alu_group_addrmap))
    {
    }
  MauSelectorAluAddrmap(
      
  )
    : RegisterBlock(0, 0, 0, false, 0, 0, "MauSelectorAluAddrmap")
    {
    }
public:







  IntrInjectMauSelectorAlu &intr_inject_mau_selector_alu() { return intr_inject_mau_selector_alu_; }





  MauSelectorAluErrlog &mau_selector_alu_errlog() { return mau_selector_alu_errlog_; }





  SelectorAluCtl &selector_alu_ctl() { return selector_alu_ctl_; }






  IntrStatusMauSelectorAlu &intr_status_mau_selector_alu() { return intr_status_mau_selector_alu_; }






  IntrEnable0MauSelectorAlu &intr_enable0_mau_selector_alu() { return intr_enable0_mau_selector_alu_; }






  IntrEnable1MauSelectorAlu &intr_enable1_mau_selector_alu() { return intr_enable1_mau_selector_alu_; }

  bool read(
      uint32_t offset, uint32_t* data
      ) const {
    if (offset < 0x4) {
      offset -= 0x0;
      if (read_callback_) read_callback_();
      intr_inject_mau_selector_alu_.read( offset, data );
    }
    else if (offset >= 0x4 && offset < 0x8) {
      offset -= 0x4;
      if (read_callback_) read_callback_();
      mau_selector_alu_errlog_.read( offset, data );
    }
    else if (offset >= 0x10 && offset < 0x14) {
      offset -= 0x10;
      if (read_callback_) read_callback_();
      selector_alu_ctl_.read( offset, data );
    }
    else if (offset >= 0x14 && offset < 0x18) {
      offset -= 0x14;
      if (read_callback_) read_callback_();
      intr_status_mau_selector_alu_.read( offset, data );
    }
    else if (offset >= 0x18 && offset < 0x1c) {
      offset -= 0x18;
      if (read_callback_) read_callback_();
      intr_enable0_mau_selector_alu_.read( offset, data );
    }
    else if (offset >= 0x1c && offset < 0x20) {
      offset -= 0x1c;
      if (read_callback_) read_callback_();
      intr_enable1_mau_selector_alu_.read( offset, data );
    }
    return true;
  }


  bool write(
      uint32_t offset, uint32_t data
      ) {
    if (offset < 0x4) {
      offset -= 0x0;
      intr_inject_mau_selector_alu_.write( offset, data );
      if (write_callback_) write_callback_();
    }
    else if (offset >= 0x4 && offset < 0x8) {
      offset -= 0x4;
      mau_selector_alu_errlog_.write( offset, data );
      if (write_callback_) write_callback_();
    }
    else if (offset >= 0x10 && offset < 0x14) {
      offset -= 0x10;
      selector_alu_ctl_.write( offset, data );
      if (write_callback_) write_callback_();
    }
    else if (offset >= 0x14 && offset < 0x18) {
      offset -= 0x14;
      intr_status_mau_selector_alu_.write( offset, data );
      if (write_callback_) write_callback_();
    }
    else if (offset >= 0x18 && offset < 0x1c) {
      offset -= 0x18;
      intr_enable0_mau_selector_alu_.write( offset, data );
      if (write_callback_) write_callback_();
    }
    else if (offset >= 0x1c && offset < 0x20) {
      offset -= 0x1c;
      intr_enable1_mau_selector_alu_.write( offset, data );
      if (write_callback_) write_callback_();
    }
    return true;
  }

  void reset(
      
      ) {
    intr_inject_mau_selector_alu_.reset();
    mau_selector_alu_errlog_.reset();
    selector_alu_ctl_.reset();
    intr_status_mau_selector_alu_.reset();
    intr_enable0_mau_selector_alu_.reset();
    intr_enable1_mau_selector_alu_.reset();
    if (write_callback_) write_callback_();
  }

  std::string to_string(
      uint32_t offset, bool print_zeros = false, std::string indent_string = ""
      ) const {
    std::string r("");
    bool all_zeros=true;
    all_zeros=false;
    if (offset < 0x4) {
      offset -= 0x0;
      r += intr_inject_mau_selector_alu_.to_string(offset,print_zeros,indent_string) ;
    }
    else if (offset >= 0x4 && offset < 0x8) {
      offset -= 0x4;
      r += mau_selector_alu_errlog_.to_string(offset,print_zeros,indent_string) ;
    }
    else if (offset >= 0x10 && offset < 0x14) {
      offset -= 0x10;
      r += selector_alu_ctl_.to_string(offset,print_zeros,indent_string) ;
    }
    else if (offset >= 0x14 && offset < 0x18) {
      offset -= 0x14;
      r += intr_status_mau_selector_alu_.to_string(offset,print_zeros,indent_string) ;
    }
    else if (offset >= 0x18 && offset < 0x1c) {
      offset -= 0x18;
      r += intr_enable0_mau_selector_alu_.to_string(offset,print_zeros,indent_string) ;
    }
    else if (offset >= 0x1c && offset < 0x20) {
      offset -= 0x1c;
      r += intr_enable1_mau_selector_alu_.to_string(offset,print_zeros,indent_string) ;
    }
    if (all_zeros && !print_zeros) {
      return("");
    }
    else {
      return r;
    }
  }

  std::string to_string(
      bool print_zeros = false, std::string indent_string = ""
      ) const {
    std::string r("");
    bool all_zeros=true;
    all_zeros=false;
    r += intr_inject_mau_selector_alu_.to_string(print_zeros,indent_string) ;
    r += mau_selector_alu_errlog_.to_string(print_zeros,indent_string) ;
    r += selector_alu_ctl_.to_string(print_zeros,indent_string) ;
    r += intr_status_mau_selector_alu_.to_string(print_zeros,indent_string) ;
    r += intr_enable0_mau_selector_alu_.to_string(print_zeros,indent_string) ;
    r += intr_enable1_mau_selector_alu_.to_string(print_zeros,indent_string) ;
    if (all_zeros && !print_zeros) {
      return("");
    }
    else {
      return r;
    }
  }

private:
  IntrInjectMauSelectorAlu intr_inject_mau_selector_alu_;
  MauSelectorAluErrlog mau_selector_alu_errlog_;
  SelectorAluCtl selector_alu_ctl_;
  IntrStatusMauSelectorAlu intr_status_mau_selector_alu_;
  IntrEnable0MauSelectorAlu intr_enable0_mau_selector_alu_;
  IntrEnable1MauSelectorAlu intr_enable1_mau_selector_alu_;
private:
  static int StartOffset(
      int index_pipe_addrmap, int index_mau_addrmap, int index_mau_meter_alu_group_addrmap
      ) {
    int offset=0;
    offset += 0x2000000; // to get to pipes
    assert(index_pipe_addrmap < 4);
    offset += index_pipe_addrmap * 0x800000; // pipe_addrmap[]
    assert(index_mau_addrmap < 12);
    offset += index_mau_addrmap * 0x80000; // mau_addrmap[]
    offset += 0x10000; // to get to map_alu
    offset += 0x800; // to get to meter_group
    assert(index_mau_meter_alu_group_addrmap < 4);
    offset += index_mau_meter_alu_group_addrmap * 0x200; // mau_meter_alu_group_addrmap[]
    offset += 0x20; // to get to selector
    return offset;
  }

};









  }; // namespace register_classes
}; // namespace tofino

#endif // __REGISTER_INCLUDES_MAU_SELECTOR_ALU_ADDRMAP_H__
