/*******************************************************************************
 *  Copyright (C) 2024 Intel Corporation
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions
 *  and limitations under the License.
 *
 *
 *  SPDX-License-Identifier: Apache-2.0
 ******************************************************************************/

// generated by split_classes.pl
#ifndef __REGISTER_INCLUDES_MISC_REGS_PCIE_RESET_TRIG_MUTABLE_H__
#define __REGISTER_INCLUDES_MISC_REGS_PCIE_RESET_TRIG_MUTABLE_H__


#include <cstdint>
#include <cassert>
#include <array>
#include <vector>
#include <string>
#include <boost/lexical_cast.hpp>
#include <boost/format.hpp>
#include <model_core/register_block.h>
#include <shared/bitvector.h>












namespace tofino {
  namespace register_classes {

class MiscRegsPcieResetTrigMutable : public model_core::RegisterBlock<RegisterCallback> {
public:
  MiscRegsPcieResetTrigMutable(
      int chipNumber, RegisterCallback& write_callback = 0, RegisterCallback& read_callback = 0
  )
    : RegisterBlock(chipNumber, StartOffset(), 4, true, write_callback, read_callback, std::string("MiscRegsPcieResetTrigMutable"))
    {
    }
  MiscRegsPcieResetTrigMutable(
      
  )
    : RegisterBlock(0, 0, 0, true, 0, 0, "MiscRegsPcieResetTrigMutable")
    {
    }
public:





  uint16_t pcie_reset_delay() { return pcie_reset_delay_; }
  void pcie_reset_delay(const uint16_t &v) { pcie_reset_delay_=v; }






  uint8_t pcie_reset_trig() { return pcie_reset_trig_; }
  void pcie_reset_trig(const uint8_t &v) { pcie_reset_trig_=v; }

  bool read(
      uint32_t offset, uint32_t* data
      ) const {
    if (read_callback_) read_callback_();
    *data = pcie_reset_delay_;
    *data |= ((pcie_reset_trig_ & 0x1) << 16);
    return true;
  }


  bool write(
      uint32_t offset, uint32_t data
      ) {
    pcie_reset_delay_ = data;
    pcie_reset_trig_ = ((data >> 16) & 0x1);
    if (write_callback_) write_callback_();
    return true;
  }

  void reset(
      
      ) {
    pcie_reset_delay_ = 0x400;
    pcie_reset_trig_ = 0x0;
    if (write_callback_) write_callback_();
  }

  std::string to_string(
      uint32_t offset, bool print_zeros = false, std::string indent_string = ""
      ) const {
    std::string r("");
    bool all_zeros=true;
    r += indent_string + std::string("MiscRegsPcieResetTrigMutable") + ":\n";
    r += indent_string + "  " + std::string("pcie_reset_delay") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(pcie_reset_delay_) ) + "\n";
    all_zeros &= (0 == pcie_reset_delay_);
    r += indent_string + "  " + std::string("pcie_reset_trig") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(pcie_reset_trig_) ) + "\n";
    all_zeros &= (0 == pcie_reset_trig_);
    if (all_zeros && !print_zeros) {
      return("");
    }
    else {
      return r;
    }
  }

  std::string to_string(
      bool print_zeros = false, std::string indent_string = ""
      ) const {
    std::string r("");
    bool all_zeros=true;
    r += indent_string + std::string("MiscRegsPcieResetTrigMutable") + ":\n";
    r += indent_string + "  " + std::string("pcie_reset_delay") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(pcie_reset_delay_) ) + "\n";
    all_zeros &= (0 == pcie_reset_delay_);
    r += indent_string + "  " + std::string("pcie_reset_trig") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(pcie_reset_trig_) ) + "\n";
    all_zeros &= (0 == pcie_reset_trig_);
    if (all_zeros && !print_zeros) {
      return("");
    }
    else {
      return r;
    }
  }

private:
  uint16_t pcie_reset_delay_;
  uint8_t pcie_reset_trig_;
private:
  static int StartOffset(
      
      ) {
    int offset=0;
    offset += 0x40000; // to get to misc_regs
    offset += 0xf0; // to get to pcie_reset_trig
    return offset;
  }

};









  }; // namespace register_classes
}; // namespace tofino

#endif // __REGISTER_INCLUDES_MISC_REGS_PCIE_RESET_TRIG_MUTABLE_H__
