/*******************************************************************************
 *  Copyright (C) 2024 Intel Corporation
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions
 *  and limitations under the License.
 *
 *
 *  SPDX-License-Identifier: Apache-2.0
 ******************************************************************************/

// generated by split_classes.pl
#ifndef __REGISTER_INCLUDES_MOVEREG_METER_CTL_MUTABLE_H__
#define __REGISTER_INCLUDES_MOVEREG_METER_CTL_MUTABLE_H__


#include <cstdint>
#include <cassert>
#include <array>
#include <vector>
#include <string>
#include <boost/lexical_cast.hpp>
#include <boost/format.hpp>
#include <model_core/register_block.h>
#include <shared/bitvector.h>












namespace tofino {
  namespace register_classes {

class MoveregMeterCtlMutable : public model_core::RegisterBlock<RegisterCallback> {
public:
  MoveregMeterCtlMutable(
      int chipNumber, int index_pipe_addrmap, int index_mau_addrmap, int index_movereg_meter_ctl, RegisterCallback& write_callback = 0, RegisterCallback& read_callback = 0
  )
    : RegisterBlock(chipNumber, StartOffset(index_pipe_addrmap, index_mau_addrmap, index_movereg_meter_ctl), 4, true, write_callback, read_callback, std::string("MoveregMeterCtlMutable")+":"+boost::lexical_cast<std::string>(index_pipe_addrmap) + "," + boost::lexical_cast<std::string>(index_mau_addrmap) + "," + boost::lexical_cast<std::string>(index_movereg_meter_ctl))
    {
    }
  MoveregMeterCtlMutable(
      
  )
    : RegisterBlock(0, 0, 0, true, 0, 0, "MoveregMeterCtlMutable")
    {
    }
public:


  uint8_t movereg_meter_ctl_deferred() { return movereg_meter_ctl_deferred_; }
  void movereg_meter_ctl_deferred(const uint8_t &v) { movereg_meter_ctl_deferred_=v; }


  uint8_t movereg_meter_ctl_direct() { return movereg_meter_ctl_direct_; }
  void movereg_meter_ctl_direct(const uint8_t &v) { movereg_meter_ctl_direct_=v; }







  uint8_t movereg_ad_meter_shift() { return movereg_ad_meter_shift_; }
  void movereg_ad_meter_shift(const uint8_t &v) { movereg_ad_meter_shift_=v; }


  uint8_t movereg_meter_ctl_lt() { return movereg_meter_ctl_lt_; }
  void movereg_meter_ctl_lt(const uint8_t &v) { movereg_meter_ctl_lt_=v; }


  uint8_t movereg_meter_ctl_color_en() { return movereg_meter_ctl_color_en_; }
  void movereg_meter_ctl_color_en(const uint8_t &v) { movereg_meter_ctl_color_en_=v; }

  bool read(
      uint32_t offset, uint32_t* data
      ) const {
    if (read_callback_) read_callback_();
    *data = (movereg_meter_ctl_deferred_ & 0x1);
    *data |= ((movereg_meter_ctl_direct_ & 0x1) << 1);
    *data |= ((movereg_ad_meter_shift_ & 0x7) << 2);
    *data |= ((movereg_meter_ctl_lt_ & 0xf) << 5);
    *data |= ((movereg_meter_ctl_color_en_ & 0x1) << 9);
    return true;
  }


  bool write(
      uint32_t offset, uint32_t data
      ) {
    movereg_meter_ctl_deferred_ = (data & 0x1);
    movereg_meter_ctl_direct_ = ((data >> 1) & 0x1);
    movereg_ad_meter_shift_ = ((data >> 2) & 0x7);
    movereg_meter_ctl_lt_ = ((data >> 5) & 0xf);
    movereg_meter_ctl_color_en_ = ((data >> 9) & 0x1);
    if (write_callback_) write_callback_();
    return true;
  }

  void reset(
      
      ) {
    movereg_meter_ctl_deferred_ = 0x0;
    movereg_meter_ctl_direct_ = 0x0;
    movereg_ad_meter_shift_ = 0x0;
    movereg_meter_ctl_lt_ = 0x0;
    movereg_meter_ctl_color_en_ = 0x0;
    if (write_callback_) write_callback_();
  }

  std::string to_string(
      uint32_t offset, bool print_zeros = false, std::string indent_string = ""
      ) const {
    std::string r("");
    bool all_zeros=true;
    r += indent_string + std::string("MoveregMeterCtlMutable") + ":\n";
    r += indent_string + "  " + std::string("movereg_meter_ctl_deferred") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(movereg_meter_ctl_deferred_) ) + "\n";
    all_zeros &= (0 == movereg_meter_ctl_deferred_);
    r += indent_string + "  " + std::string("movereg_meter_ctl_direct") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(movereg_meter_ctl_direct_) ) + "\n";
    all_zeros &= (0 == movereg_meter_ctl_direct_);
    r += indent_string + "  " + std::string("movereg_ad_meter_shift") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(movereg_ad_meter_shift_) ) + "\n";
    all_zeros &= (0 == movereg_ad_meter_shift_);
    r += indent_string + "  " + std::string("movereg_meter_ctl_lt") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(movereg_meter_ctl_lt_) ) + "\n";
    all_zeros &= (0 == movereg_meter_ctl_lt_);
    r += indent_string + "  " + std::string("movereg_meter_ctl_color_en") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(movereg_meter_ctl_color_en_) ) + "\n";
    all_zeros &= (0 == movereg_meter_ctl_color_en_);
    if (all_zeros && !print_zeros) {
      return("");
    }
    else {
      return r;
    }
  }

  std::string to_string(
      bool print_zeros = false, std::string indent_string = ""
      ) const {
    std::string r("");
    bool all_zeros=true;
    r += indent_string + std::string("MoveregMeterCtlMutable") + ":\n";
    r += indent_string + "  " + std::string("movereg_meter_ctl_deferred") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(movereg_meter_ctl_deferred_) ) + "\n";
    all_zeros &= (0 == movereg_meter_ctl_deferred_);
    r += indent_string + "  " + std::string("movereg_meter_ctl_direct") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(movereg_meter_ctl_direct_) ) + "\n";
    all_zeros &= (0 == movereg_meter_ctl_direct_);
    r += indent_string + "  " + std::string("movereg_ad_meter_shift") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(movereg_ad_meter_shift_) ) + "\n";
    all_zeros &= (0 == movereg_ad_meter_shift_);
    r += indent_string + "  " + std::string("movereg_meter_ctl_lt") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(movereg_meter_ctl_lt_) ) + "\n";
    all_zeros &= (0 == movereg_meter_ctl_lt_);
    r += indent_string + "  " + std::string("movereg_meter_ctl_color_en") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(movereg_meter_ctl_color_en_) ) + "\n";
    all_zeros &= (0 == movereg_meter_ctl_color_en_);
    if (all_zeros && !print_zeros) {
      return("");
    }
    else {
      return r;
    }
  }

private:
  uint8_t movereg_meter_ctl_deferred_;
  uint8_t movereg_meter_ctl_direct_;
  uint8_t movereg_ad_meter_shift_;
  uint8_t movereg_meter_ctl_lt_;
  uint8_t movereg_meter_ctl_color_en_;
private:
  static int StartOffset(
      int index_pipe_addrmap, int index_mau_addrmap, int index_movereg_meter_ctl
      ) {
    int offset=0;
    offset += 0x2000000; // to get to pipes
    assert(index_pipe_addrmap < 4);
    offset += index_pipe_addrmap * 0x800000; // pipe_addrmap[]
    assert(index_mau_addrmap < 12);
    offset += index_mau_addrmap * 0x80000; // mau_addrmap[]
    offset += 0x18000; // to get to match
    offset += 0x160; // to get to movereg_meter_ctl
    assert(index_movereg_meter_ctl < 4);
    offset += index_movereg_meter_ctl * 0x4; // movereg_meter_ctl[]
    return offset;
  }

};










  }; // namespace register_classes
}; // namespace tofino

#endif // __REGISTER_INCLUDES_MOVEREG_METER_CTL_MUTABLE_H__
