/*******************************************************************************
 *  Copyright (C) 2024 Intel Corporation
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions
 *  and limitations under the License.
 *
 *
 *  SPDX-License-Identifier: Apache-2.0
 ******************************************************************************/

// generated by split_classes.pl
#ifndef __REGISTER_INCLUDES_PGR_APP_EVENT_JITTER_VALUE_MUTABLE_H__
#define __REGISTER_INCLUDES_PGR_APP_EVENT_JITTER_VALUE_MUTABLE_H__


#include <cstdint>
#include <cassert>
#include <array>
#include <vector>
#include <string>
#include <boost/lexical_cast.hpp>
#include <boost/format.hpp>
#include <model_core/register_block.h>
#include <shared/bitvector.h>












namespace tofino {
  namespace register_classes {

class PgrAppEventJitterValueMutable : public model_core::RegisterBlock<RegisterCallback> {
public:
  enum PartyPgrAppRegRspecEnum {
    kEventIbgJitterValue,
    kEventIpgJitterValue
  };
public:
  PgrAppEventJitterValueMutable(
      int chipNumber, int index_pipe_addrmap, int index_party_pgr_app_reg_rspec, PartyPgrAppRegRspecEnum selector_party_pgr_app_reg_rspec, RegisterCallback& write_callback = 0, RegisterCallback& read_callback = 0
  )
    : RegisterBlock(chipNumber, StartOffset(index_pipe_addrmap, index_party_pgr_app_reg_rspec, selector_party_pgr_app_reg_rspec), 4, true, write_callback, read_callback, std::string("PgrAppEventJitterValueMutable")+":"+boost::lexical_cast<std::string>(index_pipe_addrmap) + "," + boost::lexical_cast<std::string>(index_party_pgr_app_reg_rspec) + "," + boost::lexical_cast<std::string>(selector_party_pgr_app_reg_rspec))
    {
    }
  PgrAppEventJitterValueMutable(
      
  )
    : RegisterBlock(0, 0, 0, true, 0, 0, "PgrAppEventJitterValueMutable")
    {
    }
public:




  uint32_t value() { return value_; }
  void value(const uint32_t &v) { value_=v; }

  bool read(
      uint32_t offset, uint32_t* data
      ) const {
    if (read_callback_) read_callback_();
    *data = value_;
    return true;
  }


  bool write(
      uint32_t offset, uint32_t data
      ) {
    value_ = data;
    if (write_callback_) write_callback_();
    return true;
  }

  void reset(
      
      ) {
    value_ = 0x0;
    if (write_callback_) write_callback_();
  }

  std::string to_string(
      uint32_t offset, bool print_zeros = false, std::string indent_string = ""
      ) const {
    std::string r("");
    bool all_zeros=true;
    r += indent_string + std::string("PgrAppEventJitterValueMutable") + ":\n";
    r += indent_string + "  " + std::string("value") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(value_) ) + "\n";
    all_zeros &= (0 == value_);
    if (all_zeros && !print_zeros) {
      return("");
    }
    else {
      return r;
    }
  }

  std::string to_string(
      bool print_zeros = false, std::string indent_string = ""
      ) const {
    std::string r("");
    bool all_zeros=true;
    r += indent_string + std::string("PgrAppEventJitterValueMutable") + ":\n";
    r += indent_string + "  " + std::string("value") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(value_) ) + "\n";
    all_zeros &= (0 == value_);
    if (all_zeros && !print_zeros) {
      return("");
    }
    else {
      return r;
    }
  }

private:
  uint32_t value_;
private:
  static int StartOffset(
      int index_pipe_addrmap, int index_party_pgr_app_reg_rspec, PartyPgrAppRegRspecEnum selector_party_pgr_app_reg_rspec
      ) {
    int offset=0;
    offset += 0x2000000; // to get to pipes
    assert(index_pipe_addrmap < 4);
    offset += index_pipe_addrmap * 0x800000; // pipe_addrmap[]
    offset += 0x700000; // to get to pmarb
    offset += 0x3c000; // to get to pgr_reg
    assert(index_party_pgr_app_reg_rspec < 8);
    offset += index_party_pgr_app_reg_rspec * 0x200; // party_pgr_app_reg_rspec[]
    switch (selector_party_pgr_app_reg_rspec) {
      case kEventIbgJitterValue:
        offset += 0x1c; // to get to event_ibg_jitter_value
        break;
      case kEventIpgJitterValue:
        offset += 0x28; // to get to event_ipg_jitter_value
        break;
      default:
        assert(0);
        break;
    }
    return offset;
  }

};









  }; // namespace register_classes
}; // namespace tofino

#endif // __REGISTER_INCLUDES_PGR_APP_EVENT_JITTER_VALUE_MUTABLE_H__
