/*******************************************************************************
 *  Copyright (C) 2024 Intel Corporation
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions
 *  and limitations under the License.
 *
 *
 *  SPDX-License-Identifier: Apache-2.0
 ******************************************************************************/

// generated by split_classes.pl
#ifndef __REGISTER_INCLUDES_PGR_APP_LOG_MUTABLE_H__
#define __REGISTER_INCLUDES_PGR_APP_LOG_MUTABLE_H__


#include <cstdint>
#include <cassert>
#include <array>
#include <vector>
#include <string>
#include <boost/lexical_cast.hpp>
#include <boost/format.hpp>
#include <model_core/register_block.h>
#include <shared/bitvector.h>












namespace tofino {
  namespace register_classes {

class PgrAppLogMutable : public model_core::RegisterBlock<RegisterCallback> {
public:
  PgrAppLogMutable(
      int chipNumber, int index_pipe_addrmap, int index_party_pgr_app_reg_rspec, RegisterCallback& write_callback = 0, RegisterCallback& read_callback = 0
  )
    : RegisterBlock(chipNumber, StartOffset(index_pipe_addrmap, index_party_pgr_app_reg_rspec), 4, true, write_callback, read_callback, std::string("PgrAppLogMutable")+":"+boost::lexical_cast<std::string>(index_pipe_addrmap) + "," + boost::lexical_cast<std::string>(index_party_pgr_app_reg_rspec))
    {
    }
  PgrAppLogMutable(
      
  )
    : RegisterBlock(0, 0, 0, true, 0, 0, "PgrAppLogMutable")
    {
    }
public:





  uint8_t statemachine() { return statemachine_; }
  void statemachine(const uint8_t &v) { statemachine_=v; }





  uint8_t timer_valid() { return timer_valid_; }
  void timer_valid(const uint8_t &v) { timer_valid_=v; }





  uint8_t portdown_valid() { return portdown_valid_; }
  void portdown_valid(const uint8_t &v) { portdown_valid_=v; }





  uint8_t recir_valid() { return recir_valid_; }
  void recir_valid(const uint8_t &v) { recir_valid_=v; }

  bool read(
      uint32_t offset, uint32_t* data
      ) const {
    if (read_callback_) read_callback_();
    *data = (statemachine_ & 0x7);
    *data |= ((timer_valid_ & 0x1) << 3);
    *data |= ((portdown_valid_ & 0x1) << 4);
    *data |= ((recir_valid_ & 0x1) << 5);
    return true;
  }


  bool write(
      uint32_t offset, uint32_t data
      ) {
    statemachine_ = (data & 0x7);
    timer_valid_ = ((data >> 3) & 0x1);
    portdown_valid_ = ((data >> 4) & 0x1);
    recir_valid_ = ((data >> 5) & 0x1);
    if (write_callback_) write_callback_();
    return true;
  }

  void reset(
      
      ) {
    statemachine_ = 0x0;
    timer_valid_ = 0x0;
    portdown_valid_ = 0x0;
    recir_valid_ = 0x0;
    if (write_callback_) write_callback_();
  }

  std::string to_string(
      uint32_t offset, bool print_zeros = false, std::string indent_string = ""
      ) const {
    std::string r("");
    bool all_zeros=true;
    r += indent_string + std::string("PgrAppLogMutable") + ":\n";
    r += indent_string + "  " + std::string("statemachine") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(statemachine_) ) + "\n";
    all_zeros &= (0 == statemachine_);
    r += indent_string + "  " + std::string("timer_valid") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(timer_valid_) ) + "\n";
    all_zeros &= (0 == timer_valid_);
    r += indent_string + "  " + std::string("portdown_valid") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(portdown_valid_) ) + "\n";
    all_zeros &= (0 == portdown_valid_);
    r += indent_string + "  " + std::string("recir_valid") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(recir_valid_) ) + "\n";
    all_zeros &= (0 == recir_valid_);
    if (all_zeros && !print_zeros) {
      return("");
    }
    else {
      return r;
    }
  }

  std::string to_string(
      bool print_zeros = false, std::string indent_string = ""
      ) const {
    std::string r("");
    bool all_zeros=true;
    r += indent_string + std::string("PgrAppLogMutable") + ":\n";
    r += indent_string + "  " + std::string("statemachine") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(statemachine_) ) + "\n";
    all_zeros &= (0 == statemachine_);
    r += indent_string + "  " + std::string("timer_valid") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(timer_valid_) ) + "\n";
    all_zeros &= (0 == timer_valid_);
    r += indent_string + "  " + std::string("portdown_valid") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(portdown_valid_) ) + "\n";
    all_zeros &= (0 == portdown_valid_);
    r += indent_string + "  " + std::string("recir_valid") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(recir_valid_) ) + "\n";
    all_zeros &= (0 == recir_valid_);
    if (all_zeros && !print_zeros) {
      return("");
    }
    else {
      return r;
    }
  }

private:
  uint8_t statemachine_;
  uint8_t timer_valid_;
  uint8_t portdown_valid_;
  uint8_t recir_valid_;
private:
  static int StartOffset(
      int index_pipe_addrmap, int index_party_pgr_app_reg_rspec
      ) {
    int offset=0;
    offset += 0x2000000; // to get to pipes
    assert(index_pipe_addrmap < 4);
    offset += index_pipe_addrmap * 0x800000; // pipe_addrmap[]
    offset += 0x700000; // to get to pmarb
    offset += 0x3c000; // to get to pgr_reg
    assert(index_party_pgr_app_reg_rspec < 8);
    offset += index_party_pgr_app_reg_rspec * 0x200; // party_pgr_app_reg_rspec[]
    offset += 0x50; // to get to log
    return offset;
  }

};









  }; // namespace register_classes
}; // namespace tofino

#endif // __REGISTER_INCLUDES_PGR_APP_LOG_MUTABLE_H__
