/*******************************************************************************
 *  Copyright (C) 2024 Intel Corporation
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions
 *  and limitations under the License.
 *
 *
 *  SPDX-License-Identifier: Apache-2.0
 ******************************************************************************/

// generated by split_classes.pl
#ifndef __REGISTER_INCLUDES_QAC_GLB_AP_DROP_STATE_CELL_H__
#define __REGISTER_INCLUDES_QAC_GLB_AP_DROP_STATE_CELL_H__


#include <cstdint>
#include <cassert>
#include <array>
#include <vector>
#include <string>
#include <boost/lexical_cast.hpp>
#include <boost/format.hpp>
#include <model_core/register_block.h>
#include <shared/bitvector.h>












namespace tofino {
  namespace register_classes {

class QacGlbApDropStateCell : public model_core::RegisterBlock<RegisterCallback> {
public:
  QacGlbApDropStateCell(
      int chipNumber, int index_qac_glb_ap_drop_state_cell, RegisterCallback& write_callback = 0, RegisterCallback& read_callback = 0
  )
    : RegisterBlock(chipNumber, StartOffset(index_qac_glb_ap_drop_state_cell), 4, false, write_callback, read_callback, std::string("QacGlbApDropStateCell")+":"+boost::lexical_cast<std::string>(index_qac_glb_ap_drop_state_cell))
    {
    }
  QacGlbApDropStateCell(
      
  )
    : RegisterBlock(0, 0, 0, false, 0, 0, "QacGlbApDropStateCell")
    {
    }
public:





  uint8_t &drop_state() { return drop_state_; }

  bool read(
      uint32_t offset, uint32_t* data
      ) const {
    if (read_callback_) read_callback_();
    *data = (drop_state_ & 0xf);
    return true;
  }


  bool write(
      uint32_t offset, uint32_t data
      ) {
    drop_state_ = (data & 0xf);
    if (write_callback_) write_callback_();
    return true;
  }

  void reset(
      
      ) {
    drop_state_ = 0x0;
    if (write_callback_) write_callback_();
  }

  std::string to_string(
      uint32_t offset, bool print_zeros = false, std::string indent_string = ""
      ) const {
    std::string r("");
    bool all_zeros=true;
    r += indent_string + std::string("QacGlbApDropStateCell") + ":\n";
    r += indent_string + "  " + std::string("drop_state") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(drop_state_) ) + "\n";
    all_zeros &= (0 == drop_state_);
    if (all_zeros && !print_zeros) {
      return("");
    }
    else {
      return r;
    }
  }

  std::string to_string(
      bool print_zeros = false, std::string indent_string = ""
      ) const {
    std::string r("");
    bool all_zeros=true;
    r += indent_string + std::string("QacGlbApDropStateCell") + ":\n";
    r += indent_string + "  " + std::string("drop_state") +  ": 0x" + boost::str( boost::format("%x") % static_cast<uint>(drop_state_) ) + "\n";
    all_zeros &= (0 == drop_state_);
    if (all_zeros && !print_zeros) {
      return("");
    }
    else {
      return r;
    }
  }

private:
  uint8_t drop_state_;
private:
  static int StartOffset(
      int index_qac_glb_ap_drop_state_cell
      ) {
    int offset=0;
    offset += 0x400000; // to get to tm_top
    offset += 0x80000; // to get to tm_qac_top
    offset += 0x20000; // to get to qac_common
    offset += 0x280; // to get to qac_common_block_drop_st_qac_glb_ap_drop_state_cell
    assert(index_qac_glb_ap_drop_state_cell < 8);
    offset += index_qac_glb_ap_drop_state_cell * 0x4; // qac_glb_ap_drop_state_cell[]
    return offset;
  }

};









  }; // namespace register_classes
}; // namespace tofino

#endif // __REGISTER_INCLUDES_QAC_GLB_AP_DROP_STATE_CELL_H__
