/*******************************************************************************
 *  Copyright (C) 2024 Intel Corporation
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions
 *  and limitations under the License.
 *
 *
 *  SPDX-License-Identifier: Apache-2.0
 ******************************************************************************/

// generated by split_classes.pl
#ifndef __REGISTER_INCLUDES_TM_SCH_PIPE_RSPEC_INTR_H__
#define __REGISTER_INCLUDES_TM_SCH_PIPE_RSPEC_INTR_H__


#include <cstdint>
#include <cassert>
#include <array>
#include <vector>
#include <string>
#include <boost/lexical_cast.hpp>
#include <boost/format.hpp>
#include <model_core/register_block.h>
#include <shared/bitvector.h>











#include "tm_sch_pipe_rspec_intr_enable0.h"
#include "tm_sch_pipe_rspec_intr_enable1.h"
#include "tm_sch_pipe_rspec_intr_freeze_enable.h"
#include "tm_sch_pipe_rspec_intr_inject.h"
#include "tm_sch_pipe_rspec_intr_status.h"

namespace tofino {
  namespace register_classes {

class TmSchPipeRspecIntr : public model_core::RegisterBlock<RegisterCallback> {
public:
  TmSchPipeRspecIntr(
      int chipNumber, int index_tm_sch_pipe_rspec, RegisterCallback& write_callback = 0, RegisterCallback& read_callback = 0
  )
    : RegisterBlock(chipNumber, StartOffset(index_tm_sch_pipe_rspec), 20, false, write_callback, read_callback, std::string("TmSchPipeRspecIntr")+":"+boost::lexical_cast<std::string>(index_tm_sch_pipe_rspec))
    {
    }
  TmSchPipeRspecIntr(
      
  )
    : RegisterBlock(0, 0, 0, false, 0, 0, "TmSchPipeRspecIntr")
    {
    }
public:






  TmSchPipeRspecIntrStatus &intr_status() { return intr_status_; }







  TmSchPipeRspecIntrEnable0 &intr_enable0() { return intr_enable0_; }







  TmSchPipeRspecIntrEnable1 &intr_enable1() { return intr_enable1_; }








  TmSchPipeRspecIntrInject &intr_inject() { return intr_inject_; }





  TmSchPipeRspecIntrFreezeEnable &intr_freeze_enable() { return intr_freeze_enable_; }

  bool read(
      uint32_t offset, uint32_t* data
      ) const {
    if (offset >= 0x20 && offset < 0x24) {
      offset -= 0x20;
      if (read_callback_) read_callback_();
      intr_status_.read( offset, data );
    }
    else if (offset >= 0x24 && offset < 0x28) {
      offset -= 0x24;
      if (read_callback_) read_callback_();
      intr_enable0_.read( offset, data );
    }
    else if (offset >= 0x28 && offset < 0x2c) {
      offset -= 0x28;
      if (read_callback_) read_callback_();
      intr_enable1_.read( offset, data );
    }
    else if (offset >= 0x2c && offset < 0x30) {
      offset -= 0x2c;
      if (read_callback_) read_callback_();
      intr_inject_.read( offset, data );
    }
    else if (offset >= 0x30 && offset < 0x34) {
      offset -= 0x30;
      if (read_callback_) read_callback_();
      intr_freeze_enable_.read( offset, data );
    }
    return true;
  }


  bool write(
      uint32_t offset, uint32_t data
      ) {
    if (offset >= 0x20 && offset < 0x24) {
      offset -= 0x20;
      intr_status_.write( offset, data );
      if (write_callback_) write_callback_();
    }
    else if (offset >= 0x24 && offset < 0x28) {
      offset -= 0x24;
      intr_enable0_.write( offset, data );
      if (write_callback_) write_callback_();
    }
    else if (offset >= 0x28 && offset < 0x2c) {
      offset -= 0x28;
      intr_enable1_.write( offset, data );
      if (write_callback_) write_callback_();
    }
    else if (offset >= 0x2c && offset < 0x30) {
      offset -= 0x2c;
      intr_inject_.write( offset, data );
      if (write_callback_) write_callback_();
    }
    else if (offset >= 0x30 && offset < 0x34) {
      offset -= 0x30;
      intr_freeze_enable_.write( offset, data );
      if (write_callback_) write_callback_();
    }
    return true;
  }

  void reset(
      
      ) {
    intr_status_.reset();
    intr_enable0_.reset();
    intr_enable1_.reset();
    intr_inject_.reset();
    intr_freeze_enable_.reset();
    if (write_callback_) write_callback_();
  }

  std::string to_string(
      uint32_t offset, bool print_zeros = false, std::string indent_string = ""
      ) const {
    std::string r("");
    bool all_zeros=true;
    all_zeros=false;
    if (offset >= 0x20 && offset < 0x24) {
      offset -= 0x20;
      r += intr_status_.to_string(offset,print_zeros,indent_string) ;
    }
    else if (offset >= 0x24 && offset < 0x28) {
      offset -= 0x24;
      r += intr_enable0_.to_string(offset,print_zeros,indent_string) ;
    }
    else if (offset >= 0x28 && offset < 0x2c) {
      offset -= 0x28;
      r += intr_enable1_.to_string(offset,print_zeros,indent_string) ;
    }
    else if (offset >= 0x2c && offset < 0x30) {
      offset -= 0x2c;
      r += intr_inject_.to_string(offset,print_zeros,indent_string) ;
    }
    else if (offset >= 0x30 && offset < 0x34) {
      offset -= 0x30;
      r += intr_freeze_enable_.to_string(offset,print_zeros,indent_string) ;
    }
    if (all_zeros && !print_zeros) {
      return("");
    }
    else {
      return r;
    }
  }

  std::string to_string(
      bool print_zeros = false, std::string indent_string = ""
      ) const {
    std::string r("");
    bool all_zeros=true;
    all_zeros=false;
    r += intr_status_.to_string(print_zeros,indent_string) ;
    r += intr_enable0_.to_string(print_zeros,indent_string) ;
    r += intr_enable1_.to_string(print_zeros,indent_string) ;
    r += intr_inject_.to_string(print_zeros,indent_string) ;
    r += intr_freeze_enable_.to_string(print_zeros,indent_string) ;
    if (all_zeros && !print_zeros) {
      return("");
    }
    else {
      return r;
    }
  }

private:
  TmSchPipeRspecIntrStatus intr_status_;
  TmSchPipeRspecIntrEnable0 intr_enable0_;
  TmSchPipeRspecIntrEnable1 intr_enable1_;
  TmSchPipeRspecIntrInject intr_inject_;
  TmSchPipeRspecIntrFreezeEnable intr_freeze_enable_;
private:
  static int StartOffset(
      int index_tm_sch_pipe_rspec
      ) {
    int offset=0;
    offset += 0x400000; // to get to tm_top
    offset += 0xc0000; // to get to tm_sch_top
    assert(index_tm_sch_pipe_rspec < 4);
    offset += index_tm_sch_pipe_rspec * 0x10000; // tm_sch_pipe_rspec[]
    return offset;
  }

};





  }; // namespace register_classes
}; // namespace tofino

#endif // __REGISTER_INCLUDES_TM_SCH_PIPE_RSPEC_INTR_H__
